### ISSUE TITLE
Browser name banners still just say "Browser" and it's ugly and confusing

### ISSUE THREAD

**Issue by revolutionaryking7** [fork-maintainers/iceraven-browser#10]
### What is the user problem or growth opportunity you want to see solved?

In the homepage it just shows browser without any name.. Can you please add a logo or text on homepage and in about iceweasel page

### How do you know that this problem exists today? Why is this important?
The name place seems empty 

### Who will benefit from it?
All users

**Comment by interfect** [comment]
Yeah it's definitely ugly there. I know how to do it: draw a new https://github.com/interfect/fenix/blob/fork/app/src/forkRelease/res/drawable-xxxhdpi/ic_logo_wordmark_normal.png and https://github.com/interfect/fenix/blob/fork/app/src/forkRelease/res/drawable-xxxhdpi/ic_logo_wordmark_private.png and then scale down the lower-resolution versions from them. I just need (or someone else needs) to actually make the images.

**Comment by eNV25** [comment]
Can't we just remove it or leave it blank if we can't make one?

**Comment by interfect** [comment]
That's also an option, I suppose.

**Comment by bbigam** [comment]
I'm not sure how to do it myself, but I'd suggest just having a simple "Iceweasel" wordmark.

**Comment by bbigam** [comment]
Would something like this do it?
You can't see the text of the second one because it's white text. :-)
It's nothing special but it was easy and might work at least as a placeholder.
I'm not sure what's required for all the scaling, though.

![ic_logo_wordmark_normal](https://user-images.githubusercontent.com/69259971/92418516-cd691c80-f135-11ea-9601-fc368ddc5934.png)
![ic_logo_wordmark_private](https://user-images.githubusercontent.com/69259971/92418517-d0640d00-f135-11ea-91e9-9268edc6f297.png)

**Comment by bbigam** [comment]
Actually, this is probably better. Made the font match properly, plus the browsers has been listed as "Iceweasel Mobile."
![ic_logo_wordmark_normal7](https://user-images.githubusercontent.com/69259971/92418753-34d39c00-f137-11ea-9740-71a788dfd49b.png)
![ic_logo_wordmark_private8](https://user-images.githubusercontent.com/69259971/92418764-4ae15c80-f137-11ea-9055-46994b75add4.png)

**Comment by interfect** [comment]
That could work.

I'd caution against working too hard on the branding assets before we settle the naming issue in #36 in about a week. But those images look a lot like what is needed.

The Mozilla ones had a logo image to the left of the name, but we don't necessarily need to replicate that.

As for the scaling, the easy thing to do is to just put the full-resolution image in each of the DPI folders and let the device scale it down.

The right thing to do is go to each DPI folder in `app/src/main/res`, figure out how big the wordmark image there is in pixels, and resize down to that resolution in the image editor for the corresponding DPI folder in `app/src/forkRelease/res`. This is so the tiny phone doesn't have to think as hard, and because I think the phone resizes with nearest or some other ugly interpolation while an image editor can do better.

The fancy thing to do is re-render the text at every size so the edges are hinted pixel-perfect.

**Comment by bbigam** [comment]
It looks like the images currently in here (the ones that say __________ Browser) are all the same size. Would like like me to do a PR with the "easy" solution for now, to hold us over for the next release until the name is decided? That would only take a few minutes. Or just wait?

**Comment by interfect** [comment]
If you want to make a PR I can merge it. They're all the same size because I went the "easy" route when filling off the Mozilla branding and didn't bother resizing anything. It looks bad on the emulator but fine on my real device, so we can probably wait on resizing until we have the final images with the final name.

September 7, 2020 3:32 PM, "bbigam" <notifications@github.com (mailto:notifications@github.com?to=%22bbigam%22%20<notifications@github.com>)> wrote:
	It looks like the images currently in here (the ones that say __________ Browser) are all the same size. Would like like me to do a PR with the "easy" solution for now, to hold us over for the next release until the name is decided? That would only take a few minutes. Or just wait?

**Comment by bbigam** [comment]
Done, with the easy option saying Iceweasel Mobile.
https://github.com/fork-maintainers/iceweasel/pull/85

**Comment by ghost** [comment]
But why ?
Browser seems very subtle and minimalistic
I don't like browsers that brand every part of the UI with their name 

If @interfect you are going to brand it please add option to customise homepage  it's look like like icon text background

**Comment by bbigam** [comment]
It's just the browser's name, a feature inherited from upstream. We have it
actually more minimalistic, just the name, whereas upstream also has the
logo here.

**Comment by bbigam** [comment]
A little more info: without a name in the banner we'd just have unusable
empty space. It's not designed to be user-customizable, so someone would
have to write the code for that.

**Comment by bbigam** [comment]
Fixed in https://github.com/fork-maintainers/iceraven-browser/pull/85 and updated in https://github.com/fork-maintainers/iceraven-browser/pull/110
