### ISSUE TITLE
Fully rebrand to Iceraven Browser

### ISSUE THREAD

**Issue by interfect** [fork-maintainers/iceraven-browser#111]
As the winner of the name poll, we want to change the project name to "Iceraven", and probably "Iceraven Browser" where convenient because of the other Iceraven that exist.

The header images have already been updated, but we still need to:

* [x] Draw a new icon and replace the old one (via Android Studio SVG import). Doesn't have to be final or even good but it should probably not be the one we have with a weasel.
* [x] Rename the Github project (maybe @interfect needs to do this?). Here we would want to be `iceraven-browser` I think
* [x] Make sure moving the repo didn't upset Travis
* [x] `s/Iceweasel/Iceraven/g` in all the strings files, and the tests that demand to know the browser name.
* [x] Change the app ID. When we get into F-Droid we probably want an app ID we are definitely sticking with. What domain should it be under?
* [x] Ship a release

Anything I'm forgetting?

**Comment by bbigam** [comment]
I would be okay with us using a generic browser icon temporarily (i.e. from Material Icons) until we get a proper Iceraven one - that way we could build a new rebranded release even if we don't have a fancy new icon yet. I don't know anything about icons and am not artsy myself.

I definitely think we should change the app ID. This is our new name, let's use it fully.

Suggestion: pin this issue. We need to get this done to complete the rebranding for a release.

**Comment by CharmCityCrab** [comment]
Since I'm not an artist (My artistic skills are limited to drawing stick figures and making mild alterations to pre-existing images and changing their formats and pixel scale with GIMP), I don't really have the ability to propose a logo of my own creation.

However, I've been doing some web searches and finding some interesting stuff on Pintrest and other sites that might with some mild alterations work as at least temporary logos for Iceraven pending potentially in the future getting a custom design made specifically for the browser.

The thing is here, is that to be legally in the clear, if we were to select, say, a Pintrest logo from a random person, we would have to email that person to get permission to use it as the browser logo.  I think it's probably easy enough to email people and ask, but I'm not sure about how we should time that relative to a decision.  It probably wouldn't be appropriate for me (Especially since I'm not a maintainer) to go around emailing a bunch of people asking them if they would consider letting Iceraven use their logo and then post a bunch of them here and have people pick after the fact, leaving a lot of artists contacted having to consider whether to give permission and then not having their work used even after being asked.

It seems like the thing to do, if we are going to request a license to pre-existing artwork, would be to have the maintainers give the okay to something from their end as the first choice, or to authorize votes on some potential choices, and then approach the person who created the artwork selected to ask permission when we are sure we'd use it if permission is given.  It'd probably be a good idea to also have 2nd and 3rd choices ready so that if the one we want says no or the artist fails to respond to our queries within a set period of time, we could just ask the next person and not have to redo the search process, just in the interest of getting this done in a reasonable period of time.

An even better idea, just as a stopgap to get an icon that looks like a raven to go with the new browser name that looks okay while the browser solicits a more permanent logo solution, might be to see if we can find a repo of public domain or open-source art (with a license that allows us to alter it and use it as a browser icon) where we can just find a picture of a black raven (ideally, facing the users), and maybe add some white or blue snow or ice to the tips of it's wing, beak, talons, etc., and see if people are into that enough to use it temporarily.  Anyone know any open-source or public domain art websites we could look through?

Of course, the ideal would be if we had an artists who could just design something for us, but there is a good chance that we do not, and that a design from scratch might have to wait.

Though a short term logo taken from pre-existing artwork by permission of the artist or taken because it's public domain or has licensing that allows us to may not allow us to be too picky for the first temporary logo, I'm curious about what people are looking for in a long term logo.  Anyone have any descriptions that want to throw out there, or design elements they'd like to see excluded or excluded?

Is anyone here actually an artist who could create something?

**Comment by CharmCityCrab** [comment]
Here are a few things I found that looked interesting to me.  Of course, in these cases, we would need the permission of the artist to use them (See previous post above), but could seek that permission if we find one that works for interfect and the other maintainers, and is popular with Iceweasel/Iceraven users.  Any of these look good?

You have to scroll down a bit to see the full art on these pages.  Some look like they are complete with just the upper part, but scrolling down reveals the rest of the drawing/painting/whatever.

Option 1:

https://www.pinterest.com/pin/10414642876756335/

Option 2:

https://www.pinterest.com/pin/334110866097248942/

Option 3:

https://www.pinterest.com/pin/544935623645747003/

Option 4:

https://www.pinterest.com/pin/263038434467554502/

Note:  Option 4 is just "pinned" by someone, the actual artist appears to be http://www.nathalieparenteau.com/ (My sense is that this would be the hardest one to get permission to use for free, because the artist appears very established and seems to sell a lot of stuff).

The option numbering is just so people can discuss them by number and have everyone else know what they are talking about.  I'm not suggesting an order of preference, that these are the only options, or even that they are options at all (The artists could deny permission to use them or maybe the maintainers won't like them or whatever).

Hopefully more options will be found and suggested by others as well.

Of course these four, I think I like Option 1 the best.  

Option 4, if adopted, would be a clear homage to our Firefox heritage, especially if we could put a blue/green planet inside, but it seems like Option 4 would require some money, that we'd have trouble getting permission to alter it ourselves to add the planet, and that if we asked the artist to add the planet for us, that would cost us even more.  Since it's an all-volunteer project, we likely have a budget of $0 for this, unless someone likes something so much that they are willing to buy a license for it from the artist for the project's use.

**Comment by bbigam** [comment]
Option 3 might be okay temporarily.
I think asking permission needs to include asking to use the image under a
free license. CC-BY and CC-BY-SA are good ones for content.

I picture our final logo being in the general shape of the Firefox logo.
I'm imagining a black raven with dark blue highlights wrapped partly around
an ice-white globe with light blue highlights. (The blue keeps it from
being just a black and white logo.) But I have no idea how to make this. :-)

**Comment by CharmCityCrab** [comment]
> 
> I picture our final logo being in the general shape of the Firefox logo. I'm imagining a black raven with dark blue highlights wrapped partly around an ice-white globe with light blue highlights. (The blue keeps it from being just a black and white logo.) But I have no idea how to make this. :-)

What about the globe being a planet with blue water and green land, with the land mostly being iced over (White?), but green in certain spots, especially towards the center/equator?  I kind of like the idea of it looking like a planet, similar in general format to the old Firefox logos, before they just turned a planet into a ball.  The way I envision it, the planet in this case would not be earth, but also would not be the old Mozilla planet for copyright reasons.  It'd be a planet with it's own continent, ocean, and glacier shapes; conceptually going through an ice age, or being a little further from it's sun than earth is from our's (But not much further).  Ideally, it'd be missing the "glare" present on most Firefox planet logos and be more like the 2004 version with no glare in that respect.

**Comment by bbigam** [comment]
Sure, why not? If someone is willing and able to do it! :-)

**Comment by interfect** [comment]
Those pins make a good moodboard for logo design, but it doesn't look like any of them (except maybe the last one?) are vector art, and even then you need to do some stuff differently when drawing things for icon size, and simplify/chibi-fy the image. Though I suppose we could get in touch with any of those artists and try and commission something "like that, but a tiny SVG".

Android Studio has some builtin icons I think we can use as placeholders.

**Comment by interfect** [comment]
I renamed the repo to `iceraven-browser`. We'll see if that upsets any tests.

All the links and Git remotes should redirect, but we might want to update the README URLs.

**Comment by interfect** [comment]
What domain do we want the AppID under?

For F-Droid, we could probably use `io.github.fork-maintainers.iceraven-browser`. In the [absolutely massive metadata repository](https://gitlab.com/fdroid/fdroiddata/-/tree/master/metadata) there's a lot of `com.github`, and I assume `io.github` is already represented too, but I got bored of scrolling to look for it.

**Comment by bbigam** [comment]
I think really long app IDs are obnoxious, so I suggest leaving out
-browser if that's the domain we go with. It'd be unique still.

**Comment by CharmCityCrab** [comment]
A very small side effect of the rebranding was that the final paragraph of the introduction in the readme.md right above above the "Installation" subheader now says "Iceraven" in two spots where it should say "Iceweasel".

Specifically, it now references "Debian Iceraven, Parabola GNU/Linux-libre Iceraven".  Those actually should of course still be "Iceweasel". Other than that, the find/replace was very smooth and still fits context properly everywhere I've looked.

I didn't think this merited a separate issue, but it's fine if someone wants to split it out.  I could also probably do a pull request if desired, but my pull requests tend to take an hour to put together whereas I suspect a maintainer could get this change made and committed to the working version in two minutes flat. :)

**Comment by interfect** [comment]
Here's a half-arsed bird with a circle which I actually have as SVG:

![image](https://user-images.githubusercontent.com/752054/93422495-bbd7f100-f868-11ea-85f0-1ba82a9bef83.png)

We could go more with bird head and circle like https://www.pinterest.com/pin/10414642876756335/

**Comment by interfect** [comment]
@abhijitvalluri Do you know anything about sizing vector drawables properly when you import them into android studio? I made my SVG like 50 px big, and I set the size to 108 dp in the import wizard, and I just got the middle of it displayed as the icon. Am I supposed to just enter the size of the SVG again, and it automatically makes it big enough to be an app icon?

**Comment by CharmCityCrab** [comment]
> Here's a half-arsed bird with a circle which I actually have as SVG:
> 
> ![image](https://user-images.githubusercontent.com/752054/93422495-bbd7f100-f868-11ea-85f0-1ba82a9bef83.png)
> 
> We could go more with bird head and circle like https://www.pinterest.com/pin/10414642876756335/

Either could work in the interests of getting something out.  While simplistic, it actually does seem very much in keeping with recent trends in Android icon design.

Perhaps with a black fill instead of a white fill of the empty space?

I suspect that in the long run, the user base that will be attracted by Iceraven is going to want the more detailed designs of yore (i.e. a planet and not a ball, and a very detailed bird and not a silhouette), but it looks good enough to use temporarily to get releases out until something better comes along.

On a related note, if the next release is the rebrand and we aren't going to do a final Iceweasel first, you may want to consider using versioning instead of "Fork 11"- i.e. "Iceraven 1.0", "Iceraven 1.11", "Iceraven 11.0", "Iceraven 80.0", "Iceraven 0.11", or whatever seems most suitable (I trust everyone sees where the example numbers are coming from.).

**Comment by bbigam** [comment]
I suggest using that existing svg as a temporary icon, good enough for now! (Assuming a free license.)

How close are we to release? What do we lack?

**Comment by abhijitvalluri** [comment]
Does anyone know someone with graphics design experience who may be able to design a nice logo for us? Or we could probably ask in Reddit for someone to create a design for us? 

There are some really cool designs of the FF logo on reddit, you can do a search on the Firefox reddit to find them. Here is a sample:
[![Kawaii Firefox icon](https://i.redd.it/nz1z3c1yc1j51.png)](https://www.reddit.com/r/firefox/comments/ig0n5q/my_girlfriend_made_an_aesthetic_firefox_icon_to/)

[![Minimalist](https://i.redd.it/h6n0qttrfyy41.png)](https://www.reddit.com/r/firefox/comments/gkcag5/minimalist_logoicon_reimagining_by_me/)

[Firefox Neon](https://www.reddit.com/r/firefox/comments/bn4a7w/new_version_of_the_mozilla_firefox_logo_by_an/)

You can find more here: https://www.reddit.com/r/firefox/search?q=logo&restrict_sr=1

**Comment by abhijitvalluri** [comment]
I found this on dreamstime which is a good example of what our logo for a bird wrapping the globe can look like: 
[![Preview](https://thumbs.dreamstime.com/z/cardinal-bird-holds-mother-earth-to-protect-26890911.jpg)](https://www.dreamstime.com/stock-image-cardinal-bird-holds-mother-earth-to-protect-image26890911)

And an example of a simpler/abstract design:
![Abstract design](https://cdn.pixabay.com/photo/2016/12/27/13/10/logo-1933884__340.png)

**Comment by abhijitvalluri** [comment]
> @abhijitvalluri Do you know anything about sizing vector drawables properly when you import them into android studio? I made my SVG like 50 px big, and I set the size to 108 dp in the import wizard, and I just got the middle of it displayed as the icon. Am I supposed to just enter the size of the SVG again, and it automatically makes it big enough to be an app icon?

I am not sure, I did not do much of this in the past. I tried importing a 48dp x 48dp SVG into Android studio, and imported it at 150 x 150 dp and it seemed to be fine. If you are having trouble importing your SVG at 108 dp, try doing 50 dp and scale it up where needed. That may work?

**Comment by interfect** [comment]
> I suggest using that existing svg as a temporary icon, good enough for now! (Assuming a free license.)
> 
> How close are we to release? What do we lack?

I think we just need a PR to set the app ID to `io.github.fork-maintainers.iceraven` and one to replace the weasel icon with a temp icon at a reasonable size, and then we can release.

I might be able to do those today.

Asking Reddit for a final icon might work.

**Comment by interfect** [comment]
OK, I think we have all the pieces. I'm going to do a release!

**Comment by abhijitvalluri** [comment]
Hooray! I think we have finished all the steps laid out in the first post to fully rebrand to Iceraven. The only thing left to do is a proper logo for the browser and we are golden!

**Comment by interfect** [comment]
I'm going to close this and let "good logo" be its own issue.
