### ISSUE TITLE
History and Bookmarks pages need search, and History needs timestamps

### ISSUE THREAD

**Issue by revolutionaryking7** [fork-maintainers/iceraven-browser#113]
### What is the user problem or growth opportunity you want to see solved?
Can you please design history and bookmark page with a card style layout similar to Microsoft edge? It looks awesome... Also in history page time can be added with a search button

### How do you know that this problem exists today? Why is this important?
The UI looks outdated and does not provide the basic functionalities 

### Who will benefit from it?
All users
![Screenshot_20200915-124107945 (1)](https://user-images.githubusercontent.com/58127841/93177778-ecc50280-f750-11ea-9b31-fe6f6cdadaca.jpg)

**Comment by CharmCityCrab** [comment]
Search functionality would be really helpful.  If only one time part of the above proposal can implemented, that would be the part I'd be rooting for.  Times and dates would be helpful as well, although not to the same extent as search.

As far as the card layout goes, that's really an aesthetic thing that doesn't allow you to do more with your browser the way the above two items mentioned would.  I think Iceraven is more about giving users the ability to do more and know more than it is about an aesthetic, not that aesthetic concerns are entirely irrelevant.

I also have to be honest- I don't really like card layouts.  It wouldn't bother me if it was part of bringing in important functionality like that, though.  They just, for me, are part of a design fad that's in vogue and that one day will pass.  They don't look awful- and if someone said it'll help make Iceraven popular with the trendy people of the tech world or the mobile would in general, they'd be fine with me.  It's the functionality aspect of this issue page that really appeal to me, though.  Regardless of appearance (current, card, or other), search and date/time are really features that should be there.  It's almost hard to believe Mozilla didn't put them there upstream, but of course their perceived failings with the Firefox version of Fenix are part of why Iceraven exists.  A lot of things are missing from Firefox for Android right now.

It's unfortunate that Edge is a fork of Chromium rather than a fork of Fenix.  If it were closer to Iceraven's code (Which is a fork of Fenix/Firefox), I would say just take that bookmark system (Assuming it's open-source like the browser it's based on) and replace the Firefox bookmark system with it (Even if it means adopting the card thing).  However, as things stand, I assume this kind of stuff would have to implemented from scratch because of the differences between Chromium and Fenix based browsers.

**Comment by interfect** [comment]
I've renamed this to describe the specific functional features that Edge has that we don't.

I'm fine with the current design language and wouldn't recommend changing to cards *just* so it can be cards, but we definitely could improve the navigability of History and Bookmarks.

**Comment by akliuxingyuan** [comment]
@sheikh-azharuddin Search Ability for History and Bookmarks was already implemented in upstream, and we don't have enough space to display history each timestamp
