### ISSUE TITLE
[Bug] Google is forced on every update

### ISSUE THREAD

**Issue by resynth1943** [fork-maintainers/iceraven-browser#136]
## Steps to reproduce

Update the application.

### Expected behavior

The default search engine carries over.

### Actual behavior

The search engine is reset to Google.
Perhaps we should also think about switching the default?

### Device information

* Android device: Pixel 2 XL, Android 10
* Fenix version: 

- iceraven-1.0.0 (Build #2015764507)
- AC: 60.0.20200917130150, a1a5c582c
- GV: 80.0.2-20200903001900
- AS: 61.0.13

**Comment by bbigam** [comment]
Did this happen for you between previous Iceweasel updates? If so, it's a bug.

If it only happened with the new Iceraven release, that's expected. The app ID changed, so Iceraven did not inherit Iceweasel's settings. Android sees Iceraven as an entirely new app.

**Comment by CharmCityCrab** [comment]
> ## Steps to reproduce
> 
> Update the application.
> ### Expected behavior
> 
> The default search engine carries over.
> ### Actual behavior
> 
> The search engine is reset to Google.
> Perhaps we should also think about switching the default?

Did the search engine keep switching back to Google on updates previous to the most recent one?

The reason why that question is important is because, on the first 10 releases, when the browser was called Iceweasel, each subsequent release should have picked up settings, like your preferred search engine, from any previous versions installed.

_However_, the most recent update, from what was referred to as "Iceweasel Fork 10" to "Iceraven 1.0" (The most current version as of when I'm typing) did not have the capability to carry over any settings or preferences.  

I think the developers would have liked to have been able to do something to have the update carry them over, but the problem was that changing the browser's app ID from something related to "Iceweasel" to something related to "Iceraven", meant that Android viewed the previous update and the current APK as being two separate apps.  This change was going to have to happen at some point, but shouldn't repeat itself if that's the cause of what happened to you.  

Iceraven 1.0 to Iceraven 1.1 or Iceraven 2.0 should carry over your browser preference from previous Iceraven (Incidentally, people should probably uninstall Iceweasel once they upgrade to Iceraven (It'll clear up some hard drive space), unless they are using Iceweasel as a reference to slowly copy over stuff to Iceraven or so that they can open it to look at their browsing history prior to the first Iceraven (A quicker more automated way to do this would just be to have both browsers signed into Firefox Sync and wait for them to sync with each other, but that will only pick up some things, like history and bookmarks, not everything, and there are valid reasons why some people may not want to use Firefox Sync.  I don't use Firefox Sync, for example.  If you use it, though, it'll be helpful with this transition.).

In theory, someone could have designed a little program to import all the old settings from Iceweasel to Iceraven, that perhaps could have been repurposed to import Firefox and/or Chrome settings to Iceraven in the future, but that's a lot of work and would have delayed the release.  Plus, there's the question of where we want the limited developer hours people have to contribute to go to- the browser itself or side programs related to the browser.  I'm sure they'd be happy to look over a patch or a small ancillary program that does this in the future for people switching from other browsers if someone wants to create one and submit it to them, though.

As far as the default search engine goes- Good news!  Issue #80 covers that, and the conclusion reached was that the browsers maintainers would like to switch to DuckDuckGo as Iceraven's default search engine.  They are just having some mild technical difficulties getting it done right now.  It's on the agenda, though!

**Comment by interfect** [comment]
It's less "mild technical difficulties" and more "somebody has to take the time to do it". I think just dumping a modified copy of the JSON mentioned in #80 into the app's res folder might manage it. Anyone want to try that and make a PR?

I think to see if we can reproduce *this* bug we need to wait until the next release. Then we can check if search settings are overridden, and, if not, declare it fixed.

**Comment by revolutionaryking7** [comment]
Just a side question.... From Where to download the latest build ?

**Comment by CharmCityCrab** [comment]
> Just a side question.... From Where to download the latest build ?

https://github.com/fork-maintainers/iceraven-browser/releases

Most users will want to download and install the first APK download under "assets" in the most recent blog style entry at the top of the page.

**Comment by revolutionaryking7** [comment]
> > Just a side question.... From Where to download the latest build ?
> 
> https://github.com/fork-maintainers/iceraven-browser/releases
> 
> Most users will want to download and install the first APK download under "assets" in the most recent blog style entry at the top of the page.

Thanks buddy👍
