### ISSUE TITLE
Modern icon

### ISSUE THREAD

**Issue by TheEvilSkeleton** [fork-maintainers/iceraven-browser#14]
The logo looks ancient and does not match with any of Android's UI, to be honest.

I have found some fanmade(?) icons:

- https://wiki.ubuntu.com/IceWeaselIcon/
- https://iconarchive.com/show/papirus-apps-icons-by-papirus-team/iceweasel-icon.html

**Comment by interfect** [comment]
These look OK. The second one comes in SVG. I like the [winner on the Ubuntu wiki](https://wiki.ubuntu.com/IceWeaselIcon?action=AttachFile&do=get&target=IYY_new_tangoish.png) better, but I don't immediately see an SVG for it.

The way to actually change the icon is to take the SVG and use Android Studio's importer to replace https://github.com/interfect/fenix/blob/fork/app/src/forkRelease/res/drawable/ic_launcher_foreground.xml with it. There's also https://github.com/interfect/fenix/blob/fork/app/src/forkRelease/res/ic_launcher-web.png which wants to be a rasterized version. If the background color needs to change for the icon to look good, that's set in https://github.com/interfect/fenix/blob/10c43fdbabb0427dec1f826b54ff243305531e5b/app/src/forkRelease/res/values/colors.xml#L6

**Comment by TheEvilSkeleton** [comment]
I'll try to use this program to convert the PNG to SVG: https://github.com/xyproto/png2svg.

I don't know how to use Go, so I've asked for support in a public chat, hope I can get it installed

**Comment by TheEvilSkeleton** [comment]
[Iceweasel.zip](https://github.com/interfect/fenix/files/5143950/Iceweasel.zip)
I hope this is good

**Comment by CharmCityCrab** [comment]
I would suggest, just as general principles, that a planet with clearly defined water and continents, and a white weasel with a visible paw, be requirements of any potential new logo (I'm not saying the main logos under consideration don't meet those potential requirements.  It's just something to keep in mind as there may be more potential logos that people put forward.).

The reason is that Firefox excluding the fox's paw and turning their planet into a ball are (As best I can tell, at least) the top two complaints about Firefox's logo online.  Since IceWeasel is an alternative, it makes sense to reflect that in it's logo by making sure that the two most frequent FF logo complaints don't apply to IW.

It also might be worth *considering* that an older looking logo like the current one would also be an alternative to recent designing trends (Material theme and beyond) on Android, and that for some people that may truly be a feature and not a bug. Normally, one wants to fit in with the operating system's guidelines and style, but, at the same time, but maybe this is a project that "We're different" would have value for.

Anyway, I don't have strong opinions on any of this (Other than the planet with continents- I really miss that from recent Firefox logos) ).  I just thought I'd bring it up because I just saw a Reddit thread with 250 or more upvotes trying to restore the Firefox logo's paw (And this isn't the first time).  A "logo choice" screen under options or settings like the DuckDuckGo browser has in it's GUI might be a long-term possibility, but it seems like one of those things that might be better broached down the road because there are a lot of more important priorities right now code wise for IceWeasel.

One thing that should also probably be brought up is whether IceWeasel is the name the project plans to stick with long-term.  If it's not, updating the look and feel of the logo might be work that can only be used for a short period of time and might be worth skipping over for that reason, so the real work could begin upon rebranding *if* rebranding is planned, and to save people time and energy now.

IceWeasel is an iconic storied name, which makes it a cool thing to have.  However, the weaknesses of having a name that's been used before a zillion different ways and can be used by anyone going forward, is that there is potential for a lot of user confusion and potentially malicious (Or just buggy or different) implementations of IceWeasel could be distributed various places by people who have nothing to do with this project, with code that has nothing to do with this project, and this project could get blamed for that or take hits to it's reputation over it.

Plus, while the project could probably sell IceWeasel branded merchandise either to make money, to raise awareness (perhaps selling at cost), or both, anyone else could also sell IceWeasel branded merchandise to benefit themselves.

I'm not for or against keeping the current name (I really see both sides on that one- I'm torn between the coolness of giving new life to an iconic name and the project inventing it's own name for the sake of clarity and owning it's own name [Which has a lot of practical benefits, as mentioned above].).  I just thought it was worth putting everything out there, so everyone knows the options and some of their pluses and minuses.  Just generally in life, sometimes defacto choices are made when people don't realize they have a choice or don't really consider their options.  Then they sometimes regret it later.  So, understanding options so people can think about them isn't a bad thing IMO, even if it leads to the decision of "What we have is good.".  It's one less thing kind of hanging around out there, that once decided formally can allow people to plan with it in mind.

**Comment by TheEvilSkeleton** [comment]
Alright, it took a long time for me to read (I'm a slow and bad reader so my apologies).

If I understood it right: you think that it is a better idea to keep the nostalgic feel of the Iceweasel logo and keep the name "Iceweasel" the same?

**Comment by CharmCityCrab** [comment]
> If I understood it right: you think that it is a better idea to keep the nostalgic feel of the Iceweasel logo and keep the name "Iceweasel" the same?

I don't really express a strong opinion as to a course of action (Other than a planet with water and continents, and an animal with a paw or something, both be included, because they are popular design elements missing from the Firefox logo).  I think I am just saying that some intentionality should be applied to this process.

If I were to break it down into steps, I would say:

Step one: Decide if the browser will continue to be IceWeasel or not.

Step two: Decide on a new name, if a new name is the way to go, or skip to step three if it's decided to stick with IceWeasel

Step three: Figure out the logo.  

Part of figuring it out should probably be based on what fits with the browser's brand identity goals.  Like you said, it might be worth keeping a nostalgic name and logo if we're going after an audience that is used to browsers that offer more than most current ones do and that demands more from them, especially in terms of customize-ability.  Connecting visual and naming elements with what the project stands for and who the expected users are has a certain symmetry, yes.  

And there is a sort amount of cyclicalness to design anyway.  I would guess that this type of design becomes popular again sometime in the next decade as a backlash to current development trends (i.e. "What's old is new again").

There are certain security, marketability, profitability, and reputation related hits that using a name that can't be trademarked or restricted impose, though.  A business would never let a project like this stay "Iceweasel" for long because of that.  Of course, fortunately, this isn't a business. :)  But if it gets to the point where, I don't know, The Verge does a feature on the browser, you can bet they'll be a zillion "bootleg" Iceweasels out there that are malware instead of being based on this legitimate Iceweasel, plus some well-intentioned ones that aren't malware, but are very different browsers- all sort of implying that they are this Iceweasel, with any negative experiences people might have with them getting attributed to this browser unfairly.

In fact, based on those hypothetical "fake" Iceweasels (Which would actually have the same legal rights to use the name as this one does), some anti-malware software may flag anything called Iceweasel, including this perfectly legit browser.

So, _that_ is worth considering, too.

I think it's all just in the category of "Stuff to think about" rather than a solid proposal on my part.

I feel kind of a charge about making the famous Iceweasel a mobile browser, but it may not be prudent if folks want to leave the door open to this browser to get big.

My gut would say new name that can't be copied, old-fashioned type logo, animal with one or more paws wrapped around a planet with green continents and blue oceans. :)  If you put a gun to my head, that's the advice I'd give.  I really am not trying to push that too hard, though.  Like I said, Iceweasel is kind of cool (But probably impractical long-term).  I'm just saying there are a lot of things to think about- that's my point, really.  Whatever the answer is, there should be a reason why. :)

**Comment by interfect** [comment]
I dug up Iceweasle because I figured since the name was picked by the Debian folks specifically to get around a trademark problem with redistributing modified versions, it wouldn't cause me or anyone else a trademark problem distributing stuff called that.

I guess it could be re-named, but that wants to be another issue, independent of improving the icon.

@TheEvilSkeleton, that SVG is *an approach*. It seems to have turned the PNG image into an SVG of colored squares representing the pixels. Between that and potential licensing concerns (we just grabbed the image from the wiki, right? Does it have a license there?) it might make sense to dig around for old debs or source files to try and get a cleaner vector copy with a more obvious associated license.

**Comment by TheEvilSkeleton** [comment]
> Does it have a license there?

Good question, I don't know

**Comment by bbigam** [comment]
I guess now we need someone to make an Iceraven icon!
Any takers? (I'm not artsy myself.)

**Comment by interfect** [comment]
We have a new, modern icon now.
