### ISSUE TITLE
Make Top Sites (optionally) more like Fennec: 5 icons per row, 12-15 on screen

### ISSUE THREAD

**Issue by Leviafan83** [fork-maintainers/iceraven-browser#146]
make the top sites as in the old version

![Screenshot_20200921-152812](https://user-images.githubusercontent.com/71683096/93844824-2b097700-fca7-11ea-91d6-b4b4271cb11d.png)

**Comment by abhijitvalluri** [comment]
What exactly is the old behaviour that you want to replicate?

**Comment by Leviafan83** [comment]
all tabs on one screen.  or at least 12 - 15 tabs on one screen.

**Comment by revolutionaryking7** [comment]
> all tabs on one screen. or at least 12 - 15 tabs on one screen.

And 5 icons per row

**Comment by ale82to** [comment]
I d love that too and already opened a bug /request for it

**Comment by ale82to** [comment]
with smali editing i can get at max 16 top sites in one page to get 5 icons per row i must edit res /layout too.
I d love more than 16 topsites anyway.

**Comment by interfect** [comment]
How does this relate to #135 to make the icons bigger?

**Comment by CharmCityCrab** [comment]
I prefer four icons to a row because of the trend towards smartphones that are longer but narrower than their predecessors.

However, I do agree that an option to do something with all that blank space would be nice.  Adding extra rows of top sites (as suggested above) would be an improvement over the current behavior in that respect whether the icons are 4 to a row or 5 to a row.

Another approach would be that users could perhaps choose between several categories like "top sites", "bookmarks", "history", "recently closed tabs", "collections", and such, either having an option screen where the user picks one type of thing to fill out the whole screen (If enough of that type of content has been generated by the user's personal browser use) or where a user selects a set number of modules based on those categories, probably two, and each module would take up half the screen (one on top of the other) minus the space allotted for the browser name at the top and potentially the browser logo to the side of the name on the same line.

In practice, we might see one user's screen list "Iceraven" , followed by a first box with "top sites" and a second box with "most recent browser history" underneath the first box. Another user might choose "bookmarks" for the first box and "recently closed tabs" for the second box.  In this way, Iceraven could give the user control over the page (At least within the constraints of having to choose from a necessarily limited number of category options), apart from the name/logo at the top, which is good branding, and the page itself would be sure to fill up with options each user finds personally useful and not be wasted blank space.

Just doing it the original poster's way is at least an improvement over the status quo, though.

One big thing to avoid with whatever system we embrace is not just having a bunch of blank space as the only substitute if the user disables "collections", a somewhat controversial feature that we can probably expect a fair amount of opt-outs of.

**Comment by revolutionaryking7** [comment]
How about android style quick panel customization where user can define number of rows and number of columns...
Maybe we can use the same style for top sites.
