### ISSUE TITLE
More flexible choice of addons

### ISSUE THREAD

**Issue by Dakkaron** [fork-maintainers/iceraven-browser#16]
The current UI is very much not made for a larger amount of add-ons. There is no search, filter, sort or category function. So I think the current fix of just adding anything to the list isn't really scalable. Until upstream comes up with a better solution, I think it would be worthwhile to make the account name and collection ID that is used to get the list of supported add-ons configurable.

So e.g. add a menu option (or even only an about:config key) that allows the user to specify their own account name and collection ID, so they can add new addons to their list, without having to go through @interfect for every addon.

**Comment by interfect** [comment]
This might work? I'm not sure how to implement a new about:config key, or get it from the android-components side over to the place where this stuff is hard-coded in Mozilla's setup, but if we add some methods to swap out the account and collection to the add on provider thingy it might work.

It actually might be easier to make it a secret setting in the secret settings menu, because I've actually seen a bit of how that works.

**Comment by Dakkaron** [comment]
That sounds like a better option.

**Comment by abhijitvalluri** [comment]
https://github.com/interfect/fenix/pull/50 implements this feature!

**Comment by interfect** [comment]
The approach @Dakkaron suggested was implemented by @abhijitvalluri in the "Customize" settings, and is in the release I'm uploading now.
