### ISSUE TITLE
[Bug] Adding a custom search engine doesn't work

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#166]
### Expected behavior
I can specify a link in the settings to make my default search engine, it will say added, and then I can choose it from the search engines list.
### Actual behavior
The settings say that it has been added, but doesn't show up on the list of choosable engines. 
### Device information
arm64-v8a
* Android device: 10
* Fenix version: Since a few pull requests ago, on my own build off the app with no modifications. I referenced in the specific pull it started to occur in, and the same thing is replicated with even the most recent pull requests merged locally and built.

**Comment by ghost** [comment]
I warned you guys and you released a new build anyway...I can't tell what's more broken, adding a custom search engine, or my heart :'(

**Comment by abhijitvalluri** [comment]
Whooops! We need to investigate this.

**Comment by interfect** [comment]
Sorry to break your heart @johnhandcockandstuff. I hadn't read the issue yet, and didn't pick up that this was a regression since the last release.

This is another point in favor of #148. If pulling in the fixes mentioned in https://github.com/fork-maintainers/iceraven-browser/issues/170#issuecomment-700374750 doesn't introduce any new bugs that need new fixes from Mozilla's master, maybe we should take our next set of updates from one of Mozilla's stable release branches.

**Comment by johnhandcockandstuff** [comment]
> Sorry to break your heart @johnhandcockandstuff. I hadn't read the issue yet, and didn't pick up that this was a regression since the last release.
> 
> This is another point in favor of #148. If pulling in the fixes mentioned in [#170 (comment)](https://github.com/fork-maintainers/iceraven-browser/issues/170#issuecomment-700374750) doesn't introduce any new bugs that need new fixes from Mozilla's master, maybe we should take our next set of updates from one of Mozilla's stable release branches.

It okay I was just teasing btw wasn't trying to b a dickhead

**Comment by unixfox** [comment]
I can replicate the same bug since the version 1.1.

**Comment by interfect** [comment]
Given https://github.com/fork-maintainers/iceraven-browser/issues/203, it sounds like 1.2.1, which I think included the fix mentioned in https://github.com/fork-maintainers/iceraven-browser/issues/170#issuecomment-700374750, did not solve this. Maybe we want to walk back. Looks like we need to match exactly what was in Mozilla's Nightly after September 28th and before October 1st.

**Comment by interfect** [comment]
I don't see anything likely in `git log --stat 0d0a28d551d5083a6d9beeb2ec86746adf04eb10..b696fc4c4b06da58b2b8e50334d286d4ffedfb0e` which are the commits that I think should have added and removed the issue, according to https://github.com/mozilla-mobile/fenix/issues/15486

**Comment by interfect** [comment]
Here's the PR that @johnhandcockandstuff identified as bringing the bug over from Mozilla:

https://github.com/fork-maintainers/iceraven-browser/pull/149

**Comment by interfect** [comment]
The problem is almost certainly this:

https://github.com/fork-maintainers/iceraven-browser/pull/149/files#diff-7c793718d67c91fc4800800e4f4188f0

It's using a fallback list of search engines instead of the real one if the location service hasn't yet determined a location, because it wants the available list to change based on location. It's *also* using a dummy location provider instead of a real Mozilla Location Services location provider whenever no MLS API key is set. And [the dummy provider never claims to have determined the location](https://github.com/mozilla-mobile/android-components/blob/e2c0fd0376e71915c0669875d9872a3234a068bb/components/service/location/src/main/java/mozilla/components/service/location/LocationService.kt#L40-L43). So we always get the dummy list.

All the [real location service](https://github.com/mozilla-mobile/android-components/blob/e2c0fd0376e71915c0669875d9872a3234a068bb/components/service/location/src/main/java/mozilla/components/service/location/MozillaLocationService.kt) does is get a country code and country name. And that's only used [in addition to the actual device locale setting](https://github.com/mozilla-mobile/android-components/blob/f999065c045840d68d7bc36f29af953cce07bf74/components/service/location/src/main/java/mozilla/components/service/location/search/RegionSearchLocalizationProvider.kt#L27-L30), so when it fails in our builds we (used to) use less-accurately-localized search engines, instead of a static list that never accepts custom ones.

**Comment by Sonickyle27** [comment]
I still cannot add custom search engines in version 1.2.1. Upon pressing the tick button it waits for like 5 seconds, then says the engine was added, but it is nowhere to be seen.
If I attempt to add an engine with a name I've used previously, it says that the name is already being used.

**Comment by unixfox** [comment]
It works on 1.3.0 for me.
