### ISSUE TITLE
[Bug] Translate Web Page extension shows itself twice in menu and hides Switchy Omega

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#186]
When I install translate web pages,it will show 2 translate web pages in extensions tab,and I can't find switchy omega from tab now.🤔

**Comment by interfect** [comment]
I think this might be a bug in the translate extension (or possibly the implementation of the menu system, since it shouldn't be able to hide other add-ons). I remember someone else complaining that there were two menu entries for that particular extension.

I'd suggest reporting the bug to the extension developers, and having them take a look at it with the extension development tools for Mozilla Firefox Nightly. Maybe they can find the bug in the extension, or confirm exactly what the extension is doing to trigger a bug in code we (hopefully) share with Mozilla.
