### ISSUE TITLE
Final voting for new logo

### ISSUE THREAD

**Issue by abhijitvalluri** [fork-maintainers/iceraven-browser#199]
After much discussion and iteration, as well as some very late entries, we have a final(ish) vote for the new logo for our browser!
Come one! Come all! Cast your votes! Here are the entries:

### EDIT: Please vote based on what you feel best represents an "iceraven"

![logos_comparison_dark](https://user-images.githubusercontent.com/17151327/94969705-1d4fbf00-04fb-11eb-8078-4982b4b860b5.png)
![logos_comparison_light](https://user-images.githubusercontent.com/17151327/94969713-1fb21900-04fb-11eb-89c8-57bb54c44e00.png)

The emojis below each logo are the ones you need to choose to vote for it. Note that the emojis you see on your system may differ in appearance compared to the ones in the picture above (the one above is from a Mac device). Just choose the corresponding emoji on your system.

### Previous (aborted) poll results
For fairness sake, I will give the results of the previous, aborted poll:

The 1st and 2nd logo above received 9 votes each, and are tied as the current favorites. 
The 3rd logo (looking aqua blue) did not receive any votes **but** it was a new comer. 
The 4th and 5th logo got a combined 7 votes (there were both presented as a single choice). 
Refer to this https://github.com/fork-maintainers/iceraven-browser/issues/134#issuecomment-698722536 for these votes.

And finally, the last (6th) logo above got two votes in a brand new thread. Refer to this https://github.com/fork-maintainers/iceraven-browser/issues/197#issue-713645948.

---------------
Start voting now! Also, **no new submissions will be accepted in this thread.** Please make a new issue if you want to submit a new entry.

## VOTING IS CLOSED!

**Comment by abhijitvalluri** [comment]
# Voting is closed!

Final tally:
<img width="507" alt="Screen Shot 2020-10-10 at 1 10 33 AM" src="https://user-images.githubusercontent.com/17151327/95640622-86a07680-0a95-11eb-8e61-5572d8e27cb6.png">

**Comment by TheEvilSkeleton** [comment]
Who did them? They all look amazing!

**Comment by TheEvilSkeleton** [comment]
As far as I know, [Simple Mobile Tools](https://www.simplemobiletools.com/) changes icons based on the theme you chose. Maybe you guys can implement this so if one prefers an icon over another, they can just choose it in the settings, which would change the icon of the app.

**Comment by wh0isit** [comment]
👀

**Comment by hbarsaiyan** [comment]
pain lol
Congratulations @WeAreJMJ

**Comment by abhijitvalluri** [comment]
The voting seems suspiciously high for the last one. Did someone request outside help to get @WeAreJMJ's logo more votes? Please be truthful and let us know if you have requested any help to gain traction for the logo. 

I feel frustrated that someone came out of the blue and created a logo (that does not even look like a bird) and is winning. If foul play is involved, that logo will be disqualified. 

If not, then I apologize for making such an accusation.

**Comment by wh0isit** [comment]
I think it's because the poll announcement is at the top of the release page. I wouldn't have known about it other wise.

**Comment by TheEvilSkeleton** [comment]
> The voting seems suspiciously high for the last one. Did someone request outside help to get @WeAreJMJ's logo more votes? Please be truthful and let us know if you have requested any help to gain traction for the logo.

I didn't request outside help, but I did share the poll with my friends and told them that all logos looked amazing. I can send you a Discord/Matrix link of where and when I posted it if you want, since they're bridged.

I only know one that voted for @WeAreJMJ's logo, but it wasn't a request; he did it himself.

**Comment by ghost** [comment]
> I feel frustrated that someone came out of the blue and created a logo (that does not even look like a bird)

@abhijitvalluri I am trying to be courteous :) I didn't see this poll until now. I had only been viewing the prior issues by hbarsaiyan and myself. 

I didn't share my issue elsewhere except Namit Nayan(?) who was the last person to reply before the project was closed to contributions(thanks Hacktoberfest).

If there was any gaming involved in this poll, I wasn't involved in it for sure.

Btw, I took your suggestion and was trying to change the look a little bit (failure of course, else would have shared it).


![Screenshot_20201003-203531](https://user-images.githubusercontent.com/26594953/94995120-af1e0180-05b9-11eb-84d5-d6605f5cc707.png)

**Comment by ghost** [comment]
> I think it's because the poll announcement is at the top of the release page. I wouldn't have known about it other wise.

@wh0isit I missed the prior poll because the release page directed to two threads that were involved with inspirations for the logo

**Comment by Namit-Nayan** [comment]
> I didn't share my issue elsewhere except Namit Nayan(?) who was the last person to reply before the project was closed to contributions(thanks Hacktoberfest).

For me second last logo looks better in dark mode(tho colors show up nice), Yours is bit better in light mode(the edges/markings show nicely)(hard to choose).
I voted second last one(rocket emoji))
Btw third one has a nice tail.

And Just for clarification, I didn't share or talk about the poll or your images anywhere.

**Comment by hbarsaiyan** [comment]
> For me second last logo looks better in dark mode(tho colors show up nice), Yours is bit better in light mode(the edges/markings show nicely)(hard to choose).
> I voted second last one(rocket emoji))
> Btw third one has a nice tail.
> 
> And Just for clarification, I didn't share or talk about the poll or your images anywhere.

I would have chose darker colors to highlight the edges more but since it's an 'iceraven' I had to dilute the colours otherwise too much contrast. btw you are a NoGoolag admin right? 😀

**Comment by Namit-Nayan** [comment]
> btw you are a NoGoolag admin right? 😀

Yes. And for icon design , you guys have better understanding than me, in the end we will get what's popular.

**Comment by hbarsaiyan** [comment]
I don't know if it seems to you guys that i don't trust the voting. I just wanted to contibute to this project, which i think is a unique project (new features and forward porting stuff from fennec). So i just wanted to contribute to the project in some way since my knowledge of Java/Kotlin is very less. Whatever the result may be i will just accept the mandate. So no hard feelings. 
And @Namit-Nayan i was just checking if you were the same guy, if you thought i was asking you because of the sharing thing.

**Comment by Namit-Nayan** [comment]
> I don't know if it seems to you guys that i don't trust the voting.

Not to me.
> And @Namit-Nayan i was just checking if you were the same guy, if you thought i was asking you because of the sharing thing.

I didn't.

(I think enough off topic discussion, we should stop and wait for the poll to end)

**Comment by abhijitvalluri** [comment]
Sorry everyone. I didn't mean to accuse anyone of unfair behavior. My senses were on high alert since the hacktober fest spam! Hence when I saw a quick submission of a new logo + it getting so many votes, it made me suspicious.

Having said that I'm still not a fan of the new logo. It simply doesn't look like a bird. Plus @hbarsaiyan has put so much effort to design the logo I feel he should be rewarded for his efforts. So I was rooting for him. Plus if you combine all the votes for @hbarsaiyan's designs he is very close to the last one.

**Comment by interfect** [comment]
I think my favorite is :laughing:, but I'd be happy with any of these; they all beat my programmer art. The trouble with polls is that sometimes the community doesn't agree with you, and it can be disappointing to open a poll if you wouldn't be happy with a landslide victory for any of the options. I think the new last one is actually quite good, and I can sort of see a bird. It does seem to have some additional wings though.

This thread overall is getting much more participation already than the one comment did in the other thread.

Having a poll can let us see what style of icon the community prefers. We don't have to take any particular one exactly as-is; we can tweak any of them either before or after adopting it, or replace whatever we get 2 months later with an improved version of the same general idea. If loads of people vote for the last one, but also it isn't birdy enough, we can ask @WeAreJMJ if they would to make it birdier.

Also: PSA: Github lets you react with multiple emojis to the same post. So I think people ought to vote for all the options they want, instead of just their very favorite.

**Comment by hockeymikey** [comment]
> As far as I know, [Simple Mobile Tools](https://www.simplemobiletools.com/) changes icons based on the theme you chose. Maybe you guys can implement this so if one prefers an icon over another, they can just choose it in the settings, which would change the icon of the app.

I think we should do this regardless. Whatever wins can be the default but include them all. Give people that choice to chose whatever one they want. Everyone is happy then. I can see maybe a downside with losing unified branding but people will probably rice their homescreen anyways so probably a moot issue.

**Comment by locuturus** [comment]
For what it's worth I choose the last one because while it isn't the most obviously bird-like (especially on the dark background) it does have the dual raven-black & ice-blue colors I think the name calls for.  It also has the thickest, sleekest beak and the hints of a crest that ravens actually have.  The other logos look more like pigeons or crows IMO.

I would add a highlight line along the top edge of the beak to help it stand out on a dark background.  I'd probably use the center ice color but lighten it a bit.  Make it look like the beak is just a little bit shiny.

**Comment by nadeem49** [comment]
🚀

**Comment by hbarsaiyan** [comment]
> > As far as I know, [Simple Mobile Tools](https://www.simplemobiletools.com/) changes icons based on the theme you chose. Maybe you guys can implement this so if one prefers an icon over another, they can just choose it in the settings, which would change the icon of the app.
> 
> I think we should do this regardless. Whatever wins can be the default but include them all. Give people that choice to chose whatever one they want. Everyone is happy then. I can see maybe a downside with losing unified branding but people will probably rice their homescreen anyways so probably a moot issue.

I don't agree with this. This will be bad for the project and only lead to confusion imo. We should stick to one logo. People are free to change icons themselves afterwards. Anyways implementing an icon manager isn't worth the while when there are more important issues that need to be resolved.

**Comment by bajjou13214** [comment]
> For what it's worth I choose the last one because while it isn't the most obviously bird-like (especially on the dark background) it does have the dual raven-black & ice-blue colors I think the name calls for. It also has the thickest, sleekest beak and the hints of a crest that ravens actually have. The other logos look more like pigeons or crows IMO.
> 
> I would add a highlight line along the top edge of the beak to help it stand out on a dark background. I'd probably use the center ice color but lighten it a bit. Make it look like the beak is just a little bit shiny.

That's definitely not ice-blue more like ocean-blue. And about the second thing i guess you are getting too real with the icon. Firefox's own icon has looked less like a fox with the changes over the years and Kiwi Browser has a white kiwi as it's logo but kiwis aren't white. You talk about how the beak looks like a raven but on the other issue i saw someone asking him to make changes to the beak and neck, so of course you can't keep everyone happy with the design.
I don't know if people have forgotten that the name of the browser is **Iceraven so the raven should have an 'ice' tone to it** and the first two icons do full justice to that and mimic Firefox's own icon style perfectly. Just my two cents.

**Comment by bajjou13214** [comment]
While not trying to spam or anything, i will just say that it appears that people are voting more on which logo looks more like a 'raven' rather than which icon looks more like an 'iceraven' as a whole.
It's like choosing an icon for firefox based on which logo looks more like a 'fox' rather than which looks more like a 'firefox'.

**Comment by abhijitvalluri** [comment]
> That's definitely not ice-blue more like ocean-blue. And about the second thing i guess you are getting too real with the icon. Firefox's own icon has looked less like a fox with the changes over the years and Kiwi Browser has a white kiwi as it's logo but kiwis aren't white. You talk about how the beak looks like a raven but on the other issue i saw someone asking him to make changes to the beak and neck, so of course you can't keep everyone happy with the design.
> I don't know if people have forgotten that the name of the browser is **Iceraven so the raven should have an 'ice' tone to it** and the first two icons do full justice to that and mimic Firefox's own icon style perfectly. Just my two cents.

I agree with you @bajjou13214. Asking for a poll is very tricky. Which is why Google did not ask its employees or general public for voting on its new logo, nor Mozilla asks people to vote on a logo. It is tricky to make people decide the right look and feel and tone for the brand you are creating. I strongly prefer a logo that closely justifies the "Ice raven" aspect of the brand which the first two do well...

And as of now, the logos designed by @hbarsaiyan collectively gained more votes than the one by @WeAreJMJ. What are we supposed to do about that? This is very tricky. 

I am inclined to merge the votes for 1 and 2 as they are very similar in design and for 4 and 5 as they are similar in design too.

**Comment by Weropol** [comment]
For what it's worth, the sixth logo (:eyes:) really stood out to me in a good way.  I like the more muted "Icy" colors and detailed, flowing design.

I found the other icons too bright and too soft/rounded.  They remind me of a children's game, instead of a productivity tool.

:eyes: all the way!  Perhaps the beak could be highlighted a little more, but still a great job.

**Comment by abhijitvalluri** [comment]
@interfect I will leave the ultimate decision of picking a logo to you after this poll concludes. I will leave it up to you how you will balance popular choice vs what might seem like a sensible choice that best reflects the name, iceraven, and balances fairness to give credit to all the folks who contributed a design.

**Comment by bajjou13214** [comment]
![download](https://user-images.githubusercontent.com/37732050/95020016-481a4e80-0686-11eb-8cc1-1e65ae8fee22.jpeg)

We all know what this represents. Three rounds of logo contest were done to choose a logo for linux. It did not win any. Still it's the face of linux as we know it today because Linus himself chose it.

LineageOS did not contest a poll to decide their logo. The main collaborators chose the logo internally. 

And i haven't heard anyone complain about the logo for any of the two projects. So i guess it's better that the people who work on the project select the icon themselves based on what they feel represents the project the best rather than having people vote for it. Or i guess provide people only with choices so that whatever the result may be it's acceptable to you.

As for the sixth logo i don't think it's bad at all. But definitely not an iceraven. As for people saying it has icy color (even though not icy enough imo) i think it should be on the raven. It's like having a firefox icon where we will have fire color on the sphere rather than the fox.

**Comment by CharmCityCrab** [comment]
One key advantage to the colorful design represented by the "rocket ship" and "heart" emoticons in the poll (My personal preference is the one represented by the rocket ship) are that they include essentially all the colors that are found within the browser when it's opened (And maybe a few more).

For example, when a website is loading, there is this multi-color progress bar that comes across the screen.  Unless the developers want to and are able to change that (And I suspect it would be a pain to change), just doing a black and blue logo is going to make that, and things like that throughout the browser, seem kind of jarring and disconnected from the logo people touch to access the browser.

A colorful logo thus presents a more cohesive connection between the icon and the interior of the app.

The other thing is that the name of the browser could sound kind of ominous to some.  Do we want a logo that doubles down on the ominous factor, perhaps in the name of a closer relationship with the reality of the two words included in the browser name, or do we want to balance it with a colorful logo that takes the edge off but doesn't necessarily literally adhere to the name of the browser?  I'd prefer the latter, personally, although I know there are a variety of views on this.

I also just feel that one represented by the rocketship emoticon on the poll is a cool piece of art.  It's subjective and I know we'll all have our own opinions, I just wanted to put in my two cents, since it appears a lot of other people are as well. :)

I did like the suggestion of a "pick your own icon" type screen in options, although I realize it may not be feasible to create and maintain that in addition to all the other things our devs have to do.  But if they have the time and and want to do it, it'd be pretty cool.  The DuckDuckGo browser has a feature somewhat like that, though all their options are just different color variants on their regular logo instead of a bunch of different logos.

**Comment by locuturus** [comment]
I won't be upset if the poll is ignored in favor of interfect's preference but I am a little surprised by how much 'What's your opinion everyone?  Oh, no!  Not that!  That's a wrong opinion!' is going on here.  ✌️

**Comment by abhijitvalluri** [comment]
I'm guilty of the above. Sorry for moaning about the results. Just didn't expect it AT ALL. I would love to try and incorporate all logos in the app somehow. It's definitely not possible to pick a launcher icon programmatically. It can be only one. But there are ways to allow users to create shortcuts for the home screen with different icons to make it look like the launcher icon. But it's just a shortcut to the app with a different icon.

**Comment by abhijitvalluri** [comment]
And I'm coming around to 👀. Now that I see it on my phone it does look cool. Still doesn't look like a bird though. For some reason it always looks like a four legged mammal to me... Probably a bear. Definitely blue. 😂

**Comment by locuturus** [comment]
I'm happy there is so much interest 🙂

**Comment by TheEvilSkeleton** [comment]
> Sorry for moaning about the results. Just didn't expect it AT ALL. I would love to try and incorporate all logos in the app somehow. It's definitely not possible to pick a launcher icon programmatically. It can be only one. But there are ways to allow users to create shortcuts for the home screen with different icons to make it look like the launcher icon. But it's just a shortcut to the app with a different icon.

I posted a comment before: https://github.com/fork-maintainers/iceraven-browser/issues/199#issuecomment-703028377. Their apps are FOSS, so looking at their source codes might hint you on how to implement this.

Another suggestion is to create a small icon pack specifically for Iceraven. If one wants to use another icon, they can just download the icon pack and choose the one they want.

**Comment by mackeev** [comment]
My intention was to ignore voting altogether. I followed the discussion, more or less, but didn't like anything. I tapped on #199 just to "prepare myself" for whatever pigeon. "Pretty eyes" was a nice surprise. It's definitely not a pigeon, and it looks pretty cool against the black background.

**Comment by ghost** [comment]
@bajjou13214 Please take my following comment in a friendly manner:

1. The leeway to have a white kiwi example should apply to all logos. Not just mine :) If it's not icy enough, not every ice is clear is glass or pure as white.

2. Firefox doesn't have a fire in the fox. All foxes are of that colour range. Plus you can't excuse Firefox Nightly and Klar(Focus) colour selections with that reasoning. My interpretation of the 'Firefox' is 'the tails of fire left by the spirit of a fox'.

3. Also regarding the same, wasn't Firefox logo having a fox? Did they go with any other carnivore (Wolf?) while having the name of fox in their 'Branding'?

Btw, it doesn't matter what icon get's selected as the browser is Nice even without one ;) But lopsided demoralisation is really bad for a community contribution.

**Comment by ajshovon** [comment]
The middle one looks different & i like it a lot. It would be best if you can give user to change logo from the browser settings.

**Comment by Neikon** [comment]
I like the last one, but it should be more circularly perfect.
i like the middle one too, but it looks like a pigeon not a raven

**Comment by resynth1943** [comment]
3rd one looks alright, but it could do with sharper borders to differentiate the various components.

4th and 5th lack contrast. They may be harder to see for impaired viewers. Thee 5th one should definitely have a more circular form, as suggested above.

Last one is a bit too dark for my liking. I think there should be a lighter element that contrasts against the dark bird.

I am quite a fan of the 1st and 2nd logos, but judging by the current results, they may not win.

Just an idea: why not put all of them into the app, and let us choose? We'd still have to pick a default, but this seems like a pretty good way to please everyone.

**Comment by m1chj** [comment]
The last one is the best

**Comment by vitaminj** [comment]
I'd be happy with most of these, thanks to all the designers for the efforts they've put in and the devs for both acknowledging the need and also for putting it out as a vote.
But with all the designs I can nitpick technical complaints, either with smoothing issues on some curves, or weighting issues (esp at smaller sizes) or IMO the last one doesn't have icy colours. I'd love for the winner of this round to then have a few tweaked variants to select between (either another public vote or just between the main devs) before it goes final.

**Comment by hbarsaiyan** [comment]
> I'd be happy with most of these, thanks to all the designers for the efforts they've put in and the devs for both acknowledging the need and also for putting it out as a vote.
> But with all the designs I can nitpick technical complaints, either with smoothing issues on some curves, or weighting issues (esp at smaller sizes) or IMO the last one doesn't have icy colours. I'd love for the winner of this round to then have a few tweaked variants to select between (either another public vote or just between the main devs) before it goes final.

Tweaks like? Though the poll is more or less over i am open to suggestions for future.

**Comment by vitaminj** [comment]
> Tweaks like? Though the poll is more or less over i am open to suggestions for future.

I don't want second-guess the original designers or push them in particular directions, I was just wondering if a final round of really narrowing it down would absolutely nail it.

Assuming that the last design has been selected, I would love to be able to compare it with a variant with an icier-coloured planet, and/or a variant with a bit of white-tips/edging on the raven, both of which might help visibility on dark backgrounds. Maybe a bit more contrast where the beak starts? A variation on the wings? Just some subtle amends to pick from, maybe whoever makes the final call don't end up going with them, but just something to cover the concerns of the commenters above?

**Comment by abhijitvalluri** [comment]
If I have the energy and time tomorrow, I will **_try_** to see if I can somehow allow people to "choose" different icons. I will look at how some other apps do it that were mentioned above. Most likely it is going to be so that you can create a "shortcut" for the app with a different icon, but the app itself has a fixed icon. This can cause some confusion. Let me investigate.

**Comment by resynth1943** [comment]
> I will try to see if I can somehow allow people to "choose" different icons

["Is there any way to dynamically change an app icon like Calendar app does?" -- Stack Overflow](https://stackoverflow.com/questions/34592230/is-there-any-way-to-dynamically-change-an-app-icon-like-calendar-app-does)

Hope it helps 👍🏼

**Comment by m1chj** [comment]
There was a poll and people have chosen, why would dev(s) need to waste time to offer possibly tricky and unncessary icon choice? I don't get it, especially since you can always just change it on your own to whatever you like really.

**Comment by CharmCityCrab** [comment]
> There was a poll and people have chosen, why would dev(s) need to waste time to offer possibly tricky and unncessary icon choice? I don't get it, especially since you can always just change it on your own to whatever you like really.

Even though I think Iceraven probably attracts a larger percentage of technically sophisticated users than most Android browsers, I still think it would probably be fair to say that most users do not know how to personally change icons of Android apps, or even that it is possible.  

Among those who do, some may not want to switch launchers for their entire phone, which may be set up well and be working well for them overall and have custom features they use, to pull it off (Most manufacturer default launchers do not have an option to change app icons), or install yet another app to change the app icon of an existing app.

The majority of people who use the browser (At least eventually when it gets listed in F-Droid and Google Play) are also likely to never look at its issues pages on GitHub either, so if the option doesn't go in the Iceraven GUI, they won't see it.

It's fair for people to inquire about whether a browser that devotes itself in part to having as many user facing options as possible whether it would be possible to have an option they would like and use within the browser that is present to a limited extent in at least one other browser app, and in several non-browser apps, especially since, though I am in no way trying to undermine the winner, the winner in the poll did get less than 50% of the overall vote, which means the majority of people voted for something different, they just also voted for different things from each other.

If the answer is that this would too complicated to implement and maintain and that there are too many other things to worry about given the limited number of available developer hours, I understand.  I can live with almost any icon.  However, I appreciate that one of our maintainers is looking into the possibility of providing a user option to see what it would entail and if it is doable.  It's a reasonable question and that's a reasonable response. 

If it turns out to relatively simple to accomplish, why not? It'd make the over 50% of people who favored options other than what looks to be the winning one happy, and be an extra option and way to customize for everyone (I also think "It's so customizable that you can even change the logo." is a nice way of selling people on what the browser stands for when people promote it elsewhere.).  Fortunately, we have a whole bunch of already ready icons ready to be used for that- not only the ones in this poll, but maybe also some of the profile icons included in the previous issue on this subject and made it into neither poll.  Heck, we could even make the current pre-poll icon a "classic" option. :)

Obviously, the icon that won or wins the poll should be the default for the sake of fairness, but allowing users who want to use an alternate icon to do by setting an option is very consistent with the ethos of the browser.

If it's too complicated coding wise or can't be done, then that's fine, too.  However, it'd be a cool option to have if it's not too much trouble to create and maintain.

**Comment by hbarsaiyan** [comment]
Personally i think it's better if we go with a single icon because if the icon is used inside the app like in firefox then i don't think multiple icons will be a good idea and will be difficult to implement. Anyways the sixth icon has won the poll by a good margin so it's not even a close call.

**Comment by abhijitvalluri** [comment]
Yes last logo got most votes, but then again all the other logos combined got more votes together than the last. So if we put this voting in context of creators of the logos, @hbarsaiyan got more votes than @WeAreJMJ. That's why it may make sense to add more than one logo into the app, not necessarily all. Just to allow people to choose what they want and also give all the creators credit and recognition for their efforts. If you look at it, we spent most energy iterating over @hbarsaiyan's designs but the last one was added on the same day I created this poll I think and hardly got time to discuss and iterate over it.

**Comment by CharmCityCrab** [comment]
> Personally i think it's better if we go with a single icon because if the icon is used inside the app like in firefox then i don't think multiple icons will be a good idea and will be difficult to implement. 

There is no use of the icon within the current release build of Iceraven apart from what you touch to open the app from your Android desktop or app drawer.  I don't have Firefox for Android installed right now, but last I did have it installed, the only logos were on the "home screen" with top sites, etc..  Right now, Iceraven doesn't do that.  Even the "about Iceraven" option (I don't know if option is really the right term, because it just tells you what version you're on and such, it doesn't actually contain an option :) ) in settings doesn't contain a logo.

It is a valid point that Iceraven would, if it implemented a "choose your own icon" option, probably have to stick to not using the icon within the app itself (Not using it is the status quo) to provide a consistent user experience OR have the "choose your own icon" option control both the actual icon to touch to open the app, and any icons within the app, which makes it more complicated.  My instinct would be to do the former- if we can implement a "choose your own icon" type thing, just don't use the icons inside the app, so the user experience for each individual user is consistent with his or her expressed preferences (and no extra upkeep is required beyond implementing the option to have the icon on the desktop and in the app drawer.) _unless_, of course, it's easy to implement variable icons in other spots, which, like you, I doubt, but I don't really _know_, because I am not a coder.

As mentioned upthread, if we were really going for a consistent user experience, though, we would have used an icon that contained the major colors within the app like the page loading indicator, which the 2nd and 3rd place finishers (To date, I'm not sure the poll is really over until a maintainer says it is) both did or came close to doing.  So, I suppose it has to be acknowledged that using one icon (of the user's choice) to open and the default icon (regardless of the user's choice) within the app itself is a possibility, I think I'd lean towards, if we include a user option, either making sure the icon isn't used within the app so that nothing conflicts with the option the individual user sets, or making the user's option inclusive of any icon use within the app. though. 

I do actually think having one icon to open and another icon within the app (Unless they are very similar) is worse than not providing a choice at all, but to me that trails both "icon on the outside that the user chooses and no icon in the app" and "icon of the user's choice throughout the app" in terms of desirability.

**Comment by bitsper2nd** [comment]
> That's why it may make sense to add more than one logo into the app

No, an app lives and grows by both merit and indentity. You will never please everyone. Instead of changing the icon within the app, make another round of votes. Pick the top most voted icons in this round which are the third, fith and sixth. The alternative is to honor this poll and pick the last icon which gathered most votes. Personally I prefer the 5th one since it represents an ice raven in the form of a bird with aurora colors around the globe. Very similar to current firefox logo. Should help make it more familiar to users when it comes to brand. That is the point of logo.

**Comment by abhijitvalluri** [comment]
Thanks everyone for your comments and ideas. I think we captured all the points that we can possibly have on this matter. Please only comment if you have anything different to add. Don't vote anymore, it won't matter as I noted the final results. 

Let's think and make a final decision on this. 

@interfect the results are ready. Plenty of suggestions above of what to do moving forward (single icon, let people choose, etc.). I will give you the final say on this matter.

**Comment by interfect** [comment]
Many thanks to @hbarsaiyan and @WeAreJMJ for the logo submissions! They are all excellent icons. Thanks especially to @hbarsaiyan for making so many icons and going back and forth for so many rounds.

Given the results of the poll, I believe we should use the 6th icon, by @WeAreJMJ, as the browser icon. It got the most votes by far, and I think it evokes the Firefox heritage of the project in a way that the others don't.

![image](https://user-images.githubusercontent.com/752054/95644991-9c9b4080-0a6f-11eb-9a9f-939611fff553.png)

Now, I too would like to see it become more raven-y, with a bit more of a wing, and maybe try some slightly different color schemes. I think that we should adopt it as-is now, and say that we are happy to consider PRs from anyone with proposed improvements to the logo, keeping with the same general theme.

Thanks again to our logo designers, all the voters, and @abhijitvalluri for running the whole poll!

**Comment by hbarsaiyan** [comment]
Though i dont want to hijack on someone else's work, i can try tweaking the logo a little if its fine with @WeAreJMJ.

**Comment by ghost** [comment]
@hbarsaiyan It's not hijacking :) Consider it to be in CC0. You and the Devs can edit it as per your needs. The SVGs are linked in the prior issue of mine. Take a look at the Status bar SVG too if you can. IMO it needs to be closer to the newer version you are gonna make, but simple and hollow enough to be visible in teeny tiny status bar.

Edit:
[SVGs in Gdrive](https://drive.google.com/drive/folders/1jzpCTgDSmmyq4FEDUIGT3Ds47aPP9Ttz?usp=sharing)

**Comment by abhijitvalluri** [comment]
Awesome, I am happy to see further collaboration above on enhancing the logo to its final form. We shall not have such a public voting process on it but will potentially have very focussed rounds of improvements and polish it up. I will lock this discussion here and request that any discussion on further enhancements be done in a new issue or an existing issue for the logo created by @WeAreJMJ.
