### ISSUE TITLE
Stuck search suggestion window [Bug]

### ISSUE THREAD

**Issue by Genxster1998** [fork-maintainers/iceraven-browser#212]
## Steps to reproduce
put keywords in search box while its placed in bottom.let it fill automatically best url ,click on url box to approve ,press enter .

### Expected behavior
the suggestions window appearing above should be closed on pressing enter.
### Actual behavior
the suggestion window stuck frozen(no response on  clicking ), even page is opened in background ,to resolve this ,one should go back to recents and reenter app to update/repaint window (expected behavior).
### Device information
Redmi Note 7 pro

* Android device: 10.0
* Fenix version: 1.2.1
![2020-10-09 12 57 43](https://user-images.githubusercontent.com/23246830/95556209-95087700-0a30-11eb-86ea-cb361dd75ecd.jpg)

Ps: I tried again (fullscreen gestures without nav pill ) but it does work fine & occasionally get stuck.

**Comment by interfect** [comment]
I just tried and couldn't reproduce this:

1. Be in search box
2. Type 3 characters of a web address
3. Tap in right side of search box to accept suggested URL
4. Press enter.

I'm trying on 1.2.1. Am I missing something?

**Comment by ghost** [comment]
The issue is not with the browser (maybe). The thing is - You are using a custom ROM and you have disabled the bottom gestures pill entirely (or I can say you have hidden the pill with the option which is provided in custom ROMs for full seamless gesture experience). 

If you keep the gesture pill visible, you won't face this issue. I have seen this behaviour with samsung browser as well. So I am not sure if it is a browser issue or something related to the way these custom ROM hide the pill.

Edit: I am not using this browser but the same thing happens with the official Firefox builds. I just saw this issue here so just wanted to point out about this behaviour.

**Comment by Genxster1998** [comment]
@shivvvvvv @interfect Thanks for info ,yeah I disabled pill , using fullscreen gestures , and it does work 1 out of 2 times even when there is no pill but now on enabling pill , problem resolved .So this is something related to android framework more or less or way to disable pill   , but can be resolved on app side(low priority).
