### ISSUE TITLE
addon-request - "Enhance Belfast Telegraph"

### ISSUE THREAD

**Issue by trumad** [fork-maintainers/iceraven-browser#222]
Hi,

Could this extension please be added to the [collection](https://addons.mozilla.org/en-US/firefox/collections/16201230/What-I-want-on-Fenix/)?

https://addons.mozilla.org/en-GB/android/addon/enhance-belfast-telegraph/

**Comment by hbarsaiyan** [comment]
@trumad you can add it yourself. Read [here](https://github.com/fork-maintainers/iceraven-browser/pull/50#issuecomment-685187265).

**Comment by ghost** [comment]
> @trumad you can add it yourself. Read [here](https://github.com/fork-maintainers/iceraven-browser/pull/50#issuecomment-685187265).

Sir I do know that I can make my own custom list and any extension to it but I want this extension [Floccus](https://addons.mozilla.org/en-US/firefox/addon/floccus/) 
  to be available on all Iceraven browser  users (those whom I recommended ) .Since it works and it is too lengthy process  to make all friends create a firefox account for one extension

**Comment by interfect** [comment]
I've added both of these. Maintaining one's own addons.mozilla.org account and collection is indeed a bit of work; we really should write the code to let people pull any add-on from AMO from the browser or XPI.

**Comment by trumad** [comment]
Thank you @interfect! Yeah, it would be fantastic if it behaved like Fennec and allowed any arbitrary AMO addon. Sorry for the hassle - the main readme.md said to create an issue to get addons added; I didn't know I could make my own collection & point at that.
