### ISSUE TITLE
[Bug] Double Tap on Instagram

### ISSUE THREAD

**Issue by Raul1198** [fork-maintainers/iceraven-browser#241]
## Steps to reproduce
1. Open Instagram
2. Double Tap any post on the timeline to give a like/heart

### Expected behavior
The post got like

### Actual behavior
Double tapping is opening text selection

### Device information

* Android device: 10
* Fenix version: 1.3.0

**Comment by ghost** [comment]
Facing this issue in youtube.com

**Comment by interfect** [comment]
This sounds like a Geckoview issue and probably not Iceraven's fault. How well does this work in Mozilla Firefox?

**Comment by Raul1198** [comment]
I think this is geckoview's issue as same happened on FF too

**Comment by yoasif** [comment]
This browser doesn't attempt to forward issues upstream?

**Comment by interfect** [comment]
We point people upstream to file there, but I don't have the time to actually forward the issue on behalf of the original reporter, and carry the updates back and forth. And I don't think each bug that affects both Firefox and Iceraven wants to have an open issue in both Firefox and Iceraven, because there will be too many for the smaller team over here to manage.

If it's something we think we can fix ourselves, it makes sense to leave it open here. If it's a problem in GeckoView that will get fixed if and when GeckoView changes, I don't want to leave it open here.
