### ISSUE TITLE
enable swipe tab feature also on addon page

### ISSUE THREAD

**Issue by mycal123** [fork-maintainers/iceraven-browser#258]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)

i didnt find any particular issue related to this

[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)

swipe tab feature also on addon page like other chromium based Browser have it

[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)

url tool bar should also exist in addon page like in chrome extension supported Browser do . so we can try guesture on addon page

[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?

bitwarden quite slow in iceravan browser ,many timees session expire for fill out password box. it help user go back with swipe to try again.it may lead to open sevral page of same addon if it does not close its other tab automatically.

### How do you know that this problem exists today? Why is this important?

it makes it more like chromium

### Who will benefit from it?

every single user

**Comment by interfect** [comment]
So you want the little modal screens that add-ons open to conceptually be tabs, so they can be switched between (via the gesture on the URL bar or other tab-switching methods). Then you would be able to swap between the add-on's tab and the tab of the underlying page at will, instead of losing your state in the add-on when you go back to the page.

This might be a serious refactor. But honestly I want something like this for desktop Firefox too; the little menus that drop down from the add-ons are so easy to click out of on accident.

Right now, the open add-on is associated with a tab; uBlock Origin, for example, lets you control whether it is on or off for the current tab. What should happen if an add-on is opened as a tab, and the user switches to a tab for a different page, and back to the add-on? Or switches to a tab for a different page and opens the add-on for that page? Can the same add-on now be open for multiple pages? Can you have an add-on open for a tab and then close the page tab while leaving the add-on open for it?

**Comment by mycal123** [comment]
i don't want to derive the whole thing but i want to say just try kiwi Browser 5 minutes .its open source.i think their concept same as fenix with few modifications to addon page. and devloper made that by forking chromium so that browser have all chrome guesture with few modifications.

you can figure out yourself all the guesture with tweaks and how that manage extension page.it can help me easyly switching between Browsers.

just practice 5minutes all guesture in kiwi. and about extension page if we can limit how extension page should behave. if that can be optional it will be more better 
sometimes i want keep them open, sometime wants them auto close within certain interval and sometime i want to close previous extension page when i open new extension page.
its pending feature request in kiwi repo.
