### ISSUE TITLE
Add-on installation support

### ISSUE THREAD

**Issue by rsssxd** [fork-maintainers/iceraven-browser#27]
I want to do this, but I couldn't. Can someone describe it with pictures or taking a video?

https://www.reddit.com/r/firefox/comments/i8igam/androidrequires_root_install_any_addon_from_amo/

**Comment by ghost** [comment]
Maybe ask in the Reddit community 
It is a  hack I don't think you will get help with that here on github
@reyis4402

**Comment by interfect** [comment]
That procedure won't work quite the same for this fork; the cache file name it uses is different.

Also, that procedure tells you to overwrite the cache file; the browser will eventually clobber it with whatever it fetches from the collection it's still pointed at.

I'm going to close this because I don't think this is really quite related to this project, although it does raise the idea of building out UI to point at your own collection or JSON file. You might have better luck getting a visual tutorial by asking in the linked Reddit thread.
