### ISSUE TITLE
Sync to Firefox beta or nightly

### ISSUE THREAD

**Issue by revolutionaryking7** [fork-maintainers/iceraven-browser#275]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have exactly one feature request described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Feature Requests are better when they’re open-ended instead of demanding a specific solution e.g: “I want an easier way to do X” instead of “add Y”)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

### What is the user problem or growth opportunity you want to see solved?
As ice raven is a fork and updates are not released regularly is it possible to sync or build iceraven with Firefox beta build or nightly instead of the stable branch

### How do you know that this problem exists today? Why is this important?
Browser might get outdated as updates are released so lately
. Besides no harm in syncing with beta branch or nightly

Nightly might be unstable but beta should be preferred 

### Who will benefit from it?
All users

**Comment by CharmCityCrab** [comment]
Respectfully, I can not agree with the original post.

Iceraven can't offer a true alternative to Firefox that a wide variety of users can feel comfortable setting as the default browser on their phones if it lacks stability.  

A move to switch the browser over to using nightly as the basis for large chunks of its code or to adopt beta as the basis for all of the non-customized portions of the browser would almost by definition make the browser less stable.  

Iceraven doesn't exist to test things out for possible inclusion in Firefox.  Obviously, it's open-source code and Mozilla can use what they want, and I think people would actually be happy if they did adopt more of Iceraven's better features (It's happened at least once in the past), but Iceraven users are not beta testers intentionally using this browser to serve as a test bed for a different browser.  

A lot of Iceraven users make Iceraven their default browser and see it as an end unto itself.  It's own animal (Pun intended, but it works figuratively, too :) ).  Mozilla doesn't fund Iceraven.

Actually, that Iceraven gets updates less frequently than some other browsers to me suggests a reason to make the code as stable as possible.  If the folks maintaining Firefox Nightly push new code one night and it breaks something, they can push new code to fix it the next night or the next week (and then maybe more code a few days later to fix the fix, which may break something else.  Along with said fixes may come unrelated new code that breaks other things as well.), whereas Iceraven does not currently have enough developers with enough time to devote to the project to maintain that level of nimbleness.  There are going to be all sorts of things introduced at the Firefox Nightly level that just aren't stable, and if those are absorbed into Iceraven, there is a chance that whatever stabilities are introduced into Firefox Nightly, who's users only have to experience them for a short duration, will endure in Iceraven for a month or more, until we get the next batch of buggy code from Firefox Nightly.

That is not a pleasant user experience for mainstream users. I've never used a nightly anything and don't plan to start anytime soon.  Even betas make me a little skittish. I prefer my software finished.

Frankly, the recent history of Firefox has been that even their stable Android builds are not all that stable.  Nightly sounds like a nightmare to me.

If anything, I would like to see Iceraven move in the other direction and base almost entirely on Firefox stable, editing in options that Mozilla restricts to beta and nightly users because those options, in my view as a matter of principle, should not be restricted to beta testers and belong in the mainstream browser.  Mozilla won't do it in Firefox, but Iceraven can do it in its own browser.  This would include about:config, the broader extension compatibility, and so forth.

On top of that base, Iceraven would patch in its own original code offering more options (Like the ability to enable full URLs including protocol and www), it's own defaults that help create it's out of the box look and feel (Like square tabs by default), any features Mozilla strips that Iceraven wants to continue to maintain, any features that might be invented or preserved in other Fenix-based browsers (For example, the proprietary telemetry code stripping code from another fork of Firefox), and so forth.

If there is a "killer feature" that offers more customizability that is new to nightly or beta and looks like it could be coded into Iceraven now and then excised when it hits stable and Iceraven is ready to base on that new version of stable, and there are enough developer hours to manage that, that would make sense, too.

Ultimately, though, I don't view being a browser that aims to have a lot of options, customization, ability to view what's going on under the hood and so forth to be synomous with being unstable.  Yes, each option introduces more theoretical potential for instability, but that makes it all the more important that the core of the browser is the based on something stable and we don't have to deal with some bullshit thing someone at Mozilla pushes to nightly every so often that doesn't work right for extended periods of time.

It also is worth noting that some users are using this browser percisely because Mozilla doesn't always have great judgement in their view on what constitutes positive change and what doesn't.  Many times Mozilla's changes actually take away options and customizability.  That's really the great truth around this browser's origins- Mozilla took away a ton of stuff.

If Mozilla introduces code to take away something again, I'd rather have our users and developers be firewalled against it while it works it's way through nightly and beta in the hopes that Mozilla will abandon it before it makes it to the stable versions Iceraven would base off of.  That also provides our developer (or developers if we can get some more volunteers again one day) time to evaluate whether or not we can reverse Firefox's negative change and write the code that do it, all before it ever gets to Iceraven, fixing it before it ever hatches on Iceraven.

Basing on nightly is really not much different from being nightly.
