### ISSUE TITLE
[Web content bug]"game.granbluefantasy.jp"'s web content bug

### ISSUE THREAD

**Issue by naloder** [fork-maintainers/iceraven-browser#277]
The web content in game. Granbluefantasy.jp is not properly scaled and displayed.When I play the game content, the web content is skewed to one side. The bug appears to exist in the original Firefox, but in non-Firefox browsers (Chrome and other browsers will work), it's not clear if this bug can be fixed?

**Comment by interfect** [comment]
If the bug is reporducible in Mozilla Firefox, I would recommend reproducing the issue with that and reporting it in https://github.com/mozilla-mobile/fenix. All the web page rendering issues are really going to come to us through our dependency on https://github.com/mozilla-mobile/android-components but I think Mozilla tracks all the mobile Gecko rendering bugs through the fenix repo.
