### ISSUE TITLE
extension request: Read Aloud and other

### ISSUE THREAD

**Issue by DefectiveByDesign** [fork-maintainers/iceraven-browser#284]
I am still using fennec 68 until Read Aloud can be installed on FF mobile.
https://addons.mozilla.org/en-US/firefox/addon/read-aloud/

it would also be cool if other extensions were added like
dissenter  -just because, but I doubt it's possible due to being blocked
fennec copy link text
video download helper? or something similar "media download helper" works on 68
No Transition - this probably helps performance a lot
save-data: on  -seems useful and doesn't use a service
SoundCloud Downloader -doesn't use a service
Scroll to top -+++++ This is a must extension for reading usability
external video player - maybe you want to use VLC, limited compatibility tho
link cleaner+
Dark Mode  - I think this was faster than dark reader, but a lot of these UI extensions are slow
Maximum Image Size -good for fixing image sizes

edit: I got some extensions installed by changing the addon list.  Some on the original list are broken anyway.
Now the only issue is the usability downgraded UI, and how all my settings would have to be transferred. I might need to look into a password manager, but I don't want some backdoor spyware cloud service holding my data either.

**Comment by interfect** [comment]
I've added these to the collection that Iceraven uses to populate its list:
* https://addons.mozilla.org/en-US/firefox/addon/read-aloud/
* https://addons.mozilla.org/en-US/firefox/addon/fennec-copy-link-text/
* https://addons.mozilla.org/en-US/firefox/addon/video-downloadhelper/
* https://addons.mozilla.org/en-US/firefox/addon/save-data/
* https://addons.mozilla.org/en-US/firefox/addon/soundcloud-dl/
* https://addons.mozilla.org/en-US/firefox/addon/scroll-to-top/
* https://addons.mozilla.org/en-US/firefox/addon/link-cleaner-plus/
* https://addons.mozilla.org/en-US/firefox/addon/dark-mode-by-albert-inc/
* https://addons.mozilla.org/en-US/firefox/addon/maximum-image-size/

These I couldn't find on AMO:
* "dissenter"
* "No Transition"

These are already on the list, but don't show up for some reason in the application (#185?):
* https://addons.mozilla.org/en-US/firefox/addon/external-video-player/

Since you've gotten the custom collection feature working and I managed to find most of these, I am going to close out this issue as fixed.

**Comment by Aryoibrahim340** [comment]
How to install addons Videos DownloadHelper on Iceraven android ❓
