### ISSUE TITLE
[Bug] Search add-ons does not work in iceraven 1.6.0

### ISSUE THREAD

**Issue by cbwee** [fork-maintainers/iceraven-browser#288]
[comment]: # (Please do your best to search for duplicate issues before filing a new issue so we can keep our issue board clean)
[comment]: # (Every issue should have the exact bug and steps to reproduce described in it. Please do not file feedback list tickets as it is difficult to parse them and address their individual points)
[comment]: # (Read https://github.com/mozilla-mobile/fenix#i-want-to-file-an-issue for more information)

## Steps to reproduce
1. Install iceraven 1.5.0, and search add-ons in it, results will be shown without issues.
2. Update iceraven to version 1.6.0, go to search add-ons again, the result is always empty, even after typing something in the search box.

### Expected behavior
iceraven should show results after search for add-ons.

### Actual behavior
The result is always empty.

### Device information

* Android device: POCO M3 (M2010J19CG)
* Fenix version: 85, iceraven 1.6.0

**Comment by interfect** [comment]
This is definitely a bug I can reproduce. I will see if I can fix it.

**Comment by interfect** [comment]
OK, search broke because in 1.6.0 we picked up the install-add-ons-from-AMO-links code from Mozilla Firefox, which touched [this line](https://github.com/fork-maintainers/iceraven-browser/blob/1da7a9fac7ef13ddf228b81927b3ef8e5270533b/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt#L179) and made me start putting the add-on list into a local. The search feature is still pulling from [a class member that Mozilla doesn't have](https://github.com/fork-maintainers/iceraven-browser/blob/1da7a9fac7ef13ddf228b81927b3ef8e5270533b/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt#L68) and that now never gets populated.
