### ISSUE TITLE
Search Option in Addons Menu

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#3]
### What is the user problem or growth opportunity you want to see solved?
Plethora of Addons are available now it is difficult to find what you are looking and is time consuming .
My suggestion will be to add a search button or atleast sort the addons  by user count (in descending order)

### How do you know that this problem exists today? 
Previously when there were only a handful of addons for fenix this was not an issue 
And in case of fennec it was a webpage which allowed search 
There is no such option in current build

### Who will benefit from it?
Every user who uses addons on firefox

**Comment by CharmCityCrab** [comment]
I'm just brainstorming here, but could the browser setup a customized search using DuckDuckGo or another private search engine that hunts through all the appropriate AMOs, but only the AMOs, and integrate that instead of having to set up a search mechanism itself from scratch?  That might be a way of providing the functionality without having to code and maintain the full search mechanism, but rather just a hook to an existing service and perhaps a fallback hook to another one if the first one doesn't go through for whatever reason during an instance of the user using it.  Obviously, search engines that don't provide good privacy guarantees, like Google, would be something that one would want to avoid in that context, I would think.  This could be a search button or area within the browser's extensions area.

Of course, if it's easier just to code a search mechanism that is completely within the browser, that's obviously better.  I am just thinking from the perspective that it might be an extra thing to code and maintain, and with a limited number of developers, if there is a way to work around that and still provide the functionality to users, maybe it's worth doing.  It really depends on how much work these options represent for the devs, though, both at the beginning and going forward.  But since the search extension functionality requires the user be online regardless of where the back end is (It has to look through the web for extensions), there would be no difference from the perspective of losing off-line functionality.

Another thought here is that I wonder if some Fennec or even desktop Firefox code for extension searches could be repurposed, redirected, and reconfigured for Iceweasel-mobile.

**Comment by interfect** [comment]
I'd love to take a better add-on UI or search function PR, or something that lets you just install whatever you want from the AMO page. But I can't say I'm able to write it myself.

**Comment by abhijitvalluri** [comment]
#50 implements this!

**Comment by interfect** [comment]
This is implemented in the release I'm currently uploading. Thanks @abhijitvalluri!

**Comment by ovartt** [comment]
There is an awesome plugin on the list
**Swift Selection Search**
but it doesn't work
Please tell me what needs to be done to make this plugin work

Thank you so much for developing a cool browser
It will tear the rest of the browsers to smithereens
