### ISSUE TITLE
Add-On Request: Mue

### ISSUE THREAD

**Issue by CharmCityCrab** [fork-maintainers/iceraven-browser#308]
[Mue](https://github.com/mue/mue) (Github) is a new add-on for [desktop](https://addons.mozilla.org/en-US/firefox/addon/mue/) (Mozilla AMO) Firefox (and Chrome) that offers customized new tab content.

I am not sure if it would work as-is for mobile (It probably depends on how similar the code for content on tabs is on mobile relative to desktop), but we could add it to the list of Iceraven mobile extensions and find out.

If it doesn't work, since Firefox probably isn't allowing any new Android-specific submissions to the AMO and Iceraven doesn't have an independent AMO, I was considering trying to approach the Mue folks to see if they would consider filing an Iceraven pull request to integrate Mue as an option or pre-bundled extension that could be toggled on or off in Iceraven under "tabs" or "customize", and if the Mue folks are willing to continue to file pull requests as needed to retain compatibility with Iceraven's upstream as Iceraven syncs up with it periodically.

I think integration could in theory benefit both the extension, as Iceraven likely has a much larger userbase than they do right now that would be exposed to it as an option, and the browser, which would be adding more native customization that is clearly visible, creating an additional visually obvious differentiation with Firefox out of the box (if Mue is enabled by default), while being in line with Iceraven's objectives (More options and customization), and perhaps not requiring much if any upkeep on Iceraven's side as it would be in essence a pre-bundled/integrated extension maintained by Mue.

However, before I approach them, I want to see if we can add it as an add-on to our list and whether or not that works.  If it works that way, there's probably no need for the rest of that as interested users could just install it on Iceraven themselves. :)

**Comment by R0M4N0F5K7** [comment]
I tried it and as expected it doesn't work. From my experience most add-ons work on mobile if they just interact/work ON webpages (overlays etc.), but if it interacts with the UI or framework of the browser it doesn't, so, here too, the add-on can't tell the mobile browser to redirect the new tab ( - the new-tab behaviour in firefox android is weird anyway, because the new browser page seems to be weirdly isolated). Displaying the new page correctly wouldn't be the problem as you can see when you load [Mue's test page](https://demo.muetab.com/) on mobile.

P.S.: I am kinda surprised that you didn't just add it to a private add-on list and test it out yourself considering that doing so would have saved you time writing about it as well as iceraven's maintainers reading and testing and adding it.

**Comment by CharmCityCrab** [comment]
> I tried it and as expected it doesn't work.

Thanks.  Since the add-on isn't compatible with mobile, I'm going to close the issue.
