### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by byone421** [fork-maintainers/iceraven-browser#329]
Why can't I sync Firefox(PC)  bookmarks

**Comment by finprog** [comment]
the whole sync process freezes in iceraven 1.11.1

**Comment by interfect** [comment]
I'm not able to reproduce a freeze when syncing on 1.11.1. I was logged in before installing the update, but when I go to account settings and hit sync now, it syncs and doesn't freeze the app.

Are you trying to log in for the first time on 1.11.1 or were you logged in on an earlier version?

**Comment by finprog** [comment]
> Are you trying to log in for the first time on 1.11.1 or were you logged in on an earlier version?

I was logged in on an earlier version previously.
It works mostly if I log out and then log in, but login is sometimes hard / takes a long time.

**Comment by finprog** [comment]
Sync freezes in 1.13 an in 1.14 too. I see the same problem in fennec 93.1.0

**Comment by interfect** [comment]
I managed to get a crash to happen that I think was related to sending tabs around via sync (I hit sync now and it crashed), but I haven't yet reproduced it and managed to get an `adb logcat` log to see what the cause is. If anybody observing a freeze could post the Iceraven-related parts of the `adb logcat` log from the time of the issue, that might help.
