### ISSUE TITLE
[Bug] Add-on installation Failed

### ISSUE THREAD

**Issue by ghost** [fork-maintainers/iceraven-browser#33]
## Steps to reproduce
On Trying to install these addons Icweasel fails to do so and displays toast Failed to install xyz Addon
Here xyz are 
Video DownloadHelper
Youtube Video and Audio Downloader

### Expected behavior
They should install perfectly or should not be shown in list

### Device information

* Android device: AOSP 10
* Fenix version: Fork 6

**Comment by interfect** [comment]
I don't think that the expected behavior you mention is what I was going for. I'm just adding any add-on anyone wants to try to install to the list. No attempt is being made to vet them, contrary to what the UI implies with its "recommended" label.

I could take them off the list if we're sure they don't work and the devs don't seem to have any ambition to update them to work.

**Comment by ghost** [comment]
I think addons which are known/reported  not to work should be removed and added when developer of the add-on fixes it
By the Way Clean Now button of Cookie Auto Delete causes Browser to crash

**Comment by unixfox** [comment]
> By the Way Clean Now button of Cookie Auto Delete causes Browser to crash 

That's strange because it doesn't crash on mine when I tap the "clean" yellow button.

**Comment by ghost** [comment]
Edit
![GIF-showing crash](https://user-images.githubusercontent.com/59386233/91654883-3c0d0100-eaca-11ea-859a-2984ecfb0910.gif)

> > By the Way Clean Now button of Cookie Auto Delete causes Browser to crash
> 
> That's strange because it doesn't crash on mine when I tap the "clean" yellow button.

It is crashing for me

**Comment by interfect** [comment]
OK, I pulled "Video DownloadHelper" and "Youtube Video and Audio Downloader" from the list, since we really think they're totally broken.

At least some of "Cookie Auto-Delete" seems to work, and it all supposedly works for some people, so I'll leave it on the list.

**Comment by dessant** [comment]
I was just contacted on Twitter regarding Buster also failing to install. Both Video DownloadHelper and Buster declare the `nativeMessaging` permission, so maybe that needs to be ignored by the browser for a successful install, as Fennec did. Until the issue is solved, please also remove Buster from the collection.
