### ISSUE TITLE
New Name?

### ISSUE THREAD

**Issue by interfect** [fork-maintainers/iceraven-browser#36]
There have [been](https://github.com/interfect/fenix/issues/14#issuecomment-683137838) some [complaints](https://www.reddit.com/r/firefox/comments/iiz18o/iceweasel_new_fork_of_fenix_has_more_extensions/g3a3haz/) about "Iceweasle" as a name.

Anybody got ideas for a better one? Bonus points if you want to make the other branding assets. The source files I've been using are all in https://github.com/interfect/fenix/tree/fork/fork-asset-sources

**Comment by TheEvilSkeleton** [comment]
IcePhoenix?

Also, I'd advise to change the repo (`interfect/fenix`) to `interfect/[NEW NAME]` once the name will be changed. It's hard to tell by the link that it's an actual fork

**Comment by CharmCityCrab** [comment]
**SeaOtter** (Or SeaOtter Browser- putting the word "Browser" in the name would give people a way to search for it without being overwhelmed by results about sea otters, the animals), maybe with a cartoon version of an otter in approximately the pose from the picture below, with the water and the air filling out the circle in different shades of blue?

http://inotternews.com/wp-content/uploads/2016/05/13226652_10207880392945119_4155353989096800808_n.jpg

If it's deemed important to continue to have a planet, his head and paws could be peaking over it (Just imagine a cartoon version of the picture above, but with a globe in front of the otter's stomach and probably no sea or air outside the globe).

Another idea, harkening back slightly to Netscape without taking anything under copyright, might be to have the SeaOtter with a steering wheel in his paws.  It'd be the wheel of a ship, but we'd probably have to basically find the Netscape wheel and say "Not that." and go find out what other sailing ship wheels look like, and use one of those, making it a homage, but clearly original.

A sea otter is a real creature, but as long as there are no web browsers or software that have used the name before, it should be able to still be trademarked and copyrighted _in the context of a web browser and in the context of software_.

I also had a more general question, so we can kind of understand the range of possibilities here.  Does Android support using actual photos as logos?  Or do they still need to be cartoons/artwork?  

If Android supports photos as icons, it might be worth using one because it would be eye catching.  People would look at other people's phone screens and their eyes would be drawn right to the logo, because no one does that, and ask what it is, which could help user adoption rates.  I doubt Android supports them, because if they did, I'd probably have seen some apps that use them, but I just thought I'd ask.

Applying it to the SeaOtter idea, for a photo we'd likely need to go to the person who took it (Probably the website) and get permission to use it.  For a cartoon, we'd just need to get anyone to draw it and contribute it, because that's probably a common otter pose and thus not something unique to the photo.

I'll probably have some other name suggestions at some point, too.  That's just the first one I thought of (Okay, the second one I thought of.  But the first idea I had was really bad. :)  This is the first decent idea I thought of. :) ).

**Comment by interfect** [comment]
Seaotter sounds nice. Looks like there's an Otter Browser already, which wants to be Opera:

https://otter-browser.org /

IcePhoenix is also nice. It's not a piece of software, but it is an artist: https://icephoenix.com/ But Mozilla used "Phoenix" and got run off the name by trademark claims from Phoenix Technologies, according to Wikipedia.

I always liked Mozilla Firebird's name, but the Firebird database software still exists. And "Icebird is a deluxe-sized toy that transforms between two organic beast modes: a snowy owl and a polar bear."

According to none other than facts.net, the firefox the animal is also known as a "lesser panda", "red panda", "red bear-cat", and "red cat-bear". Who wouldn't love browsing in Lesser Panda? Or CatBear (which is a cool looking band)?

**Comment by CharmCityCrab** [comment]
A couple more names that crossed my mind. Some of my suggestions will probably in general have something to do with early metaphors for the world wide web and the Internet, which were often water, navigation, and/or exploration based; combined with a cute animal.  Others are about a browser that lets you do more and know more.

- **SurfDog**.  One logo possibility: A cartoon dog with shades and a Hawaiian shirt rides a wave standing on two legs.  I'm thinking loosely based on a golden retriever, but the type of cartoon character who one would feel like could talk.

- **Limitless Browser**.  Logo of a message in a bottle floating in the ocean or a hot air balloon floating off to the horizon.  Slogan: "Who knows where fate will take you today?" or **"Chart Your Own Course"** (I actually like that second slogan as a slogan for almost any browser name and logo, within reason. :) )

**Comment by CharmCityCrab** [comment]
**SeaPig Browser**: The logo would look something like this, but would be perhaps a shade of turquoise (blue/green mix), and have the disturbing elements like the extra eyes on the side flank eliminated in favor of a friendlier cartoonier look:

https://public.media.smithsonianmag.com/legacy_blog/Sea-Swine-56.jpg

That image is from 1539, so it's public domain.  The project would control the name of the browser (as a browser) and the unique elements of the image inspired by that art that are used by the project but were not in the original work, though.

Wikipedia says a cartographer from the middle ages put that in the North Sea on his maps.  The idea is to capture a sense of adventure and exploration.  Something at once familiar and strange in an intriguing sort of way.

The drawback there is that it might be a battle to get a logo based on that to seem fun and inviting rather scary or gross, though.  I also get the feeling that this particular name would ideally be run past a few focus groups before implementing, to make sure that it doesn't cause people to discount the browser itself in some way, and of course focus groups aren't in the non-existent budget. ;)

So, I'm not sure, but I thought I'd put it out ther and see. Even if people think it's a bad idea, maybe it could inspire someone to come up on with a better one.

**Comment by CharmCityCrab** [comment]
I am seeing more and more sort or retro-futurism gain in popularity in various ways.  Essentially, stuff that looks like it came from the future as it was envisioned in the 1980s.  There is a sub-reddit called r/outrun that has a lot of people who create art along those lines.  Maybe I'll drop a link to this issue there and see if anyone can pop by with names or artwork ideas.

The Fenix dark theme with its vaguely neon page loading bar and stuff gives the "interior" a very slight amount of that look already.

**Comment by sagudev** [comment]
> Iceweasel Mobile combines the power of Fenix (Of which we are a fork) and the spirit of Fennec, with a respectful nod toward the grand tradition of **Netscape Navigator**, from which all Gecko-based projects came, including the earliest of our predecessors, the old Mozilla Phoenix and Mozilla Firefox desktop browsers.

As Iceweasel Mobile has a respectful attitude toward the **Netscape Navigator**, maybe name could be derivative from Netscape like Webscape Impersonator or Firescape Innovator.

**Comment by ghost** [comment]
FoxyDroid 
Raven Browser
Nova Browser
Sonic Browser 
ZoomDroid
Menace 
Crisis 
Blaze

**Comment by darhma** [comment]
Foxy droid already exists:
Foxy Droid (Yet another F-Droid client) - https://f-droid.org/packages/nya.kitsunyan.foxydroid
https://github.com/kitsunyan/foxy-droid

**Comment by TheEvilSkeleton** [comment]
> FoxyDroid
> Raven Browser
> Nova Browser
> Sonic Browser
> ZoomDroid
> Menace
> Crisis
> Blaze

I don't want to sound rude but they all sound like those stereotypical Chinese browsers that claim to enhance your privacy and speed when in reality they track you on a whole new level.

Though I do like using "Raven" as a base, so we could add an element before it:

- WaterRaven
- IceRaven
- FireRaven

It has a similar name to Firefox (element+animal) which will make it obvious for big Firefox fans that it's a fork of Firefox.

**Comment by LoneFenris** [comment]
One thought I had was simply RedPanda -- being the animal nicknamed "fire fox". There is a "redPanda Software" company though, so maybe that'd be a trademark issue -- not sure.

**Comment by esmoak** [comment]
BlazeFox
InfernoFox
SlickFox
EmberFox

Or add Raven to the end.

**Comment by interfect** [comment]
Everybody always does water, ice, and fire. Nobody ever does earth or air.
![image](https://user-images.githubusercontent.com/752054/91683469-94172800-eb09-11ea-8bde-34d1d5c3b8da.png)

And DDG tells me that "not many results contain EarthWeasle". That seems to be only in use as a username on Twitch and Destiny 2.

[Sea Pigs are a cool deep sea creature.](https://www.youtube.com/watch?v=_y4DbZivHCY)

Ravens are cool, but maybe too cool? IceRaven probably is the best raven name, but apparently it's also a [digital museum](http://www.iceraven.com/).

I do like RedPanda, but redPanda Software would probably be required to sue.

Waterfox probably proves that we can be some other kind of fox. But not EarthFox because "thF" is an unhappy consonant cluster.

**Comment by CharmCityCrab** [comment]
AirFox is already a Gecko based browser for desktop (and a financial services company).  Their sourceforge repository already says that it was last updated 4 years ago, so they'd probably be willing to sell the name, but I am not sure anyone on this end wants to pay for it given that as far as I know at this point this is a hobbyist project with no revenue streams or business plan.

Plus, if you buy a browser's name, you sort of inherit that heritage to some extent.  So someone would probably want to research what the deal was with that browser and whether this project would be okay with the association or not.

The otherthing air reminds me of that Mega Man 2 level with the robotic frogs in the clouds.  I am not sure AirFrog is anything special, though, especially since we'd have to steer clear of looking anything like the MegaMan graphics.

**AirShark** could work, but it depends on a couple things. One would be the ratio of people it attracts because anything with the word "shark" in it is automatically cool to the people it repels because it may be kind of scary to pick up your phone in a dark room at 4am half asleep and see this giant shark's was staring back at you. ;)  I am not sure "menancing" is necessarily high on the list of word associations one wants their web browser to have with the general public, but, then again...

Second potential issue is that there are a zillion different companies and products with that company.  Closest thing to software related I saw was a project studying wifi packet loss at the University of Wisconsin.  These companies don't seem to be making any trademark claims against each othe, though.  As long as there isn't a web or an Android app, this project could *probably* use it, but I am not a lawyer nor do I play one on the Internet.  It could be a hassle. I'm assuming even a small lawsuit against it that this browser would won would be a problem for it financially.

**Comment by ghost** [comment]
Raven7, Raven8
Number taken from corresponding firefox ex v79 gives Raven7 Browser
Next Raven8 Browser

Raven in itself is complete name no need to add 3l3mebts like fire earth air water 

SwiftRaven BlazeRaven are also good but lengthy
Browser name should be catch and cool and should not be difficult to pronounce

**Comment by TheEvilSkeleton** [comment]
> Sea Pigs are a cool deep sea creature.

~~That was hilarious but I digress~~

Since @interfect referenced The Last Airbender, we could try using one of the secondary bendings discovered in both The Last Airbender and Legend of Korra, such as:

- combustion
- lightning
- lava
- metal
- blood
- plant

Edit: [oh my God there are a LOT more](https://screenrant.com/avatar-last-airbender-every-type-bending-elements/)

**Comment by revolutionaryking7** [comment]
Firefork or smartfox or Icefox

**Comment by CharmCityCrab** [comment]
Raven Browser, which someone suggested earlier would have the fringe benefit of giving the project the ability to use a public domain or open-source style licensed image of a Raven as the logo on a short-term basis if we don't have anyone to draw a logo or don't get original submissions of suitable quality at first.

Then, later on, the original Raven Browser logo could be replaced by a Raven logo specifically designed for the browser kind of at the project's leisure.

That way if the desire is switch names ASAP, there is a time way to do it without having an artist and there is also the ability to revisit it and do it better when someone with the appropriate skill set is available.

Plus, there could be a small bump in usage from fans of the two time Super Bowl Baltimore Ravens football team (By coincidence, I am a big Ravens fan myself, even though I did not think to suggest it as a browser name- someone else did. :) ).

I don't think that qualifies as a copyright or trademark issue. A football team and a web browser are two separate things.  Just in case artwork used by the browser might want to avoid the football team's primary colors of purple and their thietary barely there color of yellow, but black should be fine even though it is the team's second most used color, because that's the color of the actual bird.

A logo could just be a raven, or it could be a Raven wrapped around a globe all the Thunderbird desktop email client.

What about **NightRaven**, potentially paired with the browser adopting the dark theme as it's default (With a user option to switch to the light theme, follow system settings, or use any other theme that may henceforth be developed)?

Another similar suggestion I've not yet seen would be **Condor Browser** or **IceCondor**.  If you've never seen a picture of a Condor or read about it, it's a pretty awesome bird.  It's huge.  One variant people may have heard of is the California Condor (Nearly driven to extinction), though I am not sure it makes sense to include the word "California" in the browser name.

**Comment by LoneFenris** [comment]
> Everybody always does water, ice, and fire. Nobody ever does earth or air.

You know, there actually is a "wind weasel" in Japanese myth or folklore called a "[Kamaitachi](https://en.wikipedia.org/wiki/Kamaitachi)". I'm not sure about using the Japanese name as it might invite cultural issues (Kamaitachi seems to be a kind of monster or bad spirit in folklore). A quick search doesn't show any trademark conflicts for "WindWeasel", though. 

You'd probably have to train yourself to stop making the "weasle" typo if a weasel name is chosen, however.

**Comment by interfect** [comment]
Aw man I just super can't spell.

**Comment by interfect** [comment]
Ravens are sounding widely unobjectionable, but looks like there's a "[Raven BrowserPRO](https://play.google.com/store/apps/details?id=com.wRavenPRO_8869180&hl=en_US)", as well as a defunct Mac "Raven" browser. So it probably needs another piece.

Iceraven is probably the shortest one and is easy to say, and neither the digital museum project nor the outdoor photographer already using the name are likely to be confused for it.

**Comment by ghost** [comment]
> You know, there actually is a "wind weasel" in Japanese myth or folklore called a "[Kamaitachi](https://en.wikipedia.org/wiki/Kamaitachi)". I'm not sure about using the Japanese name as it might invite cultural issues (Kamaitachi seems to be a kind of monster or bad spirit in folklore).

Using Kamaitachi as the app name doesn't cause cultural issues because the Japanese rarely describe them as bad spirits in modern works.
By the way, the fox whose name differs from Firefox in only two letters appears in Japanese folklore. The "[pipe fox](https://en.wikipedia.org/wiki/kuda-gitsune)" is narrow long foxes and can live inside bamboo pipes.

**Comment by bbigam** [comment]
Personally, I'd like to keep the Iceweasel name! 

It has a venerable tradition as a name for modified, FOSS-focused builds of Firefox. And it doesn't have only one lineage; it's been used by Debian (formerly), GNU (formerly, now IceCat), and Hyperbola. As far as I know it hadn't been used yet in Android, so now it's time... and it's kind of a cute, funny name. (I wouldn't object to a new icon, though!)

**Comment by interfect** [comment]
OK we're going to do an emoji poll. React with your favorite:

👍 = Iceraven
😄 = Windweasel (Easier to get than "Kamaitachi" and less obviously purloined from a culture that isn't mine)
👀 = Just be Iceweasel again
🎉 = CombustionCondor Browser or other write-in candidate

I'll come back in a week and we can check the results and use that.

**Comment by TheW0LVERIN3** [comment]
Maybe:
- MoltenFenix
- Liquefied
- jagged fenix
- rustic fox
- rustic raven
- icy fox
- sassy fox
- chubbyfox
- thirstyfox
- purplefox
- fireduck
- firebat
- icebat
- FireSloth
I hope any of these are any good, if not that's ok.

**Comment by spegheti** [comment]
How about **Vulpes Browser**, or just **Vulpes** for short? It's simple, has a connection to foxes, and as far as I can tell no apps are really using the name.

**Comment by abhijitvalluri** [comment]
I really, really like the Firefox logo. I liked the older more classic version of the logo better, but the new one is good too. However, the Iceweasel logo is such a downer. It does not make me excited to use the browser on the phone. 

I would much rather prefer a suitable clone of the Firefox logo, something that is inspired by it and has a wonderful design. And a name to go with it. Until then, I don't quite like any other alternatives suggested. May be Icyfox or something but nothing really clicks.

**Comment by kufue** [comment]
Iceglaucus, because not so many people know it, like the fact that not all people have android 5 or higher, it's pretty as a logo and animal "little blue dragon". Iceraven would be nice, but ravens have had a long history of ominous associations

**Comment by lazymonkey2** [comment]
I like Vanguard.

meaning:

noun
1.
a group of people leading the way in new developments or ideas.
"the experimental spirit of the modernist vanguard"
2.
the foremost part of an advancing army or naval force.

**Comment by lazymonkey2** [comment]
I like Argonaut too.

1. Greek Mythology One who sailed with Jason on the Argo in search of the Golden Fleece.
2. also argonaut A person who is engaged in a dangerous but rewarding quest; an adventurer.

**Comment by lazymonkey2** [comment]
If you prefer some *fox variations, these are actually types of foxes:

RedFox
SandFox
SilverFox
ArcticFox

And these ones are totally made up :-)

SparkFox  --> A vital, animating, or activating factor: the spark of revolution.
NovaFox
StarFox
FlameFox
StormFox
UltraFox
SkyFox
FlyFox
AlphaFox --> A dominant fox; a fox that is an alpha male or alpha female. Often used figuratively.
DreamFox
DragonFox
ZenFox
PowerFox

**Comment by wodnikk** [comment]
I think IceWeasel is an ok name, so I wouldn't mind if it stays. However, if it were to change, the best option for me seems to be **IceFox** (proposed here by @sheikh-azharuddin). It's simple, it just rolls of the tongue, just like Firefox, and it immediately brings the original to mind. 

Either way, here are some other ideas I had:

- IceWolf
- IceCoon

Or going with the bird imagery:

- IceJay

And with a mythological twist:

- IceRoc

**Comment by abhijitvalluri** [comment]
I too like the IceFox name. We should really settle on a name and I think IceFox is a good one to settle on.

Should we have a poll or something to finalize this? I think we have spent plenty of time brainstorming so far and would be nice to finally have a good name and avoid frustrating IceWeasel developers that this name is misleading.

**Comment by ghost** [comment]
> I too like the IceFox name. We should really settle on a name and I think IceFox is a good one to settle on.
> 
> Should we have a poll or something to finalize this? I think we have spent plenty of time brainstorming so far and would be nice to finally have a good name and avoid frustrating IceWeasel developers that this name is misleading.
But IceRaven is more cool and catchy 
Many Firefox based browser add Fox at the end of name 
But by adding Raven it can be something unique

**Comment by bbigam** [comment]
Actually, we just had a poll by emoji, and it looks like Iceraven won. See
Interfect's last post.

**Comment by abhijitvalluri** [comment]
While I am ok with IceRaven, it also appears to be the name of a video game character: [reddit thread](https://www.reddit.com/r/archeage/comments/2m96u7/lordly_iceraven_robes_much_sexy/). Are you okay with that association?

**Comment by eNV25** [comment]
Why not just use the "fenix" codename? IceFenix ?

**Comment by interfect** [comment]
I think we can probably out-SEO a 5 year old reddit thread, especially if we use "Iceraven Browser".

While I like a lot of the suggestions here, it looks like Iceraven is the most popular overall, so I think that's what we should go with. I'm going to lock the thread, and we can close it with a PR that actually does the rename. Anyone who wants to work on new logo designs or other branding art should be clear to start now.
