### ISSUE TITLE
Someone please archive this repo. It no longer serves any use and just keeps releasing automated releases.

### ISSUE THREAD

**Issue by TheW0LVERIN3** [fork-maintainers/iceraven-browser#364]
The firefox nighly version on the play store has all the features this app has. 
It has about:config. 
You can choose which extensions can be installed by clicking on the firefox logo is the about section of the settings and than going back to the settings and setting a custom addons collection.

This app was first in having these features but development has stopped and everything has been implemented in the official version.

It needlessly uses github resources. Peoples also still seem to install this version over the official nightly release judging by the amount of very recent issues created on the github repo. It should be archived.

**Comment by CharmCityCrab** [comment]
Even if Firefox nightly had all of the features of Iceraven (Which it doesn't), one important distinction would be that Firefox nightly is throwing alpha quality software out there for you to test in return for giving you some features they've taken out of, or failed to include in, regular Firefox and even in some cases beta Firefox.  Iceraven is based on Firefox stable's rendering engine and initially had some other components that were based on Firefox beta that Iceraven developers were at one time considering swapping even those out for their Firefox stable equivalents (I'm not sure whether that second part actually came to fruition or not.).  Either way, though, with Iceraven you're getting a more stable consistent product than Firefox nightly generally provides where they are both drawing from versions of Fenix.

The nature of "nightly" type software is that you're going to wind up, potentially, with features there one night, gone the next, and back on night three- buggy implementations and hotfixes, before ditching both and trying a third implementation and so forth.  Some people find that sort of thing fun and some feel like by doing it they are helping with project development, and that's fine.  That's not what Iceraven is, though.  

Iceraven is pretty modest and self-deprecating in how it describes itself in that respect on the project's main GitHub readme thing, but as someone who has been using it as my main phone browser for a year or so now, I can say that at least on my phone, the end Iceraven product is pretty stable and not something I'd compare to a nightly or alpha release.  Two different animals- and not just because one is a fox and the other is a raven. :)

In terms of features, I can tell you that one thing that was brought up with Firefox's developers and code that was offered to them that instead wound up in Iceraven within the first week or so of its development is the *option* to show full URLs including protocol and "www" (when applicable).  I haven't had Firefox for Android installed in a long time, but last I checked with people, they said that's a feature Firefox still didn't have.  And it's easy enough to implement that it is I think fair to say that they have made and continuing to make a choice not to give users that option.  Iceraven is open-source, so Firefox is free to grab that code at any time if they ever change their mind (Or code their own implementation), but so far they haven't.

That's just off the top of my head.  I could start making a list, but this isn't a novel. :)

I'll just also point out, though, that a big effort has been made with Iceraven to eliminate proprietary telemetry to the extent the curre t developer knows how to without breaking things.  That's a distinction that's important to some people, though technically not a feature.

There are definitely different visions with these browsers to some degree, even though they share a ton of code.  Iceraven wants to offer options and customization.  Firefox seems a bit more focused on streamlining and simplicity.  I say that not to be critical of Firefox, just to demonstrate that there are some differences in philosophy that give Iceraven more than ample reason to exist and try to come up with a close fork of Firefox that is closer to what Iceraven users have said they want.

What I will say is a fair criticism of Iceraven to a certain extent is that it hasn't continued as ambitiously independent development wise as it was at it's early height.  However, I think in all fairness, people should consider that Iceraven is not sponsored by a corporation or a non-profit, and right now has only a single developer who graciously puts in what time he can- for free- when he isn't too busy with his day job or living his life.

That under those circumstances, it's pretty amazing that he's able to deliver what I consider the best browser on the Android platform, even taking into account that it's a close fork of Firefox that merges Firefox's new code in regularly with the Iceraven specific changes.

And the other great thing about what he's doing is that it keeps this project alive.  If we ever get some other developers in here again who want to be, and have the time and skills to be, more ambitious again about adding options and creating and maintaining more Iceraven specific code, they will be able to jump in to a place where there is an up to date product with a name and a logo, a userbase that uses the browser every day, a GitHub with plenty of open issues to work on, a lead developer to coordinate with, and a clear identity/mission statement (Essentially, being the customizations and options browser.).  People who might choose to help out later don't have to start from square one and do their own fork and all of the stuff you have to think about with that, they can just help out here and just worry about coding.

Actually, I briefly checked out your GitHub comment history and saw that you are (or were) a student.  If you ever want to take some coding classes about coding for Android, this would be a great project to work with and get some real world experience.  I know that interfect, the lead developer, has been pretty consistent in saying he'd love to have the help.  Anything from just doing the grunt work of merging in the latest upstream updates with Iceraven's existing code to free interfect up for the harder stuff or to allow for more frequent releases, to troubleshooting and creating and maintaining new features is a possibility.  Pull requests are open to anyone.

Last but not least, I think you may be misunderstanding what is automated about the Iceraven releases.  What is happening there is, as best I can tell as a fellow non-coder, is that when interfect makes changes, which, yes, do include merging in changes in Firefox with the Iceraven code, among other things, and then decides to create a new version of Iceraven for public consumption, he has GitHub make a list of the changes he's made.  It's not GitHub automatically making all the changes- it's just handling the list so he can work on the code itself and not have to create the list next to the update that tells us what he's done, but we still are able to get the list. :)

Nothing gets released that he hasn't okayed (Well, except in the past when he shared duties with other maintainers who may have sometimes handled a release, and maybe in the future if that situation occurs again, but he even there, someone human is giving new releases the nod and doing work on them before they go out.).

I know Iceraven isn't available on Google Play or F-Droid, but you can get it right here directly and manually grab updates once in a while or get the program and updates for it through an F-Droid app called ffupdater that handles that for Iceraven, along with handling various versions of Firefox, Brave, and some other stuff.  So you've got options on how to get your Iceraven.  And you may have more options in the future.

Nothing is perfect in this world, but I would really miss this browser if it weren't here.  It fills a void for me, and I don't think I am the only one who feels that way.

It's also worth pointing out that having as many Fenix based browsers out there as possible is helpful to all the other ones.  Even Firefox doesn't have a ton of people assigned to Android development or a huge market share.  So, in so far as various forks like Iceraven create code that they have the option to absorb, and draw in users who would otherwise be using Chromium-based Android browsers but instead have Iceraven and other Gecko-based browsere providing websites Firefox's user-agent string and getting counted by websites as though they were Firefox, that helps.

These projects can all be mutually beneficial to each other.  

And giving users more choices when it comes to what browser they use is a good into itself, and can create positive pressure on similar browsers to up their game in certain areas.  Similarly, if these type of browsers disappeared, so would that extra bit of incentive for other browsers to up their games.  Iceraven has been a force for positive change in the Fenix browser community IMO and hopefully will continue to be for years to come.

**Comment by TheW0LVERIN3** [comment]
I'm sorry. I didn't realise there was still someone left maintaining it. 
I know the history of iceraven and even used it before there was custom extension support on firefox nightly. I remember the fork not even having a modified readme and the default fenix name. I used it since the fenix browser was in preview on the play store, I wanted support for more modern extensions and this browser gave that to me. I submitted a lot of extensions into the collection of iceraven via the reddit thread at the time. I know at one point we got to choose the name and then the logo and then there was a team. I also know about the tracking being disabled, but I didn't realise there was still work being done. 
The github repo just looks very dead, with every release being done by a bot(I now understand it functions based on requests by the maintainer) and most commits just being merges of upstream, no progress report, the readme saying firefox doesn't have these features, issues no longer getting tags or responses, etc.

I'm sorry. 
I didn't keep close enough track of the project and thought it was no longer being maintained, I was wrong about that.
