### ISSUE TITLE
custom add-ons collection does not work

### ISSUE THREAD

**Issue by sirati** [fork-maintainers/iceraven-browser#440]
I set custom add-ons collection and user as following:
collection: https://addons.mozilla.org/en-US/firefox/collections/16555455/For-Android-Iceraven/
user: https://addons.mozilla.org/en-US/firefox/user/16555455/

but it does not do anything.
Also that list is obviously addons i want

**Comment by xfzv** [comment]
Same here, I've just installed 1.15.0 and I cannot add any custom add-ons collection. I tripled multiple collections, to no avail.

It works just fine with Firefox Nightly.

Edit: works just fine with [Mull](https://gitlab.com/divested-mobile/mull-fenix) and [Fennec](https://f-droid.org/packages/org.mozilla.fennec_fdroid/) too.

**Comment by trumad** [comment]
I also happened to be trying this yesterday and couldn't get it to work. I don't think you're supposed to put in the full URLs though? I believe the strings you are supposed to use are:

Collection: For-Android-Iceraven
User: 16555455

But I couldn't even get that to work. I've switched to firefox nightly, at least for now.

**Comment by bauripalash** [comment]
Same issue with latest iceraven

**Comment by interfect** [comment]
This definitely isn't supposed to happen.

**Comment by ToTheMoon1234** [comment]
same issue

**Comment by interfect** [comment]
It sounds like this might not actually have been fixed.

**Comment by interfect** [comment]
I just tested this again in the commit that is https://github.com/fork-maintainers/iceraven-browser/releases/tag/iceraven-1.17.0 and it definitely works for me.

If I go to Customize and add a "-2" onto the name of the collection, I can make it load a different collection I have and I see a different list of addons. If I change the user number to a different number, it complains it can't load the list, which means it is actually trying to fetch the list from that user number.

@trumad is right about the formatting: the user should be a number, and the name should be the slug from the URL you get when you view the collection in the browser, which seems to replace spaces with `-`.

I'm going to close this again; if anyone still has this issue and wants it fixed I definitely need reproduction instructions, step by step, because I'm not sure what I'm doing that y'all are not.
