### ISSUE TITLE
Easier way of importing and exporting bookmarks

### ISSUE THREAD

**Issue by tg5hKVHPyX** [fork-maintainers/iceraven-browser#469]
### What is the user problem or growth opportunity you want to see solved?

Being able to import and export bookmarks in bulk. Currently I have to do it one by one and it takes way too long.

### Who will benefit from it?

Anyone who uses bookmarks.

If there's any CLI method using adb that can pull the bookmarks from app database feel free to tell me about it.

**Comment by aroguecoder** [comment]
> if If there's any CLI method using adb that can pull the bookmarks from app database feel free to tell me about it.

History and bookmark is stored in this file.
`/data/data/io.github.forkmaintainers.iceraven/files/places.sqlite`
I'm sure you can reiterate every entry and saved it as a text somehow.
Take a look at this [gist](https://gist.github.com/dogancelik/b82c6eac880eb58acd2b). 


I'm not sure why mozilla keeps making this changes.
previously it was stored on this file.
`/data/data/org.mozilla.firefox/files/mozilla/…….default/browser.db`

Hit me up when you've made a script that can automate this process, i'm not familiar with sql since i don't even code lmao.

**Comment by eladkarako** [comment]
saved me opening a new issue.  

>[feature suggestion] support importing bookmarks from html file.

will allow users to export their chrome synced bookmarks, and import it to iceraven, without using M0z!lla cr^ppy sync service.

**Comment by akliuxingyuan** [comment]
move to #103
