### ISSUE TITLE
when will the next update be ? 

### ISSUE THREAD

**Issue by GrayRats** [fork-maintainers/iceraven-browser#470]
when will the next update be ?
 It 's been a long time since the official release, so the engine has been updated and all this on the android version !
⏳⏳⏳I 'm really looking forward to it !

**Comment by dotcs** [comment]
There is also a security perspective to this question. To me it seems obvious that the maintainers of Iceraven cannot keep up with the pace of [Fenix](https://github.com/mozilla-mobile/fenix/releases) and also the Readme mentions that security wise this fork might be problematic, still I wonder what the plan for the future is. Are releases planned to happen more often once the machinery is oiled?

**Comment by SkewedZeppelin** [comment]
Iceraven has 5 features in total:
- a different default addon collection
- the ability to show more than 50 addons
- the ability to not hide [www](http://www/). in the URL bar
- an option to let the browser die if another app on phone needs the ram
- pull to refresh

Are those all worth it for the 41 known security issues it has?
https://divestos.org/misc/ffa-dates.txt

**Comment by CharmCityCrab** [comment]
> Iceraven has 5 features in total:
> 
>     * a different default addon collection
> 
>     * the ability to show more than 50 addons
> 
>     * the ability to not hide [www](http://www/). in the URL bar
> 
>     * an option to let the browser die if another app on phone needs the ram
> 
>     * pull to refresh
> 
> 
> Are those all worth it for the 41 known security issues it has? https://divestos.org/misc/ffa-dates.txt

Have you considered volunteering for the project?

On a minimalistic level, maybe just cutting an update combining the two modules Iceraven takes from Firefox unaltered, combining it with the one Iceraven does alter, mashing them together, doing a small bit of web surfing to make sure it works, offering it up as a pull request, and optionally asking to be added as a maintainer would be a huge help right now.  @interfect has said he'd be interested in someone doing that regularly.

Maximally, you could offer to take over or fork the project, and rebase it on Fennec or Mull for ease of juggling multiple Fenix projects at once on your end.  Really, it'd be a spin on the other project of your choice with the extra Iceraven features and branding.

It could also be forked into something like "SunParrot" and you could use a really great logo for it that lost out in the pick a logo contest (Everyone said it looked more like a parrot). :)

I agree that security and updates are becoming bigger and bigger issues.  However, this is a really sticky browser for a lot of us because it offers things other browsers don't.

I think there are probably a couple more features not in the list (Unlimited scroll on the home screen maybe?  I am not sure where Firefox is on that.  It used to be an Iceraven only thing, I think.).   We also have stuff like a gazillion tab options that someone other than Interfect created for us, but were removed from Iceraven circa 1.5 because Interfect was unable to maintain them in the time available to him given changes upstream and the guy who was maintaining the code downstream previously being unavailable.

This project was once a lot more ambitious.  There are a lot of features we've all agreed would be good but which are not doable for whatever reason under present one person maintainance.

**Comment by CharmCityCrab** [comment]
Also worth noting that the list of features above doesn't mention a lot of things that Iceraven's stable version shares with some other forks that Firefox's stable version doesn't offer- about:config access, the ability to use more than the 9 extensions Firefox stable offers (In Iceraven's case, there is the unique spin of being able to do it out of the box and the extensions just being there in the GUI without any codes or non-intuitive clicks, and without a Mozilla website account- which I am not sure any other Fenix browser offers ATM), no pocket integration, no advertisements, removal of telemetry (In Iceraven's case, this in theory [as stated in the readme.md] includes the removal of even open-source telemetry, though the code base may or may not reflect that vision at this point), etc..

Iceraven also has the ability to play DRM video content (Or at least keeps prompting me about whether I want to allow individual sites to play it.  I'm not sure I've ever actually tried to watch a DRM video on it.), which is present in Firefox, but not in many of it's forks.  I wouldn't mind seeing that feature go if the project were rebased on a fork that doesn't have it, but, for now, it makes Iceraven unique among the forks and is a feature to some.

**Comment by CharmCityCrab** [comment]
> On a minimalistic level, maybe just cutting an update combining the two modules Iceraven takes from Firefox unaltered, combining it with the one Iceraven does alter, mashing them together, doing a small bit of web surfing to make sure it works, offering it up as a pull request, and optionally asking to be added as a maintainer would be a huge help right now. @interfect has said he'd be interested in someone doing that regularly.
> 
> Maximally, you could offer to take over or fork the project, and rebase it on Fennec or Mull for ease of juggling multiple Fenix projects at once on your end. Really, it'd be a spin on the other project of your choice with the extra Iceraven features and branding.

Not to get too deep into the weeds here, but in theory, these approaches could be combined.  The first approach could be used to get the browser updated ASAP and keep it updated in the near-term future, while behind the scenes work could be done integrating the feature set with a different upstream browser, which eventually would be an update to the on-going Firefox-based upstream updates.

Just as an aside, I do like the name Iceraven (Though I voted for something else back in the name the browser contest, I think.  I don't remember what) and keeping some sort of animal motif in a hypothetical fork if the Iceraven name isn't available would I think be a plus.  People seem to like that sort of thing.

**Comment by interfect** [comment]
I don't have really any tools to do the merges with Mozilla Firefox that other people don't. If someone wants to PR the new changes in, please go ahead. If they want to lit off with their own MoonStoat or SunFerret or JupiterRedPanda I would be quite happy to use that instead of sitting around feeling like I really ought to spend 3 hours fighting Git conflicts and then not doing it. If some other better-staffed fork can steal all the features, that'd be just perfect.

I can see if I can come up with a new build this weekend, if people really want one.

I'd rant about how those 41 known security issues don't just appear by magic in Iceraven but rather have been there more or less the whole time, and that when a new update comes out it will also have 41 security issues that will become known over the next 3 months, and that maybe we should all just switch to Gemini or something that can actually be correctly implemented, but... oops I guess I did.

**Comment by interfect** [comment]
Sadly it's not going to be this weekend after all. Maybe tomorrow after I make dinner?

Anyone have an idea of how many git conflicts there are going to be this time? Or better yet, a way to get git to actually help me maintain a modified branch that takes changed from upstream and never merges back, instead of fighting me constantly because I'm merging in different versions of the same upstream commit? Do I need some kind of rebasing workflow? Should I be merging all the Iceraven changes into a single mega-commit that just gets rebased?

**Comment by dotcs** [comment]
@interfect Sorry to hear about the amount of work it takes to maintain iceraven. Can you maybe briefly describe what you usually do to see if we can speed up the merge process somehow? I have the impression that rebasing might help but I'm not sure about the current procedure so I think I first would need to understand.

I think what I would probably do is to have a branch in which I pull in changes from upstream, let's call it `upstream`, and then have a second branch with the customizations which I would always rebase on top of the latest changes in the `upstream` branch. This will not remove all merge conflicts, but you will never have to fight anything in the upstream branch, instead you only have to figure out any conflicts in your own code.

**Comment by interfect** [comment]
Usually I've been merging each Mozilla Firefox tag into one branch, interleaved with Iceraven-specific commits. But since Mozilla's release tags aren't directly descended from each other, and often have different versions of the same commit in them (since it gets merged to their dev branch and their release branch), this creates a lot of conflicts.

This time I've collapsed all the Iceraven changes into one commit, which I've rebased from the old Mozilla release tag onto the current Mozilla release tag. This makes a lot less conflicts, but we lose all of the Iceraven commit history, which is annoying and also not really fair to people who contributed commits. This is also a lot harder to pull request; you can't make a pull request that says "replace the target branch with this other branch", as far as I can tell.

I could also rebase the Iceraven changes without squashing, in theory. I tried that first, but since they're interleaved with merges from Mozilla's various tags, which contain commits not in Mozilla's current latest tag, Git wants to bring a bunch of Mozilla commits along in the rebase. I'd have to work out how to select the Iceraven commits and exclude the Mozilla commits in an automated way in order to pull that off. Plus I'd have to resolve conflicts for all points in history, instead of just at the final state.

Git really isn't designed to do this, as far as I can tell. I want to have like a sub-history, but then have it resolve to a single final diff that gets applied against something else.

Anyway, I have a 1.16 release building now, and I think I've fixed the release action to not try and make an enormous changelog when the release doesn't descend from the last release. So it should be up soon.

**Comment by dotcs** [comment]
I really appreciate your hard work for this project @interfect. Thanks a ton for creating a new release. :rocket: 

I'm still thinking about how the workflow could be improved. Is it possible to cherry-pick the commits you want to have in a separate branch on top of the latest upstream changes? I'm sure you can list all the git sha hashes for all the commits that have been done in the iceraven project, right? From there on it should be possible to just `git cherry-pick` them one after the other. This could still lead to merge conflicts though but I think it should not be worse than in the solution that you just have applied with the squashed commits. If this would be possible then you should not have any problems with interleaved merge commits and it would be possible to keep the iceraven commit history along with the info about the contributors. Could that potentially solve the problem?

**Comment by interfect** [comment]
If I don't squash and I cherry-pick the commits instead, I think I still can have to resolve conflicts when the first commit conflicts, and I resolve it, and then the second commit conflicts with the resolution, so I have to resolve another conflict at more or less the same place in the same file.

It might not be *much* more work though. Maybe it is worth doing.

**Comment by dotcs** [comment]
You're right, that might be more work in the first place. But it may pay off in the long-term. I'm wondering if the upstream changes so often that you get merge conflicts all the time or if code changes occasionally and you will have most of the conflicts resolved for the next time. 🤔

If you want to stick with squashing commits: There might be some kind of a solution to this with the [`Co-authored-by` trailer](https://github.blog/2018-01-29-commit-together-with-co-authors/) in the commit message. Maybe that helps to at least keep the credit for those that have contributed in the past.
