### ISSUE TITLE
How to disable history shortcuts on homepage/new tab

### ISSUE THREAD

**Issue by subtilt** [fork-maintainers/iceraven-browser#475]
How do I disable history/recent shortcuts on the new tab/homepage, so that only my pinned/top sites shortcuts are shown like it was up until 1.15.0?

**Comment by CharmCityCrab** [comment]
Hamburger menu>Customize Homepage

Then adjust the toggles as desired.

**Comment by subtilt** [comment]
Tried that but it doesn't seem to work. I guess I'll have to try again.

**Comment by subtilt** [comment]
I 

> Hamburger menu>Customize Homepage
> 
> Then adjust the toggles as desired.

I did this but unpinned shortcuts/recent history are still showing. Very annoying.

**Comment by CharmCityCrab** [comment]
Iceraven 1.16.1 came out after the prior posts in this thread.  Anyone having issues who hasn't updated yet may want to give it a try.  

I am not sure anything in the update pertains to this issue, but it's sort of standard operating procedure for people bothered by a bug to update to the newest version of any given piece of software software to see if their bug was resolved.  There's no change log for the update, so I don't know what it covers (My guess would be a small branding issue I noticed with 1.16.0, but it could anything, including this, potentially.).

Anyhow:

I can get the browser to a point where my pinned shortcuts show and then my most visited shortcuts, each with a square icon in a grid layout, without the "recently visited" section that shows up below that in list form when certain options are enabled.

Is that what you're going for?  Or do you just want pinned shortcuts and nothing else displayed?

I'm not sure if it's possible to *only* show pinned shortcuts.  I think the "shortcuts" toggle is the pinned shortcuts plus most visited shortcuts as square icons in a grid.  The "recently visited" toggle seems to add (or subtract) a section below that with a list view of most recently visited sites.  Turning off all the toggles can get you a blank home screen if you want it, and of course there are various other toggles to add or subtract various other things.

It's possible that there's an extension or an about:config setting out there that would allow you to only see pinned tabs and not most visited sites.  

It appears as though upstream Firefox put pinned tabs and most visited sites on one GUI toggle together and that Iceraven kind of inherited that behavior, though.

Anyone test this in the latest version of Firefox and/or other forks?  If someone has been able to separate the two options back out, maybe Iceraven could borrow their patch for a future update.  Also, if someone can write a patch and submit it to Iceraven as a pull request, that might work.

This issue doesn't effect me personally since I like the pinned icons/most visited sites combo grid layout.  However, if there's an easy way to give people who only want one or the other an option that would allow that, it seems like that'd be a nice thing to add.

**Comment by alexolog** [comment]
> I'm not sure if it's possible to _only_ show pinned shortcuts.

It was possible up until the latest version.  In fact, that was the setup I had since I started using IR.

An update to 1.16.1 added unremovable history.  This is a regression, please fix.

**Comment by subtilt** [comment]
Exactly. There simply isn't a fix for this. Which is ridiculous. Needs to
be fixed. I just don't understand why one would get rid of this feature.
It's sucks. If you don't keep deleting the history you'll end up with a
super laggy homepage. I have an s21 ultra which is a flagship phone so it
has nothing to do with hardware. It's to do with the fact that the homepage
gets cluttered with this retarded feature that cannot be disabled. Please
fix this asap

**Comment by subtilt** [comment]
Still no update on this? I would like the homepage to just show my pinned url shortcuts and nothing else. I've updated to the latest 1.16.1 but it's still giving me the same issue - auto pinning last visited sites as well. Super annoying. I've tried to dig around in the about:config settings as well but to no avail.

Might just have to go back to version 15 unfortunately. However, if someone has an update or some form of fix for this particular issue then please let me know.

**Comment by alexolog** [comment]
This was broken intentionally by Mozilla in https://github.com/mozilla-mobile/fenix/issues/23159.
Please complain here: https://connect.mozilla.org/t5/discussions/android-v100-history-update/m-p/6616
Please comment here: https://github.com/mozilla-mobile/fenix/issues/25969

Can the IceRaven fork fix this?

**Comment by seniordevel** [comment]
I do not see, why we need bookmarks AND shortcuts! What's the difference in effect? 

I suggest to remove the shortcut feature in favour to bookmarks at the homepage. 

This should also resolve the issue with auto-added history.
