### ISSUE TITLE
[Add-on Request] Firefox Translations

### ISSUE THREAD

**Issue by tyteen4a03** [fork-maintainers/iceraven-browser#481]
Please add the Firefox Translations add-on to the AMO list: https://addons.mozilla.org/en-US/firefox/addon/firefox-translations/

**Comment by Bardock88** [comment]
It is a very interesting extension that Mozilla is developing but is in very initial stage.
It is better to wait for a while for her to stay stable and to get on the list, because I tested it and does not work, by the way at the moment only works on the computer. Until then, it is better to continue using Filipe PS's 'Translate Web Pages' and wait for it to release any update for extension as well.

**Comment by interfect** [comment]
I've added this to the list.
