### ISSUE TITLE
[Add-on request] 网费很贵 - 上网时间统计; 终结内容农场

### ISSUE THREAD

**Issue by zhanbao2000** [fork-maintainers/iceraven-browser#482]
[网费很贵 - 上网时间统计](https://addons.mozilla.org/zh-CN/firefox/addon/web%E6%99%82%E9%96%93%E7%B5%B1%E8%A8%88/) is a web browsing time statistics tool.

[终结内容农场](https://addons.mozilla.org/zh-CN/firefox/addon/content-farm-terminator/) is a tool used to filter out content farms in Google search results.

**Comment by interfect** [comment]
I've added these.

It would help slightly if I got links to the en-US AMO instead of the zh-CN one. https://addons.mozilla.org/en-US/firefox/addon/web%E6%99%82%E9%96%93%E7%B5%B1%E8%A8%88/ goes to what appears to be the same add-on as https://addons.mozilla.org/zh-CN/firefox/addon/web%E6%99%82%E9%96%93%E7%B5%B1%E8%A8%88/ but shows the description (if available) and AMO user interface in a language I can read.
