### ISSUE TITLE
Remove trackers if possible.

### ISSUE THREAD

**Issue by person10301** [fork-maintainers/iceraven-browser#496]
![Screenshot_2022-07-31-20-35-04-24_718a221d6c53e9d44e23988b91117061](https://user-images.githubusercontent.com/105549221/182038622-63bbbe03-1755-4826-a9e0-2b82377ca72e.jpg)

**Comment by krypciak-zz** [comment]
Quote from [readme.md](/README.md):
`Right now, we believe that no telemetry should be being sent to Mozilla anymore, but we cannot guarantee this; data may still be sent. Because of the way we have implemented this, the app may still appear to contain trackers when analyzed by tools that look for the presence of known tracking libraries. These detected trackers should actually be non-functional substitutes, many of which are sourced from here`
Your app is possibly reporting false positives.
If you have the skills to actually prove data is being send to these companies, do so.
Else, close this issue.
