### ISSUE TITLE
regarding ad ons

### ISSUE THREAD

**Issue by subham2912D** [fork-maintainers/iceraven-browser#549]
well i currenty iam testing different add ons on browser and adding working add ons my collection can you put my collection of add ons on next update of browser because most of the add ons are not working

**Comment by subham2912D** [comment]
@interfect our goal should be iceraven stable as much as possible . soon update my list you can add my collection on next build account no 17707248 ad on collection name icefec

**Comment by klcb2010** [comment]
You can create your own collection and replace the current one

**Comment by interfect** [comment]
I'd like to be able to add multiple collections so I don't have to be the only one to add add-ons to the default list. But I don't really want to boot things out because they don't *currently* work, because then how is the extension dev going to be able to port their extension and have people use it if it's not on the list?

**Comment by subham2912D** [comment]
Well firefox nighty already support coustom add support . i purpose that iceraven should have two version one is beta version and and another one so called stable version 
in stable version should have only working add ons 
in beta version should include working and non working add ons 
in github who are using beta version iceraven should report working and non working add ons github and only working  add ons added will updated on stable version on every months
