### ISSUE TITLE
[Add-On Request] Indie Wiki Buddy

### ISSUE THREAD

**Issue by cutiexe** [fork-maintainers/iceraven-browser#568]
Indie Wiki Buddy automatically redirects Fandom Wiki (formerly Wikia) links to ad-free, debloated mirrors like BreezeWiki. It has an official Firefox Mobile Beta release here: [](https://getindie.wiki/firefox-mobile/)
The install instructions in that link involve custom add-on collections, and if there's a way to use those in Iceraven then I must have missed it.
Thanks!

**Comment by CharmCityCrab** [comment]
> The install instructions in that link involve custom add-on collections, and if there's a way to use those in Iceraven then I must have missed it. Thanks!

Hamburger menu>Settings>Customize>Set Custom Add-On Collection

There's also an option right above it to Set a Custom Add-On Account.

The only thing is that, if you use them, you may be switching from the default add-on list included in Iceraven and have to use whatever new list you're substituting in it's place.  I haven't tried it, so maybe not, but I'd be prepared for that possibility before messing with it, personally.

Generally, by default, Iceraven is using one pre-installed custom add-on collection for everyone (That way you can add a ton of extensions right out of the box through the normal add-ons interface and don't need to sign up for a Mozilla account and master some sort of a secret code on a nightly or beta version of Firefox to get more than like a dozen of them.  Iceraven is based on stable versions of Firefox, but with more extensions, more options, about:config access, and so on and so forth built-in, and made easier to access where possible.), but because options are an important feature in Iceraven, you do have the ability to switch away from that if you want to.
