### ISSUE TITLE
bypass-paywalls-firefox-clean

### ISSUE THREAD

**Issue by michael1900** [fork-maintainers/iceraven-browser#582]
Hi, how can i install this extension? https://gitlab.com/magnolia1234/bypass-paywalls-firefox-clean

I can't find it in the list and no way to install xpi directly. Please help

**Comment by CharmCityCrab** [comment]
This is kind of a big ask relative to just adding a normal extension that supports Firefox for Android to the default Iceraven list.

Generally, Iceraven is exposing extensions that are sort of hidden away, but still in Mozilla's system, for use in Iceraven.  So, it's not that hard for developers to do- normally.

However, the problem with Bypass Paywalls Clean is that Mozilla doesn't host it anymore in  any way whatsoever, not even hidden away from users of their Firefox branded browsers in a way Iceraven could resurface.

Basically, Mozilla got a legal notice from some copyright holders (Probably the owner of a site with paywalls) saying that the extension was violating their rights in some way and removed it rather than fight it.

The only way Iceraven could let you add it is to, as you said, allow direct installation of .xpi files to the browser.  In the past, Interfect mentioned that it would be a good feature to have, so it's not impossible that they'd do some day, but it would be very labor intensive.  They'd have to design the whole system for loading and installing them from scratch, and then make sure it works with every new browser update from Mozilla that gets folded into Iceraven, and fix it anytime it doesn't.  They might do it at some point, but it's a lot to ask from volunteer developers.

In the meantime, if you use UBlock Origin (or another similar content/ad blocker), and haven't already done so, you can manually add the actual official Bypass Paywalls Clean filter list, and get some of that anti-paywall functionality back on Iceraven today.

Here it is:

https://gitlab.com/magnolia1234/bypass-paywalls-clean-filters/-/blob/main/bpc-paywall-filter.txt

Here is another popular anti-paywall filter list if you want to try using more than one, or prefer this to the other one:

https://raw.githubusercontent.com/liamengland1/miscfilters/master/antipaywall.txt

[Edit: The first filter list doesn't appear to be working right now.  It may have been taken down or be experiencing temporary difficulties.  The second filter list is still available and working, though.]

There are probably more out there as well.

Are they as good as dedicated extensions?  Probably not.  But they work for some stuff.

And there's always a chance that Mozilla will host the extension again (In which case, if it's compatible with their Android browsers, I would assume Iceraven would add it again- Iceraven had it when Mozilla was hosting it) or Iceraven will get a system for allowing sideloading xpi files (Like I said, though, the latter would be a big ask.  Lots of coding to do and potentially a lot of maintenance to do on it as the Fenix project code it has to work with changes).

**Comment by RealFakeGitter** [comment]
Should have read i just made 2 requests one of which was exactly this the other is an official add-on (catcha buster) 
It would be AMAZING though if we could install add-ons manually as you suggested like you can on the desktop versions of both chrome and Firefox to get this addon. Also it would be really cool if it were made possible to install extensions directly from the Mozilla add-on store rather then relying on only the repo provided , I feel like it would also in the long run be easier for developers since all the updates would be running and maintained by mozilla. Just my 2 cents 🙂

**Comment by pidus** [comment]
SmartCookieWeb Preview has xpi side load feature. Maybe Iceraven could copy..

**Comment by aCID-sLAM** [comment]
I know, it isnt a user method but for the people that would like to try,
maybe this could be a temporary solution for the people that have root?

With mixplorer you can access the firefox profile folder. Maybe you could copy or use a altered version of desktop installed and merge it here.

/data/data/io.github.forkmaintainers.iceraven/files/mozilla/YOURProfile

![image](https://github.com/fork-maintainers/iceraven-browser/assets/75371664/cd49c44c-b156-4927-8b49-2882a34396bb)


My first attamt failed. Iceraved complained that the plugin needs new permissions but after browser restart, it was gone again.
Guess i messed up at a certain point, but maybe someone else wants to try.

**Comment by krystian3w** [comment]
Other idea #684

**Comment by akliuxingyuan** [comment]
completed in #702
