### ISSUE TITLE
[Bug]: Iceraven-2.0.3 still  based on fenix v111.0.1

### ISSUE THREAD

**Issue by klcb2010** [fork-maintainers/iceraven-browser#596]
Iceraven-2.0.3 still  based on fenix v111.0.1，Is this an oolong incident? @interfect  @akliuxingyuan 

![截屏图片](https://user-images.githubusercontent.com/32628414/229852434-3abd6cda-04cc-4e8e-a69f-84d8157dd8a0.jpg)
![微信图片_20230405000421](https://user-images.githubusercontent.com/32628414/229852458-16614549-7d74-4fee-864d-0d4b1f201c99.jpg)

**Comment by CharmCityCrab** [comment]
According to the Mozilla website, Firefox 111.0.1 is the most recent stable release of their browser.  So, a fork based on that release is up to date.

You may be basing your expectations of a higher base version number on beta and nightly Firefox releases, or forks of the same, that are offering software for advance testing before finalizing it's form and publishing it for general audiences.

Iceraven bases itself only on stable releases of Firefox in order to be a stable browser itself.  Then it adds in some of it's own Iceraven specific code and customizations and options from other browsers and versions of browsers, and makes them as accessible as possible to those who want to see what their browser can do without having to enter special codes or sign up for a Mozilla account.  The idea is that you get the best of all worlds- a stable browser that also has as much in the way of options, customizations, and expandabilty as the developers have the time and the ability to pack into it. 

Mozilla makes you choose between unstable versions of it's Firefox browser that offer more choices than it's stable versions, or stable versions that offer fewer choices than it's unstable versions.  Iceraven takes the stable Firefox and the choices together- best of both worlds- and more, because Iceraven also does some things that no version of Firefox does. :)

Being based on the stable version of Firefox is an intentional feature, not a bug.  They're keeping the browser useable and accessible, but also including all sorts of options and such for power users rather than neutering it.

**Comment by klcb2010** [comment]
> 

Did you notice what he said"As you known, mozilla-mobile/fenix moves to a monorepo mozilla-mobile/firefox-android, I tried using git trick to maintain the current structure and it seems successful, but it may not be feasible in the future, anyway, this release based on fenix v111.1.1 and I bump the major version 😆

The default branch should change to iceraven, but I don't have enough permission to change repo settings, I email to @interfect to acquire for owner role, waiting for his reply" .You need to know Firefox 111.1.1 is the  recent stable release .
![Screenshot_2023-04-05-09-17-15-317_com dv adm](https://user-images.githubusercontent.com/32628414/229956782-20d3c2ee-0211-46d3-8f7b-9bdd5e0242af.jpg)

**Comment by akliuxingyuan** [comment]
@klcb2010 what I said based on v111.1.1 which is the latest fenix release tag https://github.com/mozilla-mobile/firefox-android/commits/fenix-v111.1.1
and the 111.0.1 in your picture is GeckoView version, if you also installed the firefox, you will find it's same

**Comment by klcb2010** [comment]
> @klcb2010 what I said based on v111.1.1 which is the latest fenix release tag https://github.com/mozilla-mobile/firefox-android/commits/fenix-v111.1.1 and the 111.0.1 in your picture is GeckoView version, if you also installed the firefox, you will find it's same

 get it ，thank you for your hard work
