### ISSUE TITLE
Images cannot be saved on some sites

### ISSUE THREAD

**Issue by gemeinsame** [fork-maintainers/iceraven-browser#599]
Images cannot be downloaded on some sites such as https://www.pixiv.net/. The browser displays a message indicating that the download fails.
 The Firefox version is Iceraven-2.0.3

**Comment by klcb2010** [comment]
她禁止下载 与浏览器无关

**Comment by gemeinsame** [comment]
> 

但是她在其他浏览器可以正常保存

**Comment by klcb2010** [comment]
> > 
> 
> 但是她在其他浏览器可以正常保存

403 禁止访问  其他浏览器如果能下载应该是缓存而不是原图
![Screenshot_2023-04-15-17-09-01-705_com dv adm](https://user-images.githubusercontent.com/32628414/232203248-ba77f797-f14d-4479-8ad4-24ac4685e015.jpg)

**Comment by akliuxingyuan** [comment]
upstream affected
https://github.com/mozilla-mobile/fenix/issues/17716
https://bugzilla.mozilla.org/show_bug.cgi?id=1690037

**Comment by seniordevel** [comment]
Well this needs to be fixed by Mozilla.
Seems they are on the right way.

At least I could reproduce, that a missing referrer results in a 403 Forbidden error.

![IMG_20230417_203038_674](https://user-images.githubusercontent.com/129897917/232589064-bd097367-93b9-41d7-b3eb-ba6b47dc0a58.jpg)
![IMG_20230417_210059_555](https://user-images.githubusercontent.com/129897917/232589349-9c8dfd13-e91f-450e-bc25-21009d4d97c2.jpg)

**Comment by gemeinsame** [comment]
OK, it seems that we need to wait for Mozilla to fix it.
