### ISSUE TITLE
Allow old-Fenix-style tab switcher integrated into home/new tab page

### ISSUE THREAD

**Issue by Atemu** [fork-maintainers/iceraven-browser#62]
### What is the user problem or growth opportunity you want to see solved?

Fenix initially had a very nice to tab switcher that was integrated into the home screen/new tab page. Later it was replaced with the current popup one that looks kind of out of place for a main component of the browse and is clunky to use.

Our modification to the new one are nice (especially the bottom buttons) but I still prefer the old one. My opinion is not the only one of course, so it'd be better to have it as an option (related: #56).

Perhaps you wouldn't even have to disable the current tab switcher as the old one was simply integrated into the home page but I'd have to investigate further. It might be as simple as bringing back the tab switching functionality to the home page and making the switch tab button take you there instead of opening the new popup.

### How do you know that this problem exists today? Why is this important?

People like me want sleek tab switchers that integrate well with the rest of the browser, not the opposite. They'd especially like to be given the option when a ~~worse~~radically different UX is introduced.

On top of that, the home page is nearly useless to me nowadays; it exists solely as a menu for collections which I have no use for.

### Who will benefit from it?

Everyone who liked the old Fenix tab overview.

**Comment by CharmCityCrab** [comment]
While I am all for as many users options and configurations as possible, *if* only one configuration can be maintained, I would argue for the Fennec style solution that is unique to IceWeasel.

I based that preference on a few factors:

1. I see posts on Reddit and elsewhere bemoaning Firefox's new tab system. Since IceWeasel switched to a model closer to the old Fennec Firefox's tab system, I have been able to recommend, to the extent allowed by moderation and trying to be respectful of whatever sub I am on, this browser as one potential alternative that allows the user to  stay in the Gecko ecosystem but have the tab layout they want, and I think it generally has been received positively.

Though I realize that one can't necessarily take Internet opinion, especially anctedoal observation of such by one person as they recall it, as an actual rock solid truth about wider opinions, my sense is that we attract more users than we repel with the current Fennec style system- by a huge margin.

In fact, someone asked what Fenix might look like with the Fennec style system, and I posted a picture of this browser, and it got a lot of upvotes when presented as a less labeled choice (i.e. Not Firefox or IceWeasel, here is a second way Fenix tabs could work).

2. Since the users who prefer Firefox's system of tabs' needs, in respect to tab layout, are being met within the Gecko ecosystem by Firefox already, it makes sense to meet the needs of the people whom without this browser would not have their needs met within the Gecko system at all by keeping Fennec style tabs.  Of course, some folks are here for more than tabs and really want their Firefox style tabs with IceWeasel functionality and if we can maintain both tab styles, great.  I am not opposed to Firefox-Fennec style tabs at all *as an option*,  I just support Fennec-style (ala IceWeasel style currently) style tabs if it has to be one or other.

3. Though for maintenance purposes, I realize it is logical and probably necessary to stay close to upstream, IceWeasel is, by its nature, an alternative to Firefox.  If there is a roughly equally valid and liked set of two ways to do things, I would suggest that it helps IceWeasel (or IceRaven's) brand identity to pick the option Firefox doesn't pick, so that we won't have two mostly identical browsers and so that between the two browsers, IW is enabling people (Even the ones who don't choose IW) to have more *overall* choices that have a variety of distinctions within the limitations of staying as close to upstream as is needed for maintenance and updates.

So, if a Firefox style option for tabbing is revived (Which I am not opposed to unless it precludes keeping the current IceWeasel system as well- options are good), I would suggest that Fennec style tabs be the default and that Firefox style tabs be the option that can be switched on by the individual user if desired. It gives IW a more distinct look "out of the box" to make the different look the default, while still serving the user who may want the Firefox look in that respect.

4. I actually think the designer who came up with IceWeasel's Fennec-style tabs' implementation did some beautiful work.  They look better in IceWeasel than they ever looked in Fennec, despite being in essence the same.  Maybe that's just what happens when you do tabs Fennec-style on Fenix with a dark theme and the surrounding Fenix stuff, but, still, beautiful, which is certainly not a bad side effect for a feature that would be implemented anyway to have!  Definitely a plus if something that does something people want also happens to look good. :)

So, if there is a Firefox style option for tabbing (Which I am not opposed to unless it precludes keeping the current IceWeasel system- options are good), I would suggest that Fennec style tabs be the default and that Firefox style tabs be the option that can be switched on by the individual user if desired.  It gives IW a more distinct look "out of the box" to make the different look the default, while still serving the user who may want the Firefox look in that respect.

**Comment by miDeb** [comment]
I think I agree with what @CharmCityCrab wrote, I just want to highlight the importance of customization. Not _everyone_ wants _everything_ to be different. I think one approach could be to always support a baseline configuration where IW looks exactly like fenix (not as the default obviously), so that users can choose exactly what they want to change, but keep stuff they like.

**Comment by ghost** [comment]
I agree with Atemu. Bring back the Fenix one. The one on here now is ugly and weird looking

**Comment by Atemu** [comment]
Just to clarify, I don't mean the current/new (Mozilla) Fenix tab menu UX, I mean the old one that Mozilla had before and Fenix initially came with when it first came out as Preview.

The old UX I mean (tabs integrated in the home screen):

![Screenshot_20200903-232552_Firefox_Preview](https://user-images.githubusercontent.com/18599032/92175928-cbedda80-ee3d-11ea-9da4-c6eff1cec9d9.png)

The one I don't mean (tabs as a popup menu):

![Screenshot_20200903-232911_Firefox_Nightly](https://user-images.githubusercontent.com/18599032/92175932-cd1f0780-ee3d-11ea-9cfe-f175fd7e93f4.png)

This one would also be cool to have as an option but that's not the scope of this issue.

**Comment by abhijitvalluri** [comment]
Hi all! Thanks for all the opinions. @CharmCityCrab, I am glad you like the new Fennec style tabs tray layout. And speaking of customization options, I just implemented a massive update to the Tabs tray customization in #65! 

The customization options now allow you to configure pretty much everything in that UI and you can even set it up to look the same way as the official Fenix layout (with the addition of site favicons!). 

Actually, I ended up deciding to make the default configuration look like the official Fenix one, so that users switching from that browser will have minimal disruption, which is contrary to what @CharmCityCrab suggested (i.e. make the default look of IceWeasel/whatever-we-will-eventually-call-it different from Fenix). But if most people think it makes sense to do it the other way, then I can make the old Fennec style the default.

Also, @Atemu, unfortunately bringing back the old Fenix style (tabs integrated in the home screen) can be very challenging and also potentially incompatible with upstream changes (it can cause lots of merge conflicts with any further changes that upstream does to the Home screen). So, I cannot promise to be able to recreate that in this fork. 

It *may* be doable by looking at the old commits and the commits that removed the old layout in favor of the new pop-up tab style, and seeing how we can re-add the old style. But it might take a lot of effort and I am not sure I have the time.

**Comment by abhijitvalluri** [comment]
I need to vent a little bit somewhere. There is an issue on the official Fenix repo (https://github.com/mozilla-mobile/fenix/issues/13098) requesting Fennec style compact tabs similar to what I implemented here (especially in #65). I posted an update with the latest UI changes and put loads of screenshots (https://github.com/mozilla-mobile/fenix/issues/13098#issuecomment-686825271) comparing the old Fennec browser with the new Fenix browser and also my modified layout from this fork.

The screenshots clearly show my modified layout is as good as the old Fennec layout in terms of compactness. Both show the same number of tabs in portrait and landscape mode. In portrait mode they show a little more than official Fenix layout, and in landscape mode the benefit is even more clear and you can see a lot more tabs in the new modified layout compared to the official Fenix layout. And it is the same as the old Fennec.

Despite my comment being very much on topic for the discussion and feature request, it gets marked as off-topic. What is worse is some developer who is a contributor for the Fenix project goes ahead and comments that my screenshots show that my modified layout is not compact at all (https://github.com/mozilla-mobile/fenix/issues/13098#issuecomment-686916529) and says that there is no benefit at all to my new layout and in fact states that it only has disadvantages!! Despite my screenshots making it glaringly obvious that my modified layout is indeed more compact than official Fenix layout and it is even more so in landscape mode and on screen sizes big enough to put more than 2 tabs in a row! I do not understand why this person chooses to purposefully ignore the reality shown in the screenshots and misrepresent them. I mean how could that person have come to that completely wrong conclusion when my screenshots give visual proof that my layout is compact?

And now Mozilla marked most of this discussion as off-topic and restricted conversation to only collaborators making it impossible for me to reply to that post and disagree with the wrong conclusion.

Anyway, I really do not care what anyone thinks of my layout. I just wanted to comment that I totally disagree with their conclusion. Regardless of whether they think my layout is inferior or has more disadvantages, I find it vastly superior and I shall continue to use it exclusively! 😉 

If Firefox devs continue to be adamant that their approach is the best they will continue to get 1 star reviews on Google Play Store and will lose what little userbase they have left! If they continue to ignore user requests/opinions, if they continue to ignore suggestions and implementations for alternate approaches, and think that their approach is the best and not implement features that the old browser had, then they will be left with a vastly inferior browser, at most a clone of the Chrome browser (with a different engine) and they will ruin the good reputation of Firefox and lose all their userbase!

They keep digging a hole for themselves!

**Comment by miDeb** [comment]
@abhijitvalluri yeah, your grid layout is probably the main selling point of this fork

**Comment by Atemu** [comment]
In portrait mode it doesn't help much honestly but in landscape mode it makes a huge difference.

Please find another place though as this issue is only tangentially related to tiled vs split tabs, if it all, and there already is enough noise in here.

**Comment by abhijitvalluri** [comment]
I understand. I won't trouble this topic with further discussions.

**Comment by interfect** [comment]
I've retitled the issue to capture what I think is wanted here. I think it would be a good idea to have.

Sorry Mozilla didn't want to hear about all your hard work @abhijitvalluri. I definitely appreciate it.

**Comment by akliuxingyuan** [comment]
@Atemu Fenix upstream already have grid layout, so I closed this issue
