### ISSUE TITLE
[Bug] Fullscreen out of bounds

### ISSUE THREAD

**Issue by mackeev** [fork-maintainers/iceraven-browser#66]
Streaming videos on 
http://livetv.ru/allupcoming
are out of bounds in Fullscreen mode.
I checked them via the latest Nightly and they're fine there.

**Comment by interfect** [comment]
We should pull in Mozilla's code and see if that helps.

Is this issue present in Mozilla Firefox? Because while we follow a lot of Mozilla Nightly stuff in the browser app, the actual rendering engine is the normal release one.

**Comment by mackeev** [comment]
Fine in 68
Same issue in 80

**Comment by interfect** [comment]
OK, I checked and I also see this affecting Android Mozilla Firefox 80.1.2, the current release version, as well as us. I suspect that it's a GeckoView/android-components problem that is fixed in the nightly version of the browser engine but that hasn't yet made its way to the stable Gecko that Iceweasel ships.

I could try and run off a nightly-flavored Iceweasel, I suppose, but we probably don't want to use that for most users/sites because it could have more regressions.

**Comment by mackeev** [comment]
Fixed in 1.1
