### ISSUE TITLE
[REQUEST] Fix YouTube

### ISSUE THREAD

**Issue by Soheil777** [fork-maintainers/iceraven-browser#676]
please fix the ads problem on YouTube site
also just we activate desktop from we can turn off the mobile screen and listen to the video

**Comment by CharmCityCrab** [comment]
Just FYI:

Recent issues with YouTube originate with YouTube.  They are getting more aggressive about blocking users with ad-blockers enabled in novel ways.

The solution is probably going to have to come from the ad-blocking extensions themselves.  It's going to be a cat and mouse game for a while where Google (Which owns YouTube) tries to block them and they try to unblock themselves so they can block the ads, and then Google tries to block them again with a new method to force users to view ads, which leads the ad and content blocking extensions like uBlock Origin to try to unblock themselves on the site so they can block ads on it again...  Well, you see where that was going. :)

Right now, YouTube mostly works for me on Iceraven using uBlock Origin.  When I go directly to the main YouTube URL, it shows a black screen with a nag to turn on my viewing history (Which is the other thing Google has been trying to push users towards recently).  However, there is a search box on the main page that lets me look for any video I want, and links to videos all work for me.  It's just that I don't get the main page stuff anymore, which, to be honest, were not things I generally clicked on anyway.

If you don't use uBlock Origin, you might want to give it a try (Hamburger menu>Add-Ons>Click the 
+" sign next to uBlock Origin.  Then restart your browser.).

If you already do use uBO, you might want to try purging the extension cache and reloading the filter lists once or twice a day if you have problems (Yes, Google is literally re-blocking them twice a day sometimes, and uBO is issuing fixes at the same rate).

I would try turning on all the filter lists it includes by default, except for the regional and language related ones for sites that you don't visit (i.e. If you never read websites from Spain, there's no need to add regional filters for that country- it'll just slow down your browser without helping any, because all of those filters only apply to Spain's sites, which you don't [hypothetically in this example] visit).

I also have 19 custom filter lists that I manually put in the URLs for (Well, 18 right now.  The 19th one messes with my fantasy (American) football league's site, so I turn it off that one filter list in-season each year) in addition to the included ones already turned on or that you can enable within the extension easily because they're listed.  The ones already listed in the extension are fine for a newbie to ad-blockers or people who just don't want to mess with anything complicated.  If either of those describe you, you might not want to add any custom lists right now, because they can break things and make it hard for anyone to figure out what's up and suggest a fix if something goes wrong (I think the people behind uBO generally recommend that people not use a bunch of custom lists from random URLs on the web, but they keep the feature for people who want it).  I also add my own filters using their picker tool, but, fair warning, those type of features can break things sometimes, so they may not be for people new to ad-block or who don't feel like messing with extra stuff.

Here's the latest weekly uBlock Origin thread about the YouTube situation for the week of October 16, 20232 (Posted by the developers of uBO to Reddit):

https://www.reddit.com/r/uBlockOrigin/comments/178yasm/youtube_antiadblock_and_ads_october_16_2023/

Here's the uBO sub-reddit in general:

https://www.reddit.com/r/uBlockOrigin/

My guess is that some other ad-blockers like Ad-Guard Ad-Blocker and Ad-Blocker Ultimate, both available for Iceraven (Just as uBO is), are also working on this issue as well (I wouldn't recommend using more than one ad or content blocker at a time on the same browser installation, though.).

If this goes on too long, someone may try an extension that auto-redirects YouTube URLs to some sort of copycat site with the same videos, but that doesn't block ad-blockers, hosted in a country that doesn't have strict copyright laws and won't extradite. :)  I think there is already some motion in that direction.  However, it's not ideal, because, in addition to potential legal entanglements for the hypothetical secondary host of the videos, it also could be a security issue for users (i.e. Being redirected to some random potentially sketchy website to watch videos).  So, I think most people are sticking with uBO or their favorite ad-blocker and seeing who blinks first- the ad-blockers or Google/YouTube.

Last I heard, YouTube was doing A/B testing, meaning some people get one version of the site, and others get another.  In this case, they may be blocking ad-block use for some users and not for others, so they can look at the random people they've blocked ad-blockers for and see what percentage of people turn off ad block to keep viewing and what percentage of people just stop visiting YouTube, before deciding whether to implement it for everyone else or not.

Anyhow, point being- I don't think this is a solution that will come from the browsers- any browser, really.  Some browsers with built-in ad-blockers may seem to be addressing their issue, but they are likely just making adjustments to their built in ad-blockers.  Browsers without or with minimalist ad-blockers may seem to not be taking action, but really it's just that if ad-blockers are extensions rather than built-in, it's the ad-blocker people who make the changes, not the browser people, so both really involve ad-blockers being adjusted to beat Google's latest shenanigans, at least until Google changes things again.

I'm not saying that it's impossible that a browser like Iceraven could come up with a solution to this issue.  It's just that the real issue seems to be between the content-blockers and Google/YouTube.  Those are sort of the entities sort of fighting the battle on the front lines who ultimately will probably either prevail or give up.


Side note:

The OP mentioned wanting to listen to audio from videos while other tabs or apps are in the foreground.  Iceraven has an extension called "Video Background Play Fix." that lets you do that automatically without enabling desktop mode or anything.  The only caveat is that YouTube (or where ever) has to let you play the video in the first place.  If it does, the extension works very well.

Another helpful extension for viewing YouTube on Iceraven is "Sponsor Block".  Again, you've got to get to the point where YouTube allows you to view it's videos, but if you can figure that out or an update to a content-blocker (aka an ad-blocker) extension fixes it for you, "SponsorBlock" is good at letting you skip over parts of videos where people are plugging their sponsors or promoting their other content or something, as long as someone using the extension has seen the video before you and marked the appropriate passages.  So, it doesn't work with everything right away, but it sort of tries to block the ads that aren't clearly ads (i.e. When the host is verbally basically doing advertising, which wouldn't get picked up by traditional ad-blockers looking for traditional ads that don't involve the human host of a video just continuing to talk from content to ad to content.).  So, that's a good one to add if you use YouTube a lot.  It also can work hand in hand with a traditional ad-blocker like uBO, because they are trying to do different things different ways and shouldn't wind up fighting each other the way two content blockers enabled in the same browser can do.

**Comment by Soheil777** [comment]
Thank you so much for your very complete and comprehensive explanation
But I don't think you are the creator of the app
Because even without the plugin, in this app, you can also listen to the sound in desktop mode,
but as i said the desktop mode must be active, and I don't understand why?

about ads, you're right google pushes it hard.  i use ad-guard 
Do you think uBO is a better option? i can test it
i love Iceraven and always recommend To my friends who use YouTube a lot because you can turn off your screen and just listen, this is extremely useful when you see the news 
I hope we can use this ability without activating the desktop option
and i hope Iceraven creator May it continue its work with all its strength and releases new versions
We really need a browser like that in Android OS
sorry my English is not well i hope you understand what i mean

**Comment by richie3011** [comment]
> Thank you so much for your very complete and comprehensive explanation But I don't think you are the creator of the app Because even without the plugin, in this app, you can also listen to the sound in desktop mode, but as i said the desktop mode must be active, and I don't understand why?
> 
> about ads, you're right google pushes it hard. i use ad-guard Do you think uBO is a better option? i can test it i love Iceraven and always recommend To my friends who use YouTube a lot because you can turn off your screen and just listen, this is extremely useful when you see the news I hope we can use this ability without activating the desktop option and i hope Iceraven creator May it continue its work with all its strength and releases new versions We really need a browser like that in Android OS sorry my English is not well i hope you understand what i mean

Both AdGuard and uBO are same. When you see you have to force filter update manually. If you use uBlock Origin you can report YouTube issue here:https://github.com/uBlockOrigin/uAssets/issues/19976

**Comment by daffydock** [comment]
uBlock is superior to Adguard or Adblock, et al. Since you can block specific scripts/elements on YouTube from running. Nothing to do with filter lists. 

uBlock is a lot more than just an adblocker. You can literally stop the script/pop up that runs, telling you to disable the ad-blocker from running on YouTube. Thus YT runs normally. At least for now. 

As far as having an extension that automatically redirects YT links to say, Invidious or Piped instances, that already exists. It is called LibRedirect and I have been using it since early 2022. It's great. As it works with other services/sites. 

If YT is the main issue, OP can just use Newpipe W/ Sponsorblock. Import his subs there and not deal with YT shenanigans at all.

**Comment by akliuxingyuan** [comment]
closed in #689
