### ISSUE TITLE
Firefox 119 Beta or Nightly allowed install addons from PC "path"

### ISSUE THREAD

**Issue by krystian3w** [fork-maintainers/iceraven-browser#684]
Based on this "notification" https://github.com/fork-maintainers/iceraven-browser/issues/304, I can install the add-on from the PC "platform" in Firefox 119 Beta or Nightly.

So instead of building a long collection on someone else's account, how about copying the Firefox Beta/Nightly some code to IceRaven? It could be removed as if the stable version no longer uses it and the number of compatible add-ons with Android has significantly increased (there are still some incompatible ones like https://github.com/jscher2000/dont-accept-webp).

**Comment by krystian3w** [comment]
https://github.com/fork-maintainers/iceraven-browser/issues/591

**Comment by akliuxingyuan** [comment]
yes, finally we can install more desktop version extensions, according to https://blog.mozilla.org/addons/2023/11/01/is-your-extension-ready-for-firefox-for-android/, it will land release v120 (November 21)

**Comment by CharmCityCrab** [comment]
Could we slow down the guy spamming every other thread he can find that vaguely relates with "Other ideas, see #684"?   I'm subscribed to the issues section via email, and it feels like I periodically get a dozen of these things at a time from the same person.  My phone goes off like it's the end of the world. :)

It's not that the issue is without merit, it's that this is a small project and everyone who follows issues knows about this one.  Sure, add it to one or two closely related things, but not 75.

Anyway, I think it's obvious that when Firefox *stable* adopts it's new extensions format, obviously that's an update we'll want to get included in Iceraven ASAP, because I would imagine Mozilla will drop the existing extensions library soon after (They haven't announced that, but it's logical).

One of the developers should probably test a non-public build of Iceraven to see what happens when the current format of extensions converts to the new format and whether or not people's existing extensions and extension settings carry over.  That testing could be done with some beta or nightly Firefox code.

I tend to be against the idea of adopting beta or unstable code to work this new thing in to an actual release, though, when it's supposedly going to stable early in the new year anyway, hopefully with some of the kinks worked out.  Obviously, that would change if the existing extensions servers/infrastructure are taken down by Mozilla first and might merit an emergency update to the new thing regardless of stability, because extensions have always been big for Iceraven users.  But if the current system keeps working, my feeling is why not ride it out until the new system is ready for (stable) primetime?

I understand because of the importance of extensions to the Iceraven user base, we don't want an extensions gap, which might force an early switch.  However, at this point, there are still more extensions available the way we're doing things than the new experimental format extensions, right?

**Comment by krystian3w** [comment]
I don't think everyone would activate a subscription to every request to add to the collection, some may have uninstalled the browser due not adding it to the collection for more than 12 months.

**Comment by Candlemass** [comment]
> I don't think everyone would activate a subscription to every request to add to the collection, some may have uninstalled the browser due not adding it to the collection for more than 12 months.

Yup.

I uninstalled months ago since without extension support the browser doesn't meet my needs after mozilla in all their infinite wisdom broke "legacy" extensions yet again requiring a rewrite for the what, 4th time in less than a decade?...

However, I have no idea why the dev of this project would ask for extension requests on the main page of the repo if they had no intension of ever adding them to the collection. The only purpose that served was to waste users time... Maybe I will give it another shot if/when iceraven is updated but the project thus far hasn't projected much confidence.

**Comment by mzso** [comment]
So what is the state of affairs now? I though with the Fenix 119 basis we would be able to install any addon from addons.mozilla.org, instead of relying on some collection.

**Comment by Candlemass** [comment]
> So what is the state of affairs now? I though with the Fenix 119 basis we would be able to install any addon from addons.mozilla.org, instead of relying on some collection.

Who knows?

As I mentioned above the dev clearly isn't very active or forthcoming. There are literally hudreds of problem/bug reports that have gone without a response.

**Comment by ascendbeing** [comment]
> > So what is the state of affairs now? I though with the Fenix 119 basis we would be able to install any addon from addons.mozilla.org, instead of relying on some collection.
> 
> Who knows?
> 
> As I mentioned above the dev clearly isn't very active or forthcoming. There are literally hudreds of problem/bug reports that have gone without a response

bit unfair. for whateva reason the main dev passed most of the torch to some other dude. this other dude probably isn't super responsive in particular to the older proposals, because although they appear to be from this community in a sense, they may not be familiar with the long-standing issues or prs from prior to when they were given release permission for this repo.

the majority of the time, was developer 1. developer 2 came to this project at most 1.5yr ago. I think it's been a year or less that developer 2 took on most of the work here. they have different styles. I get the impression the first developer may have been better at interfacing with the community in certain respects, but had to step away, and rather than leave us with nothing, had the goodwill to put in someone who's at least capable of performing, putting out releases pretty regularly, just maybe isnt fully read in on every person's concerns

**Comment by Candlemass** [comment]
> > > So what is the state of affairs now? I though with the Fenix 119 basis we would be able to install any addon from addons.mozilla.org, instead of relying on some collection.
> > 
> > 
> > Who knows?
> > As I mentioned above the dev clearly isn't very active or forthcoming. There are literally hudreds of problem/bug reports that have gone without a response
> 
> bit unfair. for whateva reason the main dev passed most of the torch to some other dude. this other dude probably isn't super responsive in particular to the older proposals, because although they appear to be from this community in a sense, they may not be familiar with the long-standing issues or prs from prior to when they were given release permission for this repo.
> 
> the majority of the time, was developer 1. developer 2 came to this project at most 1.5yr ago. I think it's been a year or less that developer 2 took on most of the work here. they have different styles. I get the impression the first developer may have been better at interfacing with the community in certain respects, but had to step away, and rather than leave us with nothing, had the goodwill to put in someone who's at least capable of performing, putting out releases pretty regularly, just maybe isnt fully read in on every person's concerns

Sure.

But that still doesn't address this question or explain what the plan is moving forward. This is clearly the biggest need by many and we are all still being left in the dark.

**Comment by ascendbeing** [comment]
I think we both agree. to summarize: with this Firefox 120 release coming next month, and given its particular feature set, it's going to be difficult to drum up any further interest in this project. So you and many others are rightfully concerned that you may want to see this project continue, but with no response or assurances whatsoever (I'll take your word for it), it appears that the development team is missing the last chance to garner any additional interest in this project.

the worst part imo is that this news, of fx120 letting you use actual add-ons, won't get around to everyone, so you'll have a contingent of users here, possibly just as frustrated, yet not realizing that there may be, at that point, other options.

**Comment by Candlemass** [comment]
> I think we both agree. to summarize: with this Firefox 120 release coming next month, and given its particular feature set, it's going to be difficult to drum up any further interest in this project. So you and many others are rightfully concerned that you may want to see this project continue, but with no response or assurances whatsoever (I'll take your word for it), it appears that the development team is missing the last chance to garner any additional interest in this project.
> 
> the worst part imo is that this news, of fx120 letting you use actual add-ons, won't get around to everyone, so you'll have a contingent of users here, possibly just as frustrated, yet not realizing that there may be, at that point, other options.

Well there's still the problem of mozilla dumbing down the main branch by hiding the "under the hood" settings of the about:config menu. Iceraven was supposed to essentially have feature  parity with the desktop version based on the projects initial direction.

Where things are now is a mystery because apparently basic communication and fulfilling mission statements is difficult for some...

**Comment by akliuxingyuan** [comment]
> So what is the state of affairs now? I though with the Fenix 119 basis we would be able to install any addon from addons.mozilla.org, instead of relying on some collection.

first, having add-on collection doesn't conflict with installing add-on from AMO site, the former is more convenient for general users, for the latter not every add-on is android compatible, and you may need to turn on desktop mode to install some add-ons, for example https://addons.mozilla.org/en-US/firefox/addon/get-tech-stack/

> However, I have no idea why the dev of this project would ask for extension requests on the main page of the repo if they had no intension of ever adding them to the collection. The only purpose that served was to waste users time... Maybe I will give iceraven another try if/when it is updated but the project thus far hasn't inspired much confidence.

https://github.com/fork-maintainers/iceraven-browser/blob/aa94a4e418d6132cfb3fb33c1cf6912f681b213b/app/build.gradle#L189-L190

Iceraven's default add-on collection belongs to @interfect, I have no permission to add new add-ons, I thought @interfect  will deal with the [add-on request] issues, but I take a glance on the collection [What-I-want-on-Fenix](https://addons.mozilla.org/en-US/firefox/collections/16201230/What-I-want-on-Fenix/), its last update time is Jul 11, 2022. I will email him about this, hope he can make some progress on it, or we take the last option: create a new add-on collection.

And the last, I will still maintain this project, and in the meantime we need more Android developers!!

**Comment by ascendbeing** [comment]
> > So what is the state of affairs now? I though with the Fenix 119 basis we would be able to install any addon from addons.mozilla.org, instead of relying on some collection.
> 
> first, having add-on collection doesn't conflict with installing add-on from AMO site, the former is more convenient for general users, for the latter not every add-on is android compatible, and you may need to turn on desktop mode to install some add-ons, for example https://addons.mozilla.org/en-US/firefox/addon/get-tech-stack/
> 
> > However, I have no idea why the dev of this project would ask for extension requests on the main page of the repo if they had no intension of ever adding them to the collection. The only purpose that served was to waste users time... Maybe I will give iceraven another try if/when it is updated but the project thus far hasn't inspired much confidence.
> 
> https://github.com/fork-maintainers/iceraven-browser/blob/aa94a4e418d6132cfb3fb33c1cf6912f681b213b/app/build.gradle#L189-L190
> 
> Iceraven's default add-on collection belongs to @interfect, I have no permission to add new add-ons, I thought @interfect will deal with the [add-on request] issues, but I take a glance on the collection [What-I-want-on-Fenix](https://addons.mozilla.org/en-US/firefox/collections/16201230/What-I-want-on-Fenix/), its last update time is Jul 11, 2022. I will email him about this, hope he can make some progress on it, or we take the last option: create a new add-on collection.
> 
> And the last, I will still maintain this project, and in the meantime we need more Android developers!!

I think regarding the first part, that 120 is out for desktop but when I wrote that last reply, it wasn't out yet for Android.
I am glad you are still on this but from what I gathered in my summary above, it appears that next month, which means probably 120 android version or 121, they will be basically rolling out an AMO policy that add-ons are intended to work on both desktop and mobile, as far as add-ons that appear on AMO.
is there a catch to that? probably. there usually is. like you said, it could mean they lurch down the path of disabling useful API access bc "that API isn't compatible with mobile so efya!"
if that is what happens, I guarantee most or at least a lot of us will continue to come back here, so thank ya for ya work and ye, mo devs would be cool fashir.
the cynical view is that they would be working toward that lowest common denominator because it's the road to building a web that is manifest v2 only which means trusted-only, no useful usable apis, etc.
so if I cast it like it's a sure thing there's no point in any of this I'm sorry, that's not how I feel at all. I am like you very very suspicious toward these on the surface "welcome" appearing changes.

**Comment by interfect** [comment]
I haven't touched the addon collection in a long time. If someone wants to
swap it out for a new default go right ahead. I was just adding anything
anyone asked for; the real solution is UI and backend machinery to just let
people pick extensions. Which I think is supposed to come from Mozilla
quite soon.

On Saturday, November 25, 2023, ascendbeing ***@***.***>
wrote:
> So what is the state of affairs now? I though with the Fenix 119 basis we
would be able to install any addon from addons.mozilla.org, instead of
relying on some collection.
>
> first, having add-on collection doesn't conflict with installing add-on
from AMO site, the former is more convenient for general users, for the
latter not every add-on is android compatible, and you may need to turn on
desktop mode to install some add-ons, for example
https://addons.mozilla.org/en-US/firefox/addon/get-tech-stack/
>
> However, I have no idea why the dev of this project would ask for
extension requests on the main page of the repo if they had no intension of
ever adding them to the collection. The only purpose that served was to
waste users time... Maybe I will give iceraven another try if/when it is
updated but the project thus far hasn't inspired much confidence.
>
>
https://github.com/fork-maintainers/iceraven-browser/blob/aa94a4e418d6132cfb3fb33c1cf6912f681b213b/app/build.gradle#L189-L190
>
> Iceraven's default add-on collection belongs to @interfect, I have no
permission to add new add-ons, I thought @interfect will deal with the
[add-on request] issues, but I take a glance on the collection
What-I-want-on-Fenix, its last update time is Jul 11, 2022. I will email
him about this, hope he can make some progress on it, or we take the last
option: create a new add-on collection.
>
> And the last, I will still maintain this project, and in the meantime we
need more Android developers!!
>
> I think regarding the first part, that 120 is out for desktop but when I
wrote that last reply, it wasn't out yet for Android.
> I am glad you are still on this but from what I gathered in my summary
above, it appears that next month, which means probably 120 android version
or 121, they will be basically rolling out an AMO policy that add-ons are
intended to work on both desktop and mobile, as far as add-ons that appear
on AMO.
> is there a catch to that? probably. there usually is. like you said, it
could mean they lurch down the path of disabling useful API access bc "that
API isn't compatible with mobile so efya!"
> if that is what happens, I guarantee most or at least a lot of us will
continue to come back here, so thank ya for ya work and ye, mo devs would
be cool fashir.
> the cynical view is that they would be working toward that lowest common
denominator because it's the road to building a web that is manifest v2
only which means trusted-only, no useful usable apis, etc.
> so if I cast it like it's a sure thing there's no point in any of this
I'm sorry, that's not how I feel at all. I am like you very very suspicious
toward these on the surface "welcome" appearing changes.
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by ascendbeing** [comment]
> I haven't touched the addon collection in a long time. If someone wants to swap it out for a new default go right ahead. I was just adding anything anyone asked for; the real solution is UI and backend machinery to just let people pick extensions. Which I think is supposed to come from Mozilla quite soon.
> On Saturday, November 25, 2023, ascendbeing ***@***.***> wrote: So what is the state of affairs now? I though with the Fenix 119 basis we
> would be able to install any addon from addons.mozilla.org, instead of relying on some collection.
> first, having add-on collection doesn't conflict with installing add-on
> from AMO site, the former is more convenient for general users, for the latter not every add-on is android compatible, and you may need to turn on desktop mode to install some add-ons, for example https://addons.mozilla.org/en-US/firefox/addon/get-tech-stack/
> However, I have no idea why the dev of this project would ask for
> extension requests on the main page of the repo if they had no intension of ever adding them to the collection. The only purpose that served was to waste users time... Maybe I will give iceraven another try if/when it is updated but the project thus far hasn't inspired much confidence.
> https://github.com/fork-maintainers/iceraven-browser/blob/aa94a4e418d6132cfb3fb33c1cf6912f681b213b/app/build.gradle#L189-L190
> Iceraven's default add-on collection belongs to @interfect, I have no
> permission to add new add-ons, I thought @interfect will deal with the [add-on request] issues, but I take a glance on the collection What-I-want-on-Fenix, its last update time is Jul 11, 2022. I will email him about this, hope he can make some progress on it, or we take the last option: create a new add-on collection.
> And the last, I will still maintain this project, and in the meantime we
> need more Android developers!!
> I think regarding the first part, that 120 is out for desktop but when I
> wrote that last reply, it wasn't out yet for Android.
> I am glad you are still on this but from what I gathered in my summary
> above, it appears that next month, which means probably 120 android version or 121, they will be basically rolling out an AMO policy that add-ons are intended to work on both desktop and mobile, as far as add-ons that appear on AMO.
> is there a catch to that? probably. there usually is. like you said, it
> could mean they lurch down the path of disabling useful API access bc "that API isn't compatible with mobile so efya!"
> if that is what happens, I guarantee most or at least a lot of us will
> continue to come back here, so thank ya for ya work and ye, mo devs would be cool fashir.
> the cynical view is that they would be working toward that lowest common
> denominator because it's the road to building a web that is manifest v2 only which means trusted-only, no useful usable apis, etc.
> so if I cast it like it's a sure thing there's no point in any of this
> I'm sorry, that's not how I feel at all. I am like you very very suspicious toward these on the surface "welcome" appearing changes.
> — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID:
> ***@***.***>

yeah that's the sensible approach. I guess we'll see when 120/121/122 is out for Android. hope that's the way it turns out. judging by the last three years you dont take it as a given even though it is normally the obvious route.
hope you are doing well btw

**Comment by akliuxingyuan** [comment]
Hi @CharmCityCrab, I see that you are actively participating in and paying attention to this project. Are you willing to clone [What-I-want-on-Fenix](https://addons.mozilla.org/en-US/firefox/collections/16201230/What-I-want-on-Fenix/) and maintain it as a new default add-on collection?

**Comment by danhawkes** [comment]
Hi @akliuxingyuan. @CharmCityCrab says they're unable to comment in this thread, so may not be able to reply to your question. https://github.com/fork-maintainers/iceraven-browser/issues/691#issue-2007501733

However, now that 120 is out, I think cloning the What-I-want-on-Fenix collection with the aim of adding further extensions is wasted effort.

It seems it's now possible to install any extension that declares itself compatible with FF mobile via the `gecko_android` compatibility version. E.g:
```
"browser_specific_settings": {
  "gecko": {
    "strict_min_version": "102.0"
  },
  "gecko_android": {
    "strict_min_version": "113.0"
  }
}
```
https://extensionworkshop.com/documentation/develop/developing-extensions-for-firefox-for-android/#check-for-firefox-for-android-compatibility

Users that want to install extensions that lack this declaration (such as [get-tech-stack](https://addons.mozilla.org/en-US/firefox/addon/get-tech-stack/)), should probably ask their maintainers to update them appropriately, or maintain a private collection.

**Comment by danhawkes** [comment]
In terms of the impact of changing Iceraven's default collection, I think we have several sets of users to think about:

- New installations. These users won't see any breaking change, as they start with no installed extensions. They'll just see a different default list of extensions in the native 'Add-ons' manager UI.
- Existing users of the Iceraven default collection.
  - Those with installed extensions that are now `gecko_android` compatible will be unaffected.
  - Those with installed extensions that are _not_ `gecko_android` compatible will be unaffected in the short term: the extensions will remain installed and continue to receive updates. In the longer term, if they uninstall an extension that is not `gecko_android` compatible, they'll not be able to re-install it without one of the above workarounds.
- Existing users who've set a custom add-on collection. Presumably any change of the default collection would not overwrite these users' settings, so they won't be affected.

**Comment by mzso** [comment]
@danhawkes 

> Users that want to install extensions that lack this declaration (such as [get-tech-stack](https://addons.mozilla.org/en-US/firefox/addon/get-tech-stack/)), should probably ask their maintainers to update them appropriately, or maintain a private collection.

Or maybe ask for a switch to ignore this in Iceraven? :)

**Comment by danhawkes** [comment]
@Candlemass 
> Especially when we have no timeline regarding when iceraven will be updated with the full feature set of 120 which we haven't even seen confirmation of whether desktop extensions function on mobile yet...

I'm confused about this: isn't Iceraven already built on top of the 120 codebase? It seems to have support for installing extensions from AMO, as well as XPIs from disk.

![1](https://github.com/fork-maintainers/iceraven-browser/assets/3388897/5a6853b0-c776-48b8-aa6d-bb35c55da0f5) ![2](https://github.com/fork-maintainers/iceraven-browser/assets/3388897/4a41ea22-2434-48f5-9ee0-dfd211da1433)

> Seriously, what's so difficult about updating the list? 

It's not! You can volunteer to do it: https://github.com/fork-maintainers/iceraven-browser/issues/684#issuecomment-1829546377

**Comment by danhawkes** [comment]
> @danhawkes
> 
> > Users that want to install extensions that lack this declaration (such as [get-tech-stack](https://addons.mozilla.org/en-US/firefox/addon/get-tech-stack/)), should probably ask their maintainers to update them appropriately, or maintain a private collection.
> 
> Or maybe ask for a switch to ignore this in Iceraven? :)

If we're talking about downloading desktop extensions from [addons.mozilla.org](https://addons.mozilla.org), that switch would need to modify how the website behaves, either by messing with the JS it uses, or sending a desktop user-agent to 'trick' it into treating Iceraven as a desktop browser. 

The former's an invasive and fragile solution, that will likely require maintenance to keep working, and the latter is already there (albeit manual), via the 'Desktop site' toggle:

E.g. this is me installing 'get tech stack':
![3](https://github.com/fork-maintainers/iceraven-browser/assets/3388897/11165ac0-eb13-442c-a273-6411b9b14929)

**Comment by Candlemass** [comment]
> @danhawkes
> 
> > Users that want to install extensions that lack this declaration (such as [get-tech-stack](https://addons.mozilla.org/en-US/firefox/addon/get-tech-stack/)), should probably ask their maintainers to update them appropriately, or maintain a private collection.
> 
> Or maybe ask for a switch to ignore this in Iceraven? :)

I see no way to add extensions to the list in the link you provided. Please elaborate.

**Comment by Candlemass** [comment]
> @Candlemass
> 
> > Especially when we have no timeline regarding when iceraven will be updated with the full feature set of 120 which we haven't even seen confirmation of whether desktop extensions function on mobile yet...
> 
> I'm confused about this: isn't Iceraven already built on top of the 120 codebase? It seems to have support for installing extensions from AMO, as well as XPIs from disk.
> 
> ![1](https://private-user-images.githubusercontent.com/3388897/288798856-5a6853b0-c776-48b8-aa6d-bb35c55da0f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzI0NzMsIm5iZiI6MTcwMjEzMjE3MywicGF0aCI6Ii8zMzg4ODk3LzI4ODc5ODg1Ni01YTY4NTNiMC1jNzc2LTQ4YjgtYWE2ZC1iYjM1YzU1ZGEwZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMTQyOTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTE0YTg4MDZjZDFiMjNjM2ZkNTRkNzhlNjMzOGRkZTJhN2QxYTVkYWRlMDM2YmQwMWU1N2VjNmI4N2QxOWJlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-X4VrbBMc1FqGl-2hySeJRzSm7yIJOkA_pznhFhaJ_k) ![2](https://private-user-images.githubusercontent.com/3388897/288798863-4a41ea22-2434-48f5-9ee0-dfd211da1433.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzI0NzMsIm5iZiI6MTcwMjEzMjE3MywicGF0aCI6Ii8zMzg4ODk3LzI4ODc5ODg2My00YTQxZWEyMi0yNDM0LTQ4ZjUtOWVlMC1kZmQyMTFkYTE0MzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMTQyOTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ5OWYzMmU5ODRjZGUxNWQxOGMwY2Y3YmYyYTVkMjI3MzJjY2U3NjRlZGQ4MzdlYWJlYWViZmYzNjNlZmViZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SC_VPoUMDPegEfY2qw6A1B9i4isqm4z0llMq8MCz95M)
> 
> > Seriously, what's so difficult about updating the list?
> 
> It's not! You can volunteer to do it: [#684 (comment)](https://github.com/fork-maintainers/iceraven-browser/issues/684#issuecomment-1829546377)

**Comment by Candlemass** [comment]
> @Candlemass
> 
> > Especially when we have no timeline regarding when iceraven will be updated with the full feature set of 120 which we haven't even seen confirmation of whether desktop extensions function on mobile yet...
> 
> I'm confused about this: isn't Iceraven already built on top of the 120 codebase? It seems to have support for installing extensions from AMO, as well as XPIs from disk.
> 
> ![1](https://private-user-images.githubusercontent.com/3388897/288798856-5a6853b0-c776-48b8-aa6d-bb35c55da0f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzI0NzMsIm5iZiI6MTcwMjEzMjE3MywicGF0aCI6Ii8zMzg4ODk3LzI4ODc5ODg1Ni01YTY4NTNiMC1jNzc2LTQ4YjgtYWE2ZC1iYjM1YzU1ZGEwZjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMTQyOTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTE0YTg4MDZjZDFiMjNjM2ZkNTRkNzhlNjMzOGRkZTJhN2QxYTVkYWRlMDM2YmQwMWU1N2VjNmI4N2QxOWJlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.-X4VrbBMc1FqGl-2hySeJRzSm7yIJOkA_pznhFhaJ_k) ![2](https://private-user-images.githubusercontent.com/3388897/288798863-4a41ea22-2434-48f5-9ee0-dfd211da1433.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzI0NzMsIm5iZiI6MTcwMjEzMjE3MywicGF0aCI6Ii8zMzg4ODk3LzI4ODc5ODg2My00YTQxZWEyMi0yNDM0LTQ4ZjUtOWVlMC1kZmQyMTFkYTE0MzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMTQyOTMzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWQ5OWYzMmU5ODRjZGUxNWQxOGMwY2Y3YmYyYTVkMjI3MzJjY2U3NjRlZGQ4MzdlYWJlYWViZmYzNjNlZmViZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SC_VPoUMDPegEfY2qw6A1B9i4isqm4z0llMq8MCz95M)
> 
> > Seriously, what's so difficult about updating the list?
> 
> It's not! You can volunteer to do it: [#684 (comment)](https://github.com/fork-maintainers/iceraven-browser/issues/684#issuecomment-1829546377)

I see no way to add extensions to the list in the link you provided. Please elaborate.
