### ISSUE TITLE
Some add-ons "don't load"

### ISSUE THREAD

**Issue by rsssxd** [fork-maintainers/iceraven-browser#7]
![Screenshot_20200819-011851_Iceweasel_1](https://user-images.githubusercontent.com/60405617/90571580-ba100480-e1ba-11ea-9815-6ba5cdb6a2eb.png)
![Screenshot_20200819-011837_Iceweasel_1](https://user-images.githubusercontent.com/60405617/90571589-c005e580-e1ba-11ea-8e1b-a2e3097d65b5.png)
These two addons don't load

**Comment by interfect** [comment]
Do you mean they don't work when installed? Or does the browser seem to be refusing to install them?

Unfortunately, getting them to actually work is a job for the add-on devs (to work around the missing parts of WebExtension support) or for upstream android-components (to actually implement the missing parts), not for this fork repo specifically. Either way, it would be most useful to break out the extension development/debugging tools (which I'm not quite sure how to do) and work out what exactly the extensions want that the browser can't yet give them, so that those particular parts can be bumped up the to do list or worked around.

But if the browser somehow thinks they aren't allowed to be installed, that's a problem for this repo.

**Comment by eNV25** [comment]
This may be that you are trying to install multiple add-ons at the same time and it git stuck. It happened to me. Have you tried again but one at a time?
 @reyis4402

**Comment by rsssxd** [comment]
Yep

**Comment by ghost** [comment]
This issue is same as I faced in https://github.com/interfect/fenix/issues/33
@interfect

**Comment by eNV25** [comment]
Then we should probably leave it at that. Once mozilla supports more extensions they will address this.

**Comment by interfect** [comment]
I've pulled Video DownloadHelper as describes in #33 because multiple people are reporting it not installing at all. I've just tested Buster and it immediately failed to install at all for me, so I'm pulling it too.
