### ISSUE TITLE
install xpi

### ISSUE THREAD

**Issue by culinaxok** [fork-maintainers/iceraven-browser#723]
can i install xpi extension? how to install. thanks

**Comment by seniordevel** [comment]
There is still a need for a way to install xpi files from local sources. For us developers, it is highly cumbersome to set up a Mozilla collective account. I will never support this for testing and developing addons. Non-developers would never use a hidden option that allows local files to be installed. They won't understand or trust to do so. So, what are your concerns?

Stop hesitating with restoring former Firefox abilities as beeing suitable for our limitated android display. 

For 10 years you have seen how many users Firefox lost because of wrong management.
Massive loss of features, increasingly being user unfriendly.

Reverse it or loose

**Comment by CharmCityCrab** [comment]
Iceraven does support installing extensions from local files.  

It was added in the November 30, 2023 update and should work with all of the more recent updates beyond that point as well.

Hamburger menu>Settings>Add-Ons>Puzzle Piece Icon

**Comment by seniordevel** [comment]
menu>Settings>Add-Ons>Puzzle Piece Icon

Thank you for answering CharmCityCrab.

Unfortunately it seems to work with signed addons only, thus it is useless for me.
Loading unsigned addons that way simply results in Iceraven crashing. At least due to my experience.
 
Devolpment means you start from  the scratch, your addon is un-signed, you need to test dozens of times a week ... for a month or even far longer.
You don't want to go through a process of uploading, filling forms and waiting for signing by Mozilla - again and again.

Installation from local file sources should be unrestricted, working as known from desktop firefox 10 years ago.

Just make about:config item: xpiinstall.signatures.required=false working as the setting suggests.

**Comment by akliuxingyuan** [comment]
As CharmCityCrab described, we already support side-loading addons,
and setting `xpinstall.signatures.required` to false in about:config is required for unsigned xpi installation purpose

**Comment by 0402mexx** [comment]
Currently this feature seems to be broken.
Even if setting xpiinstall.signatures.required=false.
What version can I install to install handmaid xpi.
