### ISSUE TITLE
Switch to a more privacy respectful search engine

### ISSUE THREAD

**Issue by TheEvilSkeleton** [fork-maintainers/iceraven-browser#80]
### What is the user problem or growth opportunity you want to see solved?

Google is an anti-private corporation. I personally think that we should switch to a more privacy respecting metasearch/search engine like Searx, DuckDuckGo, etc.

### How do you know that this problem exists today? Why is this important?

A lot of people care about their privacy. Google doesn't respect users' privacy and treat our information unethically.

### Who will benefit from it?

Everyone

**Comment by interfect** [comment]
Yeah. Google's not paying us, so the default search engine probably shouldn't be Google.

DuckDuckGo is quite popular, and already included on the list by default. Maybe we can swap over to it.

I'm not really sure where this is configured, though.

**Comment by CharmCityCrab** [comment]
I agree.  My specific recommendation would be DuckDuckGo.

I do think that Google should be included as an option, though, and,  _if possible_, when making a change, people's existing search engine preferences should be respected (Firefox for desktop made a change in search engines that flipped everyone's search engines to Yahoo [They had a deal with Yahoo at that the time, which has since been terminated and replaced by a deal with Google] a few years back.  Users could flip their browser's individual defaults right back to Google or whatever, but it would up being a big controversy anyway.).

Thus, everyone currently using Iceweasel would continue to use the search engine they have already chosen (or left in place), but any new users (Or users with fresh profiles from installing on a new phone or whatever) would get DuckDuckGo as the default and have Google, Bing, and so forth as alternative choices they can set in options.

**Comment by jaytohe** [comment]
Yeah I think we should go with DDG as default.

**Comment by bbigam** [comment]
I think it must be configured somewhere in here, but I sure can't figure out how to change it: https://github.com/fork-maintainers/iceweasel/tree/fork/app/src/main/java/org/mozilla/fenix/settings/search

**Comment by interfect** [comment]
I think we need to override this file from android-components somehow: https://github.com/mozilla-mobile/android-components/blob/4f8ae49dff1db9e4a72b5713244a0756641e878e/components/browser/search/src/main/assets/search/list.json

We already have an assets directory, with a few of its own search plugins:

https://github.com/fork-maintainers/iceweasel/tree/fork/app/src/main/assets

I think this is all controlled from https://github.com/fork-maintainers/iceweasel/blob/fork/app/src/main/java/org/mozilla/fenix/components/searchengine/FenixSearchEngineProvider.kt

I'm not sure if we can just add a new JSON asset in the app's assets, with a different default set, and have it automatically override the one from android-components, or if we need to fork [AssetsSearchEngineProvider](https://github.com/mozilla-mobile/android-components/blob/0094209ac99076787f4e2d3693fff4aa60c40472/docs/api/mozilla.components.browser.search.provider/-assets-search-engine-provider/index.md) somehow.

**Comment by linsui** [comment]
Any update here? Please also remove baidu and taobao for Chinese users. Thanks!

**Comment by L31FY** [comment]
Can I give a recommendation to Qwant instead? DDG is just Google without calling it Google in a lot of ways.

**Comment by CharmCityCrab** [comment]
> Can I give a recommendation to Qwant instead? DDG is just Google without calling it Google in a lot of ways.

Actually, DDG doesn't use Google search results at all in its standard results (Some people use it as a sideways way to load Google results through a feature called "Bangs", but if you just use DDG in the usual fashion one would use a search engine, Google plays no part in it).  It draws primarily from Bing, but also has its own limited web crawler and hundreds of minor specialized sources that it includes in the mix of some search results.

I don't know much about Qwant, but some information I see about it online suggests that it may do better with French than English.  Having Macron's endorsement is pretty cool for such a small search engine, though!

I would favor having both on the default list, but making DDG the actual default search engine.

Maybe Qwant could replace Amazon on that list, which would make it DDG (default), Qwant, Google, Bing, and Wikipedia.  

Though I have nothing against Amazon in general, having one of the default search engine choices be solely devoted to doing searches on merchandise in one solo store seems a bit odd- I would think that they are paying Mozilla for that, but they aren't paying Iceraven, so...

After the two we like, Google and Bing being built in options makes sense because a lot of users will only use Google, and then Bing is the largest Google competitor, and I think that makes Bing worth including also.  If nothing else, the volume of issues people would open and trash talking they'd do all over the Internet about Google not being available as a maintained option would make not including it not worth it (But it shouldn't be the default, which is a point I think we all agree with).

So, we'd get two small privacy respecting search engines and the two industry leading search engines.  That'd be a good array of choice (And of course people could individually add whatever they want). The fifth current option is Wikipedia, which makes sense because probably half of all searches (I made up that percentage) are actually going to end in Wikipedia entries eventually anyway, and it is important enough to the web to be worth supporting.

However, if we were to choose not to have Wikipedia there, we could also add something like Startpage or Onesearch, which are similar to DDG and Qwant in their missions, but have more people who are critical or distrustful of the companies that own them (Which is why they would only be the third choice in the the small search engine subcategory and the other would be left out). I am assuming we are limited to including five out of the box. Of course people can individually add their own.

Another thought would be that perhaps we should consider just having one list for the entire world rather than trying to maintain a bunch of separate localized search engine lists to include depending on where someone lives.  It might be easier to maintain.

**Comment by linsui** [comment]
I guess we don't need to limit it to 5 default engines?

**Comment by CharmCityCrab** [comment]
> I guess we don't need to limit it to 5 default engines?

To be honest, I have no idea. It probably depends on how it's coded currently.  It may be that it's set up for an assumption of five choices and simply making substitutions as to what the choices are is one level of difficulty, but is ultimately still sort of keeping the five level bookshelf and just swapping some of the books in and out and changing their order, whereas adding additional options *may* be another level of difficulty that involves tearing down, rebuilding, and expanding the bookshelf itself as well as changing the books.

Of course, if users can add custom search engines just by visiting them (Can we?  One never knows what choices were taken away by Mozilla when Fenix was released that one may suddenly find yet another example of on any given day.  Iceraven has done a good job of restoring a lot of options like that to us, though.), it would seem as though if the coding were difficult were difficult to truly expand from five presets naturally, perhaps an approach would be to sort of auto-add more at the bottom at browser install so that to the end user just looking at the browser, it comes with more than 5 pre-set options, even if the top five are actually privledged slightly in the code.

Anyway, technically this is just an issue about changing the default. :). So, I guess that's the thing to start with.

**Comment by linsui** [comment]
Well, I'm sure there is no FIVE limitation because there are SIX default ones in my Firefox and TWO another ones can be added.

**Comment by akliuxingyuan** [comment]
I try to add a new search engine Startpage in https://github.com/fork-maintainers/iceraven-browser/releases/tag/iceraven-2.10.3 and it works fine
we can add more privacy search engines

**Comment by akliuxingyuan** [comment]
Switched to DuckDuckGo in https://github.com/fork-maintainers/iceraven-browser/releases/tag/iceraven-2.10.4
