### ISSUE TITLE
Suggestion: rebase from upstream beta

### ISSUE THREAD

**Issue by bbigam** [fork-maintainers/iceraven-browser#93]
Upstream Fenix is still under heavy development, often adding new features. For example, they're currently adding optional top sites from history, and (my favorite) finally an option to disable _all_ autocompletion. Look at the releases for more info: https://github.com/mozilla-mobile/fenix/releases

We could get those newer features here more quickly if we rebased on Fenix Beta, at least until the release branch reaches a more feature-complete status. And Beta is really pretty stable for end users (unlike Nightly which sometimes has horrible bugs).

I wouldn't know how to do this rebase, and I'm open to hearing that it's a bad idea! But I thought it worth the suggestion.

**Comment by abhijitvalluri** [comment]
I cannot tell with 100% confidence, but it looks like the beta versions are branched out from an older point of the master branch and have a few small changes there. So, most likely the releases we are creating here from the master branch are newer than the Betas and so will have even more features faster! But they can definitely be more buggy due to it being cutting edge. While it is not a bad idea to use the beta branches to create releases, it may be more overhead to constantly keep track of the beta branches and merge them to our fork branch. It may add lot more complexity compared to just keeping track of mozilla-mobile/master and merging/rebasing that into our fork branch.

**Comment by bbigam** [comment]
Ah, and I see that your latest rebase actually brings in some of those features. Maybe we don't need this after all.
